# This ingress allows HTTP basic authentication on the basicauth domain, to
# allow for easier machine access to Prometheus.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-tls-basic
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prometheus-data-pipeline-basic.{{GCLOUD_PROJECT}}.measurementlab.net
    secretName: prometheus-basic-tls
  rules:
  - host: prometheus-data-pipeline-basic.{{GCLOUD_PROJECT}}.measurementlab.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
