WITH site_city_country AS (
  SELECT
    CASE
    WHEN date between DATE_SUB(CURRENT_DATE(), INTERVAL 360 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 353 DAY)
      THEN "-360"
    WHEN date between DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 173 DAY)
      THEN "-180"
    WHEN date between DATE_SUB(CURRENT_DATE(), INTERVAL  90 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 83 DAY)
      THEN "-090"
    WHEN date between DATE_SUB(CURRENT_DATE(), INTERVAL  30 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 23 DAY)
      THEN "-030"
    WHEN date between DATE_SUB(CURRENT_DATE(), INTERVAL   7 DAY) AND CURRENT_DATE()
      THEN "-007"
    ELSE
      "ignore"
    END as period,
    server.Site AS site,
    REGEXP_EXTRACT(server.Site, "([a-z]{3}).*") AS city,
    server.Geo.CountryCode AS country
  FROM
    `measurement-lab.ndt.ndt7`
  WHERE
       date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 360 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 353 DAY)
    OR date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 173 DAY)
    OR date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL  90 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 83 DAY)
    OR date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL  30 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 23 DAY)
    OR date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL   7 DAY) AND CURRENT_DATE()
)

SELECT
  period,
  COUNT(distinct site) AS value_sites_count,
  COUNT(distinct city) AS value_cities_count,
  COUNT(distinct country) AS value_countries_count
FROM
  site_city_country
GROUP BY
  period
ORDER BY
  period
