apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

deleteDatasources:
- name: BigQuery (mlab-oti)
  orgId: 1
- name: BigQuery (mlab-staging)
  orgId: 1
- name: BigQuery (mlab-sandbox)
  orgId: 1
- name: Google BigQuery (mlab-ns)
  orgId: 1

