{
 "title": "Alert: PlatformCluster_PusherDailyDataVolumeTooLow",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "sandbox,staging,oti" },
   { "name": "cluster", "query": "prometheus" },
   { "name": "federation", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Successful Bytes Uploaded over 24hrs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "datatype:pusher_bytes_per_tarfile:increase24h",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "Upload Retries (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (increase(pusher_retries_total[5m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Tarfile Size Histogram",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(le) (increase(pusher_bytes_per_tarfile_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Aggregate Pusher Bytes per Archive",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum by(le) (increase(pusher_bytes_per_tarfile_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Successful Tarfile Uploads (per Experiment)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (rate (pusher_tarfiles_successful_uploads_total[5m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Successful Tarfile Uploads (per Datatype)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(datatype) (rate (pusher_tarfiles_successful_uploads_total[5m]))",
     "legendFormat": "{{datatype}}"
    }
   ]
  }
 ]
}