{
 "title": "Alert: ScriptExporterDownOrMissing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "query": "oti,staging,sandbox" },
   { "name": "cluster", "query": "prometheus" },
   { "name": "federation", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Current \"Script Successes\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(script) (script_success)",
     "legendFormat": "{{script}}"
    }
   ]
  },
  {
   "title": "Target Counts for job=script-exporter-federation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (service) (script_success{job=\"script-targets-federation\"})",
     "legendFormat": "{{service}} targets"
    }
   ]
  },
  {
   "title": "up{deployment=\"script-exporter\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ready) (up{deployment=\"script-exporter\"})"
    }
   ]
  },
  {
   "title": "NDT5 - monitoring tests run in last 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ndt_test_rate_mbps_count{direction=\"s2c\", monitoring=\"true\"}[5m]))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(increase(ndt_test_rate_mbps_count{direction=\"s2c\", monitoring=\"true\"}[5m] offset 7d))",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Median E2E Test Rates (Mbps) by protocol",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=\"s2c\", monitoring=\"true\"}[5m])) by (le, protocol))",
     "legendFormat": " {{protocol}}"
    }
   ]
  }
 ]
}