{
 "title": "Alert: ScraperMostRecentArchivedFileTimeIsTooOld",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "alertname", "label": "Alert name", "query": "label_values(alertname)" },
   { "name": "site", "label": "Site", "query": "label_values(machine)" }
  ]
 },
 "panels": [
  {
   "title": "$alertname for $site",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"$alertname\", machine=~\".*$site.*\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Global Alerts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count by(alertname) (ALERTS)", "legendFormat": "{{alertname}}" }
   ]
  },
  {
   "title": "ScraperMostRecentArchivedFileTimeIsTooOld $site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(time() - (scraper_maxrawfiletimearchived{container=\"scraper-sync\", machine=~\".*$site.*\"} != 0)) > (36 * 60 * 60) and ON(machine) (time() - process_start_time_seconds{service=\"sidestream\", machine=~\".*$site.*\"}) > (30 * 60 * 60)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "ScraperRunningWithoutRsyncd $site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "up{container=\"scraper\", machine=~\".*$site.*\"} unless ON(machine, experiment) up{service=\"rsyncd\", machine=~\".*$site.*\"}",
     "legendFormat": "{{machine}} {{experiment}}"
    }
   ]
  },
  {
   "title": "ScraperMostRecentArchivedFileTimeIsTooOld $site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() - (scraper_maxrawfiletimearchived{container=\"scraper-sync\", machine=~\".*$site.*\"} != 0)) < 12 * 24 * 60 * 60",
     "legendFormat": "{{machine}}"
    }
   ]
  }
 ]
}