{
 "title": "Archive Repacker (Annotations)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"reannotator\"}[3m])",
     "legendFormat": "reannotator {{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{container=\"renamer\"}[3m])",
     "legendFormat": "renamer {{instance}}"
    }
   ]
  },
  {
   "title": "RSS RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"reannotator\"}",
     "legendFormat": "reannotator {{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{container=\"renamer\"}",
     "legendFormat": "renamer {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(.95, go_memstats_heap_objects{container=\"reannotator\"})",
     "legendFormat": "p95 - reannotator"
    },
    {
     "expr": "quantile(.95, go_memstats_heap_objects{container=\"renamer\"})",
     "legendFormat": "p95 - renamer"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(go_info{container=\"reannotator\"})",
     "legendFormat": "reannotator"
    },
    {
     "expr": "count(go_info{container=\"renamer\"})",
     "legendFormat": "renamer"
    }
   ]
  },
  {
   "title": "Job Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "jobserver_status_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Dates processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    { "expr": "(repacker_date)*1000 ", "legendFormat": "reannotator" },
    { "expr": "(renamer_date)*1000", "legendFormat": "renamer" }
   ]
  },
  {
   "title": "Job Completion Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (increase(repacker_date_completion_time_bucket[10m])) OR sum by (le) (increase(renamer_date_completion_time_bucket[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query results processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(repacker_query_results_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (le) (increase(jobserver_update_duration_seconds_bucket[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Jobs Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(repacker_dates_started_total[5m]))",
     "legendFormat": "Dates started"
    },
    {
     "expr": "jobserver_status_count{status=\"leased\"}",
     "legendFormat": "Jobs Leased"
    }
   ]
  },
  {
   "title": "Archive completion time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (le) (increase(repacker_archive_completion_time_bucket[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query completion time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (le) (increase(repacker_query_completion_time_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query errors & Files missing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(repacker_query_errors_total[$__rate_interval]))\n",
     "legendFormat": "Query errors"
    },
    {
     "expr": "sum(increase(repacker_query_files_missing_total[$__rate_interval])) / sum(increase(repacker_annotations_total[$__rate_interval]))",
     "legendFormat": "Query files missing"
    },
    {
     "expr": "sum(rate(repacker_query_read_errors_total[$__rate_interval]))\n",
     "legendFormat": "Query read errors"
    },
    {
     "expr": "sum(rate(repacker_query_files_corrupt_total[$__rate_interval]))\n",
     "legendFormat": "Corrupt Files"
    },
    {
     "expr": "sum(increase(repacker_query_files_missing_total[$__range]))",
     "legendFormat": "Absolute Missing files count"
    }
   ]
  },
  {
   "title": "Annotation status percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(repacker_annotations_total[2m])) / ignoring(status) group_left() sum (rate(repacker_annotations_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Archives Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(repacker_archives_total[2m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(jobserver_update_duration_seconds_count[2m])  ",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(renamer_archives_total[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}