{
 "title": "Autojoin",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasourceAutojoin", "query": "prometheus" },
   { "name": "datasourcePlatform", "query": "prometheus" },
   { "name": "bigquery", "query": "grafana-bigquery-datasource" },
   {
    "name": "org",
    "query": {
     "query": "label_values(ndt_test_rate_mbps_count,org)"
    }
   },
   {
    "name": "metro",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Status ${metro}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(ndt7_measurer_bbr_enabled_total{status=\"true\", machine=~\".*${metro:regex}.*\"}) > 0)",
     "legendFormat": "ndt7"
    },
    {
     "expr": "count(jostler_bytes_per_bundle_count{datatype=\"ndt7\", machine=~\".*${metro:regex}.*\"} > 0)",
     "legendFormat": "jostler"
    },
    {
     "expr": "count(heartbeat_health_endpoint_checks_total{status=\"OK\", machine=~\".*${metro:regex}.*\"} > 0)",
     "legendFormat": "heartbeat"
    },
    {
     "expr": "count(uuid_annotator_annotation_errors_total{machine=~\".*${metro:regex}.*\"} == 0)",
     "legendFormat": "uuid-annotator"
    },
    {
     "expr": "count(traces_performed_total{exported_type=\"scamper\", machine=~\".*${metro:regex}.*\"} > 0)",
     "legendFormat": "traceroute"
    }
   ]
  },
  {
   "title": "Prometheus: Percent of NDT TX Rejections ($metro)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(site) (label_replace(rate(controller_access_txcontroller_requests_total{request=\"rejected\", machine=~\".*${metro:regex}.*\"}[15m]), \"site\", \"$1\", \"machine\", \"ndt-([a-z]{3}[^-]+)-.*\")) / \n  sum by(site) (label_replace(rate(controller_access_txcontroller_requests_total{machine=~\".*${metro:regex}.*\"}[15m]), \"site\", \"$1\", \"machine\", \"ndt-([a-z]{3}[^-]+)-.*\"))",
     "legendFormat": "{{site}}"
    },
    {
     "expr": "sum by(site) (rate(controller_access_txcontroller_requests_total{request=\"rejected\", machine=~\".*${metro:regex}.*\"}[15m])) / \n  sum by(site) (rate(controller_access_txcontroller_requests_total{machine=~\".*${metro:regex}.*\"}[15m]) )",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Prometheus: NDT Download Counts ($metro)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "60 * sum by(direction, site) (rate(ndt_test_rate_mbps_count{direction=\"download\", machine=~\".*(${metro:regex}).*\"}[5m]))\n",
     "legendFormat": "{{site}}"
    },
    {
     "expr": "60 * sum by(direction, org, site) (label_replace(rate(ndt_test_rate_mbps_count{deployment=\"byos\", direction=\"download\",  machine=~\".*(${metro:regex}).*\"}[5m]), \"site\", \"$1\", \"machine\", \"ndt-([a-z]{3}[^-]+)-.*\"))\n",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Prometheus: Aggregate Download Rate Heatmap ($metro)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(ndt_test_rate_mbps_bucket{direction=~\"download\", monitoring=\"false\", machine=~\".*${metro:regex}.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "BigQuery: Row Counts per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "/* TODO: figure out per-org labels */\nSELECT time, org as metric, count(*) as total FROM (\nSELECT TIMESTAMP_TRUNC(raw.StartTime, HOUR) as time, server.Site as org,\nFROM `mlab-autojoin.autoload_v2_ndt.ndt7_union`\nWHERE date BETWEEN  \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\" AND server.Site is not NULL\n AND REGEXP_CONTAINS(server.Site, \"${metro:regex}\")\nUNION ALL\nSELECT TIMESTAMP_TRUNC(raw.StartTime, HOUR) as time, server.Site as org\nFROM `mlab-oti.ndt.ndt7`\nWHERE date BETWEEN  \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\" AND server.Site is not NULL\n AND REGEXP_CONTAINS(server.Site, \".*${metro:regex}.*\")\n)\ngroup by time, org\norder by time,org"
    }
   ]
  },
  {
   "title": "BigQuery: Download Mbps",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT * FROM (\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf_byosraw`(0.1, 3500, \"MeanThroughputMbps\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\nUNION ALL\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf`(0.1, 3500, \"MeanThroughputMbps\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\n)\nORDER BY xright, site"
    }
   ]
  },
  {
   "title": "BigQuery: Download MinRTT",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT * FROM (\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf_byosraw`(0.1, 500, \"MinRTT\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\nUNION ALL\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf`(0.1, 500, \"MinRTT\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\n)\nORDER BY xright, site"
    }
   ]
  },
  {
   "title": "BigQuery: Download LossRates",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT * FROM (\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf_byosraw`(1e-6, 1, \"LossRate\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\nUNION ALL\nSELECT\n  xright,\n  CASE \"pdf\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf`(1e-6, 1, \"LossRate\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}.*\")\n)\nORDER BY xright, site"
    }
   ]
  }
 ]
}