{
 "title": "Autojoin: Site Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "gkedatasource", "label": "GKE Datasource", "query": "prometheus" },
   {
    "name": "org",
    "label": "Org",
    "query": {
     "query": "label_values(node_time_seconds,machine)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(node_time_seconds,machine)"
    }
   },
   {
    "name": "machine",
    "label": "Machine",
    "query": {
     "query": "label_values(node_time_seconds,machine)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "site",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (days)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{machine=~\"ndt-$site-.*\"}) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Load Avg (15m)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{machine=~\"ndt-$site.*\"}"
    }
   ]
  },
  {
   "title": "Rootfs Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", machine=~\"ndt-$site-.*\"} -\n    node_filesystem_avail_bytes{mountpoint=\"/\", machine=~\"ndt-$site-.*\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", machine=~\"ndt-$site-.*\"}"
    }
   ]
  },
  {
   "title": "E2E Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "script_success{machine=~\"ndt-$site-$machine.*\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Average sec/sec usage across all CPUs available to the machine.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by (machine) (rate(node_cpu_seconds_total{machine=~\"ndt-$site-.*\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "$node-$site"
    }
   ]
  },
  {
   "title": "Memory (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{machine=~\"ndt-$site-.*\"}\n+ node_memory_Buffers_bytes\n+ node_memory_SReclaimable_bytes",
     "legendFormat": "Buff/Cache"
    },
    {
     "expr": "node_memory_Active_bytes{machine=~\"ndt-$site-.*\"}\n+ node_memory_Active_anon_bytes\n+ node_memory_Active_file_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{machine=~\"ndt-$site-.*\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device!~\"(lo|br-.+|docker[0-9])\", machine=~\"ndt-$site-.*\"}[$__rate_interval])",
     "legendFormat": "TX {{device}}"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device!~\"(lo|br-.+|docker[0-9])\", machine=~\"ndt-$site.*\"}[$__rate_interval])",
     "legendFormat": "RX {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{machine=~\"ndt-$site.*\"}[$__rate_interval])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{machine=~\"ndt-$site.*\"}[$__rate_interval])",
     "legendFormat": "Written ({{device}})"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{machine=~\"ndt-$site.*\"}[$__rate_interval])",
     "legendFormat": "% sec/sec ({{device}})"
    }
   ]
  }
 ]
}