{
 "title": "BigQuery: NDT7 Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "NDT7 Downloads per day by client_name",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "WITH clients AS (\n SELECT\n  TIMESTAMP(date) as time,\n  (SELECT metadata.Value FROM UNNEST(raw.Download.ClientMetadata) AS metadata WHERE metadata.Name = \"client_name\") as client_name\nFROM `measurement-lab.ndt.ndt7`\nWHERE\n  date between \"${__from:date:YYYY-MM-DD}\" and \"${__to:date:YYYY-MM-DD}\"\n AND raw.Download is not NULL \n)\n\nSELECT\n  time, IF(client_name IS NULL, \"UNNAMED\", client_name) as metric, COUNT(*) as total\nFROM clients\nGROUP BY time, metric\nHAVING total > 10\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Percentage of NDT7 Downloads to Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "WITH ndt7 AS (\nSELECT *, metadata\nFROM `measurement-lab.ndt.ndt7`, UNNEST(raw.Download.ServerMetadata) as metadata\nWHERE date BETWEEN \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\"\n AND server.Site is not NULL\n AND raw.Download is not NULL \n AND metadata.Name = \"type\"\n)\n\n/*\nSELECT TIMESTAMP(date) as time, \"virtual\" as metric, COUNTIF(metadata.Value=\"virtual\")/COUNT(*) as ratio FROM ndt7 GROUP BY date, metric\nUNION ALL \nSELECT TIMESTAMP(date) as time, \"physical\" as metric, COUNTIF(metadata.Value=\"physical\")/COUNT(*) as ratio FROM ndt7 GROUP BY date, metric\n*/\n\nSELECT time, metric, total / SUM(total) OVER(partition by time) as ratio FROM (\nSELECT TIMESTAMP(date) as time, metadata.Value as metric, COUNT(*) as total FROM ndt7 GROUP BY date, metric\n) order by time\n\n/*SELECT\n    date, COUNTIF(metadata.Value=\"virtual\") as virtual_total, COUNTIF(metadata.Value=\"physical\") as physical_total, COUNT(*) as total, COUNTIF(metadata.Value=\"virtual\")/COUNT(*) as virtual_ratio\nFROM `measurement-lab.ndt.ndt7`, UNNEST(raw.Download.ServerMetadata) as metadata\nWHERE\n     date > \"2022-10-01\"\n\nGROUP BY date\nORDER BY date\n*/\n\n"
    }
   ]
  },
  {
   "title": "NDT7 Downloads per day by GCP Zone",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "SELECT TIMESTAMP(date), CONCAT(server.Site, \"-\", metadata.Value) as metric, count(*) as total \nFROM `measurement-lab.ndt.ndt7`, UNNEST(raw.Download.ServerMetadata) as metadata\nWHERE date between  \"${__from:date:YYYY-MM-DD}\" and \"${__to:date:YYYY-MM-DD}\"\n AND raw.Download is not NULL \n AND metadata.Name = \"zone\"\n AND server.Site is not NULL\nGROUP BY date, metric\norder by date "
    }
   ]
  },
  {
   "title": "Total tests per Country per day",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": " \n  SELECT\n    TIMESTAMP(date),\n    client.Geo.CountryCode as metric,\n    COUNT(*) as total,\n  FROM\n    `measurement-lab.ndt.ndt7`\n  WHERE\n    date BETWEEN \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\"\n    AND server.Geo.Longitude IS NOT NULL\n    AND server.Geo.Latitude IS NOT NULL\n    AND client.Geo.Longitude IS NOT NULL\n    AND client.Geo.Latitude IS NOT NULL\n    AND raw.Download is not NULL\n    AND client.Geo.CountryCode = server.Geo.CountryCode\n  GROUP BY date, metric\n  ORDER BY date "
    }
   ]
  },
  {
   "title": "NDT7 Download Median Rate per unique Lat/Lon pair",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "location": "US",
     "project": "mlab-oti",
     "rawSql": "WITH ndt7 AS (\n  SELECT\n    a.MeanThroughputMbps as rate,\n    client.Geo.Latitude AS latitude,\n    client.Geo.Longitude AS longitude,\n  FROM\n    `measurement-lab.ndt.ndt7`\n  WHERE\n      date BETWEEN \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\"\n    -- Basic test quality filters for safe division.\n    AND raw.Download is not NULL\n),\ntests AS (\nSELECT\n  latitude, longitude,\n  APPROX_QUANTILES(rate, 10)[OFFSET(5)] AS value,\n  COUNT(*) as value_tests,\nFROM\n  ndt7\nGROUP BY\n  latitude, longitude\nHAVING\n  value_tests > 10\n  AND value IS NOT NULL\n  AND latitude IS NOT NULL and longitude IS NOT NULL\n)\n\nSELECT CURRENT_TIMESTAMP() as time,\n   latitude, longitude, value\nFROM tests\nLIMIT 2500\n"
    }
   ]
  }
 ]
}