{
 "title": "Cloud: AppEngine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "AppEngine Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gcp_aeflex_services" }
   ]
  },
  {
   "title": "AppEngine Versions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(gcp_aeflex_versions)", "legendFormat": "Versions" }
   ]
  },
  {
   "title": "AppEngine Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(gcp_aeflex_instances)", "legendFormat": "Instances" }
   ]
  },
  {
   "title": "Inactive Instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum (gcp_aeflex_instances{container=\"service-discovery\", active=\"false\"})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum (gcp_aeflex_instances{container=\"service-discovery\", active=\"true\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Used Versions (of 210 max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(gcp_aeflex_versions{container=\"service-discovery\"}) / 210",
     "legendFormat": "% Used Versions"
    }
   ]
  }
 ]
}