{
 "title": "Cloud Storage Usage",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "grafana-bigquery-datasource" },
   { "name": "offset", "label": "Resource offset (days)", "query": "0, 365" }
  ]
 },
 "panels": [
  {
   "title": "Total User Requests / Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  proto_payload.audit_log.authentication_info.principal_email AS user,\n  TIMESTAMP_TRUNC(timestamp, HOUR) AS t,\n  COUNT(*) AS Count\nFROM \n  `gcp_logging._AllLogs`\nWHERE\n    timestamp BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\n    AND proto_payload.audit_log.authentication_info.principal_email IS NOT NULL\n    AND proto_payload.audit_log.method_name LIKE \"storage.%.%\"\n    AND proto_payload.audit_log.authentication_info.principal_email NOT LIKE \"%gserviceaccount.com\"\n    AND IF (${offset} = 0, true, REGEXP_EXTRACT(proto_payload.audit_log.resource_name, r'\\d{4}\\/\\d{2}\\/\\d{2}') <= FORMAT_DATE(\"%E4Y/%m/%d\", DATE_SUB(CURRENT_DATE(), INTERVAL ${offset} DAY)))\nGROUP BY\n  proto_payload.audit_log.authentication_info.principal_email,\n  t\nORDER BY\n  t"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  proto_payload.audit_log.authentication_info.principal_email AS user,\n  COUNT(*) AS Count\nFROM \n  `gcp_logging._AllLogs`\nWHERE\n    timestamp BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\n    AND proto_payload.audit_log.authentication_info.principal_email IS NOT NULL\n    AND proto_payload.audit_log.method_name LIKE \"storage.%.%\"\n    AND proto_payload.audit_log.authentication_info.principal_email NOT LIKE \"%gserviceaccount.com\"\n    AND IF (${offset} = 0, true, REGEXP_EXTRACT(proto_payload.audit_log.resource_name, r'\\d{4}\\/\\d{2}\\/\\d{2}') <= FORMAT_DATE(\"%E4Y/%m/%d\", DATE_SUB(CURRENT_DATE(), INTERVAL ${offset} DAY)))\nGROUP BY\n  proto_payload.audit_log.authentication_info.principal_email\nORDER BY\n  COUNT DESC"
    }
   ]
  },
  {
   "title": "User Actions / Hour (breakdown)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  proto_payload.audit_log.authentication_info.principal_email AS user,\n  TIMESTAMP_TRUNC(timestamp, HOUR) AS t,\n  proto_payload.audit_log.method_name AS action,\n  COUNT(*) AS Count\nFROM \n  `gcp_logging._AllLogs`\nWHERE\n    timestamp BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\n    AND proto_payload.audit_log.authentication_info.principal_email IS NOT NULL\n    AND proto_payload.audit_log.method_name LIKE \"storage.%.%\"\n    AND proto_payload.audit_log.authentication_info.principal_email NOT LIKE \"%gserviceaccount.com\"\n    AND IF (${offset} = 0, true, REGEXP_EXTRACT(proto_payload.audit_log.resource_name, r'\\d{4}\\/\\d{2}\\/\\d{2}') <= FORMAT_DATE(\"%E4Y/%m/%d\", DATE_SUB(CURRENT_DATE(), INTERVAL ${offset} DAY)))\nGROUP BY\n  user,\n  action,\n  t\nORDER BY\n  t"
    }
   ]
  },
  {
   "title": "Cost / Hour (staging/oti)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "ndt",
     "location": "US",
     "partitionedField": "date",
     "project": "mlab-oti",
     "rawSql": "SELECT \n  SUM(cost) AS cost, TIMESTAMP_TRUNC(usage_start_time, HOUR) AS t, sku.description\nFROM \n  `mlab-oti.billing.unified`\nWHERE \n  usage_start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\n  AND service.description LIKE '%Storage%'\nGROUP BY \n  t, sku.description\nORDER BY \n  t"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "location": "US",
     "project": "mlab-oti",
     "rawSql": "SELECT \n    proto_payload.audit_log,\n    timestamp,\nFROM \n    `gcp_logging._AllLogs`\nWHERE\n    timestamp BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\n    AND proto_payload.audit_log.authentication_info.principal_email IS NOT NULL\n    AND proto_payload.audit_log.method_name LIKE \"storage.%.%\"\n    AND proto_payload.audit_log.authentication_info.principal_email NOT LIKE \"%gserviceaccount.com\"\n    AND IF (${offset} = 0, true, REGEXP_EXTRACT(proto_payload.audit_log.resource_name, r'\\d{4}\\/\\d{2}\\/\\d{2}') <= FORMAT_DATE(\"%E4Y/%m/%d\", DATE_SUB(CURRENT_DATE(), INTERVAL ${offset} DAY)))"
    }
   ]
  }
 ]
}