{
 "title": "Exp: Scamper Detail",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "site", "query": "label_values(machine)" },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Successful Trace Latency ($site)",
   "type": "heatmap",
   "description": "Percent of successful traces that take x seconds.\n\nIndicates congestion if there are significant counts in bins > 1Gb/sec",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*avg(rate(trace_time_seconds_bucket{machine=~\".*.$site.*\", outcome=\"success\"}[10m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Failed Trace Latency ($site)",
   "type": "heatmap",
   "description": "Percent of traces that take x seconds.\n\nIndicates congestion if there are significant counts in bins > 1Gb/sec",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "100*avg(rate(trace_time_seconds_bucket{machine=~\".*.$site.*\", outcome!=\"success\"}[10m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TRC performed/outcome (Tests/Min) [$site]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Tests/Min" }
   ],
   "targets": [
    {
     "expr": "60* sum(rate(trace_time_seconds_count{machine=~\".*($site).*\"}[$interval])) by (outcome)",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "60* sum(rate(traces_performed_total{machine=~\".*($site).*\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average Trace Time {{outcome}}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trace_time_seconds_sum{machine=~\".*($site).*\"}[$interval]))by(outcome)/sum(rate(trace_time_seconds_count{machine=~\".*($site).*\"}[$interval]))by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Trace Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit", "label": "Tests/Min" }
   ],
   "targets": [
    {
     "expr": "topk(5, (sum by (machine)(rate(trace_time_seconds_count{machine=~\".*($site).*\", outcome!=\"success\"}[6h]))) / (sum by (machine)(rate(trace_time_seconds_count{machine=~\".*($site).*\"}[6h]))))\n"
    },
    {
     "expr": "avg((sum by (machine)(rate(trace_time_seconds_count{machine=~\".*($site).*\", outcome!=\"success\"}[$interval]))) / (sum by (machine)(rate(trace_time_seconds_count{machine=~\".*($site).*\"}[$interval]))))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Traces In Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Concurrent Tests/Machine" }
   ],
   "targets": [
    {
     "expr": "avg(traces_in_progress{machine=~\".*($site).*\"}) by (type)",
     "legendFormat": "Average {{type}}"
    },
    {
     "expr": "topk(3, avg_over_time(traces_in_progress{machine=~\".*($site).*\"}[6h])) by (type)",
     "legendFormat": "{{machine}}"
    }
   ]
  }
 ]
}