{
 "title": "GCP Billing Monthly (Google view)",
 "time": { "from": "2024-05-01T00:00:00.000Z", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "bqSource", "query": "grafana-bigquery-datasource" },
   {
    "name": "begin",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cumulative Credits Used since $begin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  SUM(cost) AS total,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE(\"$begin\") AND CURRENT_DATE()\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "Total cost per service (over $5k) since $begin",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  IF(sku.description LIKE \"%Transfer Out%\", \"Compute Egress\", service.description) AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  usage_start_time BETWEEN \"$begin\" AND \"${__to:date:YYYY-MM-DD}\" \nGROUP BY\n  metric\nHAVING value > 5000  "
    }
   ]
  },
  {
   "title": "Avg Daily Credits (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  SUM(cost)/30 AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 31 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "Avg Monthly Credits (last 180 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  SUM(cost)/6 AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 182 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "Projected Annual Credits (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  365*SUM(cost)/30 AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 31 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "All Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Monthly GCP Credits - Billing per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, MONTH) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  -- Always end query range at the end of the previous month.\n  usage_start_time BETWEEN \"$begin\" AND TIMESTAMP(DATE_SUB(DATE_TRUNC(DATE \"${__to:date:YYYY-MM-DD}\", MONTH), INTERVAL 1 DAY))\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL\nGROUP BY\n  date,\n  metric\nHAVING value > 1\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cumulative GCP Credits - Billing per Service",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT \n  date,\n  metric,\n  SUM(value) OVER(PARTITION BY metric ORDER BY date RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as Cost\nFROM (\n  SELECT\n    TIMESTAMP_TRUNC(usage_start_time, MONTH) AS date,\n    service.description AS metric,\n    SUM(cost) AS value,\n  FROM\n    `mlab-oti.billing.unified`\n  WHERE\n    usage_start_time BETWEEN \"$begin\" AND TIMESTAMP(DATE_SUB(DATE_TRUNC(DATE \"${__to:date:YYYY-MM-DD}\", MONTH), INTERVAL 1 DAY))\n  GROUP BY\n    date,\n    metric\n  HAVING value > 100\n  ORDER BY\n    date, value\n)\nORDER BY\n  date, Cost"
    }
   ]
  },
  {
   "title": "Monthly GCP Credits - Egress",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, MONTH) AS date,\n  SUM(cost) as Egress\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  usage_start_time BETWEEN \"$begin\" AND TIMESTAMP(DATE_SUB(DATE_TRUNC(DATE \"${__to:date:YYYY-MM-DD}\", MONTH), INTERVAL 1 DAY))\n  AND service.description = 'Compute Engine'\n  AND (sku.description LIKE 'Network Internet Egress%' OR sku.description LIKE 'Network Internet Data Transfer Out %')\n  AND cost > 0\nGROUP BY\n  date\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cumulative GCP Credits - Egress",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT \n  date,\n  SUM(Egress) OVER(ORDER BY date RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as CumulativeEgress\nFROM (\n  SELECT\n    TIMESTAMP_TRUNC(usage_start_time, MONTH) AS date,\n    SUM(cost) as Egress\n  FROM\n    `mlab-oti.billing.unified`\n  WHERE\n    usage_start_time BETWEEN \"$begin\" AND TIMESTAMP(DATE_SUB(DATE_TRUNC(DATE \"${__to:date:YYYY-MM-DD}\", MONTH), INTERVAL 1 DAY))\n    AND service.description = 'Compute Engine'\n    AND (sku.description LIKE 'Network Internet Egress%' OR sku.description LIKE 'Network Internet Data Transfer Out %')\n    AND cost > 0\n  GROUP BY\n    date\n  ORDER BY\n    date\n)\nORDER BY\n  date"
    }
   ]
  },
  {
   "title": "Cost per service (per day)",
   "type": "timeseries",
   "description": "Recent data may be delayed by 48 hours",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  usage_start_time BETWEEN \"${__from:date:YYYY-MM-DD}\" AND \"${__to:date:YYYY-MM-DD}\"\nGROUP BY\n  date,\n  metric\nHAVING value > 1\nORDER BY\n  date"
    }
   ]
  }
 ]
}