{
 "title": "GCP Billing Daily",
 "time": { "from": "now-8d", "to": "now-1d" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   { "name": "bqSource", "query": "grafana-bigquery-datasource" },
   { "name": "promSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* GCP Billing data is exported per billing account to tables in `mlab-staging.billing.*` and `mlab-oti.billing.*`\n* Partial data is exported hourly, but complete usage for a given hour may not be available until 2 days later\n* Because of the above, the default time range excludes the last 24h"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Avg Daily Credits (last 7 days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  SUM(cost)/7 AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "Projected Annual Credits (based on last 7 days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "2",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  365*SUM(cost)/7 AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  DATE(usage_start_time) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)\n  AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL"
    }
   ]
  },
  {
   "title": "All Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cost per project per day (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  project.id AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time) AND usage_start_time IS NOT NULL AND project.id IS NOT NULL AND cost IS NOT NULL\nGROUP BY\n  date,\n  metric\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cost per service per day (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time)\nGROUP BY\n  date,\n  metric\nHAVING value > 0.01\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cost per service (per hour)",
   "type": "timeseries",
   "description": "Recent data may be delayed by 48 hours",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, HOUR) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time)\nGROUP BY\n  date,\n  metric\nHAVING value > 1\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "GCE egress network cost per day (mlab-oti)",
   "type": "timeseries",
   "description": "octets_out_sum: the sum of the node-exporter metric \"node_network_transmit_bytes_total\" for every GCE virtual platform node, assuming a $0.10/GB cost. This number is likely to be higher than the actual cost, since some amount of octets out on every node will be to destinations within GCP, and billed at a much lower rate.\n\ngce_egress_sum: calculated using the exported GCP billing data in BigQuery where service.description = \"Compute Engine\" and sku.description LIKE \"Network Internet Egress%\". This number will definitely be _much_ higher than the actual cost of virtual platform node Internet egress, because it includes Internet egress costs for _all_ GCE instances, whether they are part of the platform or not. However, it should show us trends and give us a general idea of how much Internet egress is costing M-Lab.\n\nNetwork Internet Egress.*: specific network internet egress SKUs where the cost per day is greater than $10. These plots will give you an idea of the major contributors to the \"gce_egress_sum\" plot.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    (\n      (\n        increase(node_network_transmit_bytes_total{device=\"ens4\", node=~\"mlab[1-4].*\"}[1d])\n          and on(node) kube_node_labels{label_mlab_type=\"virtual\"}\n      ) / 2^30\n    ) * 0.10\n  )\n)",
     "legendFormat": "octets_out_sum"
    },
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  SUM(cost) as gce_egress_sum\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time)\n  AND service.description = 'Compute Engine'\n  AND (sku.description LIKE 'Network Internet Egress%' OR sku.description LIKE 'Network Internet Data Transfer Out %')\n  AND cost > 0\n  AND project.id = 'mlab-oti'\nGROUP BY\n  date\nORDER BY\n  date\n"
    },
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  sku.description as metric,\n  SUM(cost) as gce_egress\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time)\n  AND service.description = 'Compute Engine'\n  AND (sku.description LIKE 'Network Internet Egress%' OR sku.description LIKE 'Network Internet Data Transfer Out %')\n  AND cost > 10\n  AND project.id = 'mlab-oti'\nGROUP BY\n  date, metric\nORDER BY\n  date, gce_egress\n"
    }
   ]
  },
  {
   "title": "$project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "project",
   "targets": [
    {}
   ]
  },
  {
   "title": "Cost per day ($project)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  project.id AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time) AND project.id = \"$project\"\nGROUP BY\n  date,\n  metric\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cost per service (per day) ($project)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, DAY) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time) AND project.id = \"$project\"\nGROUP BY\n  date,\n  metric\nHAVING value > 0.01\nORDER BY\n  date\n"
    }
   ]
  },
  {
   "title": "Cost per service (per hour) ($project)",
   "type": "timeseries",
   "description": "Recent data may be delayed by 48 hours",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(usage_start_time, HOUR) AS date,\n  service.description AS metric,\n  SUM(cost) AS value,\nFROM\n  `mlab-oti.billing.unified`\nWHERE\n  $__timeFilter(usage_start_time) and project.id = \"$project\"\nGROUP BY\n  date,\n  metric\nHAVING value > .1\nORDER BY\n  date\n"
    }
   ]
  }
 ]
}