{
 "title": "k8s: Master Cluster",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "master", "label": "Master", "query": "label_values(node)" }
  ]
 },
 "panels": [
  { "title": "$master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "master" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{node=\"master-platform-cluster-$master\"}) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Sum of metrics over all CPU cores.",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"system\"}[5m]))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Written {{device}}"
    }
   ]
  },
  {
   "title": "Host network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node=\"k8s-platform-master-$master\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Active_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O % (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Flannel network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"} -\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  { "title": "$master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{node=\"master-platform-cluster-$master\"}) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Sum of metrics over all CPU cores.",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"system\"}[5m]))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Written {{device}}"
    }
   ]
  },
  {
   "title": "Host network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node=\"k8s-platform-master-$master\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Active_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O % (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Flannel network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"} -\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  { "title": "$master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{node=\"master-platform-cluster-$master\"}) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Sum of metrics over all CPU cores.",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"master-platform-cluster-$master\", mode=\"system\"}[5m]))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "Written {{device}}"
    }
   ]
  },
  {
   "title": "Host network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=~\"ens4.*\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{node=\"master-platform-cluster-$master\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node=\"k8s-platform-master-$master\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Active_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"master-platform-cluster-$master\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O % (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=\"master-platform-cluster-$master\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Flannel network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: Out"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=\"flannel.1\", node=\"master-platform-cluster-$master\"}[4m])",
     "legendFormat": "{{device}}: In"
    }
   ]
  },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"} -\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", node=\"master-platform-cluster-$master\"}"
    }
   ]
  }
 ]
}