{
 "title": "k8s: Site Overview Terse",
 "description": "A terse version of the Site Overview dashboard displaying averages over all machines, suitable for viewing multiple sites at once",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "type", "label": "Type", "query": "physical, virtual" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(kube_node_labels{label_mlab_type=~\"$type\"}, site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "site",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Average sec/sec usage across all CPUs available to all the machines at the selected site.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by (site) (rate(node_cpu_seconds_total{site=\"$site\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (site) (\n  node_memory_Cached_bytes{site=\"$site\"}\n  + node_memory_Buffers_bytes\n  + node_memory_SReclaimable_bytes\n)",
     "legendFormat": "Buff/Cache"
    },
    {
     "expr": "avg by (site) (\n  node_memory_Active_bytes{site=\"$site\"}\n  + node_memory_Active_anon_bytes\n  + node_memory_Active_file_bytes\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (site) (node_memory_MemFree_bytes{site=\"$site\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum by (site) (rate(node_network_transmit_bytes_total{device=~\"(eth0|ens4)\", site=\"$site\"}[4m]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- 8 * sum by (site) (rate(node_network_receive_bytes_total{device=~\"(eth0|ens4)\", site=\"$site\"}[4m]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (site, device) (rate(node_disk_read_bytes_total{site=\"$site\"}[5m]))",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "avg by (site, device) (rate(node_disk_written_bytes_total{site=\"$site\"}[5m]))",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "NDT test rate / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "(60 * sum(rate(ndt5_client_test_results_total{direction=\"s2c\", result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))\n+ (60 * sum(rate(ndt7_client_test_results_total{direction=\"download\", result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))",
     "legendFormat": "Download"
    },
    {
     "expr": "(60 * sum(rate(ndt5_client_test_results_total{direction=\"c2s\", result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))\n+ (60 * sum(rate(ndt7_client_test_results_total{direction=\"upload\", result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))",
     "legendFormat": "Upload"
    },
    {
     "expr": "(60 * sum(rate(ndt5_client_test_results_total{result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))\n+ (60 * sum(rate(ndt7_client_test_results_total{result!=\"error-without-rate\", site_type=~\"$type\", site=\"$site\"}[5m])) or vector(0))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}