{
 "title": "K8s: Workload Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate container CPU usage (% total cluster)",
   "type": "graph",
   "description": "Aggregate container CPU usage expressed as a percentage of the entire cluster CPU capacity.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_name:container_cpu_usage_seconds_total:sum_rate5m /\n  ignoring(container_label_io_kubernetes_container_name) group_left sum(machine_cpu_cores)\n",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "Aggregate container memory usage (% total cluster)",
   "type": "graph",
   "description": "Aggregate container memory expressed as a percentage of the entire cluster's memory capacity.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_name:container_memory_working_set_bytes:sum_rate5m /\n  ignoring(container_label_io_kubernetes_container_name) group_left sum(machine_memory_bytes)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "Aggregate container network usage (bits/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_workload) (\n  rate (\n    container_network_transmit_bytes_total{\n      container_label_io_kubernetes_container_name = \"POD\",\n      container_label_workload != \"\",\n      interface =~ \"(eth0|net1)\"\n    }\n  [5m]) * 8\n)",
     "legendFormat": "{{container_label_workload}} tranmitted"
    },
    {
     "expr": "sum by (container_label_workload) (\n  - rate (\n    container_network_receive_bytes_total{\n      container_label_io_kubernetes_container_name = \"POD\",\n      container_label_workload != \"\",\n      interface =~ \"(eth0|net1)\"\n    }\n  [5m]) * 8\n)",
     "legendFormat": "{{container_label_workload}} received"
    }
   ]
  },
  {
   "title": "Top 10: Container CPU usage by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  node_containername:container_cpu_usage_seconds_total:sum_rate5m / on(node) group_left machine_cpu_cores\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Top10: container memory usage by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  node_containername:container_memory_working_set_bytes:sum_rate5m/ on(node) group_left machine_memory_bytes\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Top 10: Container network usage by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum by (node, container_label_workload) (\n    rate (\n      container_network_transmit_bytes_total{\n        container_label_io_kubernetes_container_name = \"POD\",\n        container_label_workload != \"\"\n      }\n    [5m]) * 8\n  )\n)",
     "legendFormat": "{{container_label_workload}} tranmitted ({{node}})"
    },
    {
     "expr": "topk(10,\n  sum by (node, container_label_workload) (\n    - rate (\n      container_network_receive_bytes_total{\n        container_label_io_kubernetes_container_name = \"POD\",\n        container_label_workload != \"\"\n      }\n    [5m]) * 8\n  )\n)",
     "legendFormat": "{{container_label_workload}} received ({{node}})"
    }
   ]
  },
  {
   "title": "DaemonSets: Desired vs Curernt",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (daemonset) (kube_daemonset_status_current_number_scheduled)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum by (daemonset) (kube_daemonset_status_desired_number_scheduled)",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Deployments: Desired vs Curernt",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "sum by (exported_deployment) (kube_deployment_status_replicas)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum by (exported_deployment) (kube_deployment_spec_replicas)",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Total pods (all namespaces)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Pods not ready",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"true\"} == 0"
    }
   ]
  },
  {
   "title": "DaemonSets: desired != current",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled != kube_daemonset_status_desired_number_scheduled"
    }
   ]
  },
  {
   "title": "Container restarts (rate/s entire cluster)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total[5m])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Deployments: desired != current",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas != kube_deployment_status_replicas"
    }
   ]
  }
 ]
}