{
 "title": "K8s: Etcd Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Cluster Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Has leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "Leader changes",
   "type": "singlestat",
   "description": "Average leader changes over the past 5 minutes.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(etcd_server_leader_changes_seen_total[5m]))"
    }
   ]
  },
  {
   "title": "Wal fsync",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(etcd_disk_wal_fsync_duration_seconds_sum / etcd_disk_wal_fsync_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Backend commit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(etcd_disk_backend_commit_duration_seconds_sum / etcd_disk_backend_commit_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Proposals applied",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(etcd_server_proposals_applied_total[2m]))"
    }
   ]
  },
  {
   "title": "Proposals committed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(etcd_server_proposals_committed_total[2m]))"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(etcd_server_proposals_pending[2m]))"
    }
   ]
  },
  {
   "title": "Proposals failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(etcd_server_proposals_failed_total[2m]))"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "node" },
  {
   "title": "Wal fsync duration (s)",
   "type": "heatmap",
   "description": "A wal_fsync is called when etcd persists its log entries to disk before applying them.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_bucket[2m])"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total{instance=\"k8s-platform-master-$node\"}[4m])",
     "legendFormat": "Applied"
    },
    {
     "expr": "rate(etcd_server_proposals_committed_total{instance=\"k8s-platform-master-$node\"}[4m])",
     "legendFormat": "Committed"
    },
    {
     "expr": "rate(etcd_server_proposals_pending{instance=\"k8s-platform-master-$node\"}[4m])",
     "legendFormat": "Pending"
    },
    {
     "expr": "rate(etcd_server_proposals_failed_total{instance=\"k8s-platform-master-$node\"}[4m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Backend commit duration (s)",
   "type": "heatmap",
   "description": "A backend_commit is called when etcd commits an incremental snapshot of its most recent changes to disk.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_bucket[2m])"
    }
   ]
  },
  {
   "title": "Peer network (bits/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(etcd_network_peer_received_bytes_total{instance=\"k8s-platform-master-$node\"}[2m])",
     "legendFormat": "From: {{From}}"
    },
    {
     "expr": "- 8 * rate(etcd_network_peer_sent_bytes_total{instance=\"k8s-platform-master-$node\"}[2m])",
     "legendFormat": "To: {{To}}"
    }
   ]
  },
  {
   "title": "Peer RTT (s)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_round_trip_time_seconds_bucket[2m])"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "description": "Sum of all object counts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (etcd_object_counts)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "sum(etcd_object_counts)", "legendFormat": "Total" }
   ]
  }
 ]
}