{
 "title": "k8s: Node Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(container_start_time_seconds{container_label_io_kubernetes_pod_namespace=\"default\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Rootfs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", node=~\"$node.*\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", node=~\"$node.*\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", node=~\"$node.*\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=~\"$node.*\"} -\n    node_memory_MemFree_bytes{node=~\"$node.*\"}) / \nnode_memory_MemTotal_bytes{node=~\"$node.*\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", node=~\"$node.*\"}[4m])",
     "legendFormat": "TX eth0"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=\"eth0\", node=~\"$node.*\"}[4m])",
     "legendFormat": "RX eth0"
    }
   ]
  },
  {
   "title": "Disk I/O % sec/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=~\"$node.*\"}[5m])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node=~\"$node.*\"}[5m])",
     "legendFormat": "Written ({{device}})"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{node=~\"$node.*\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(\n  container_cpu_usage_seconds_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    container_label_io_kubernetes_pod_namespace=~\"default\",\n    node=~\"$node.*\"\n  }\n[5m])",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Pod RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    node=~\"$node.*\"\n}",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-8 * rate(\n  container_network_receive_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_pod_namespace=\"default\",\n    node=~\"$node.*\"\n  }\n[5m])",
     "legendFormat": "RX {{interface}} ({{container_label_io_kubernetes_pod_name}})"
    },
    {
     "expr": "8 * rate(\n  container_network_transmit_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_pod_namespace=\"default\",\n    node=~\"$node.*\"\n  }\n[5m])",
     "legendFormat": "TX {{interface}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  }
 ]
}