{
 "title": "k8s: Site Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "site", "label": "Site", "query": "label_values(node)" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(container_start_time_seconds{container_label_io_kubernetes_pod_namespace=\"default\"})"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{node=~\"$node.$site.*\"}) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"mlab[1-4].$site.*\"}",
     "legendFormat": "Load1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node=~\"$node.$site.*\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"$node.$site.*\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Active_bytes{node=~\"$node.$site.*\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$node.$site.*\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", node=~\"$node.$site.*\"}[4m])",
     "legendFormat": "TX eth0"
    },
    {
     "expr": "- 8 * rate(node_network_receive_bytes_total{device=\"eth0\", node=~\"$node.$site.*\"}[4m])",
     "legendFormat": "RX eth0"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=~\"$node.$site.*\"}[5m])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node=~\"$node.$site.*\"}[5m])",
     "legendFormat": "Written ({{device}})"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=~\"$node.$site.*\"}[5m])",
     "legendFormat": "% sec/sec ({{device}})"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{node=~\"$node.$site.*\"}"
    }
   ]
  },
  {
   "title": "Rootfs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", node=~\"$node.$site.*\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", node=~\"$node.$site.*\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", node=~\"$node.$site.*\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(\n  container_cpu_usage_seconds_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    container_label_io_kubernetes_pod_namespace=~\"default\",\n    node=~\"$node.$site.*\"\n  }\n[5m])",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    node=~\"$node.$site.*\"\n}",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-8 * rate(\n  container_network_receive_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_pod_namespace=\"default\",\n    interface=~\"(eth0|net2)\",\n    node=~\"$node.$site.*\"\n  }\n[5m])",
     "legendFormat": "RX {{interface}} ({{container_label_io_kubernetes_pod_name}})"
    },
    {
     "expr": "8 * rate(\n  container_network_transmit_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_pod_namespace=\"default\",\n    interface=~\"(eth0|net2)\",\n    node=~\"$node.$site.*\"\n  }\n[5m])",
     "legendFormat": "TX {{interface}} ({{container_label_io_kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Core temp",
   "type": "singlestat",
   "description": "Average temperature of all cores. Not sure how meaningful this is.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{node=~\"$node.$site.*\", chip=\"platform_coretemp_0\"})"
    }
   ]
  }
 ]
}