{
 "title": "K8S: TPCInfo",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "query": "label_values(tcpinfo_snapshot_total, deployment)"
   },
   { "name": "machine", "query": "mlab1,mlab2,mlab3,mlab4" },
   { "name": "site", "query": "label_values(machine)" },
   { "name": "TopK", "label": "Top K", "query": "1,2,3,5,10" }
  ]
 },
 "panels": [
  {
   "title": "NDT Tests/Hour",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 24, "w": 15, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "label_replace(sum by (machine) (3600*rate(ndt5_client_test_results_total{result=\"okay-with-rate\", machine=~\"mlab.*\"}[4h])), \"metro\", \"$1\", \"machine\", \".*mlab[1-4].([a-z]{3})[0-9tc]{2}.*\")",
     "legendFormat": "{{metro}}"
    }
   ]
  },
  {
   "title": "Machine status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count(lame_duck_experiment{workload=\"ndt\"})",
     "legendFormat": "Kubernetes"
    },
    {
     "expr": "count(lame_duck_node{service=\"nodeexporter\"})",
     "legendFormat": "Vserver"
    }
   ]
  },
  {
   "title": "Servers Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(lame_duck_experiment)" }
   ]
  },
  {
   "title": "NDT Test Rates (worldwide, per machine)",
   "type": "graph",
   "description": "Old platform processed up to 40 concurrent tests, which corresponds to about 240 tests per minute.  New platform can handle over 600 tests/min, but for now we set the warning level here at 240/min, and critical at 300/min.",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopK, sum by(machine)(60*rate(ndt5_client_test_results_total{machine=~\"$machine.$site.*\"}[10m]))+sum by(machine)(60*rate(ndt7_client_test_results_total{machine=~\"$machine.$site.*\"}[10m])))",
     "legendFormat": "Tests per minute - worst machines  {{machine}}"
    },
    {
     "expr": "sum(rate(ndt5_client_test_results_total{machine=~\"$machine.$site.*\", result!=\"okay-without-rate\"}[10m])) by (result)",
     "legendFormat": "Worldwide NDT5 tests/sec  {{result}}"
    },
    {
     "expr": "sum(rate(ndt7_client_test_results_total{machine=~\"$machine.$site.*\", result!=\"okay-without-rate\"}[10m])) by (result)",
     "legendFormat": "Worldwide NDT7 tests/sec  {{result}}"
    }
   ]
  },
  {
   "title": "TopK TCP Connections - v6 and v4",
   "type": "graph",
   "description": "Number of v4 and v6 connections on the hottest K machines.",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,avg(rate(tcpinfo_connection_count_histogram_sum{deployment=~\"$deployment\"}[5m])/rate(tcpinfo_connection_count_histogram_count{deployment=~\"$deployment\"} [5m])) by (machine, af)) by (af)",
     "legendFormat": "TopK avg connection count {{machine}}  {{af}}"
    }
   ]
  },
  {
   "title": "95th percentile polling intervals, top K machines",
   "type": "graph",
   "description": "The tcpinfo sampling interval is nominally 10 msec, and the max interval should never be greater than 20 msec.\nWhen machine load is high, the median interval should remain at 10 msec, but there will be more outliers, and the 95th percentile will increase.  Less than 15 msec is probably fine, but when the 95th percentile is above 16-18 msec, we may start to lose fidelity in the tcpinfo data.",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,histogram_quantile(0.95, sum(rate(tcpinfo_polling_interval_histogram_bucket{deployment=~\"$deployment\"}[10m])) by (le, machine, deployment)))",
     "legendFormat": "95th {{machine}} {{deployment}}"
    },
    {
     "expr": "bottomk($TopK,histogram_quantile(0.01, sum(rate(tcpinfo_polling_interval_histogram_bucket{deployment=~\"$deployment\"}[10m])) by (le, machine, deployment)))",
     "legendFormat": "1% {{machine}} {{deployment}}"
    },
    {
     "expr": "topk($TopK,histogram_quantile(0.75, sum(rate(tcpinfo_polling_interval_histogram_bucket{deployment=\"ndt\", deployment=~\"$deployment\"}[10m])) by (le, machine, deployment)))",
     "legendFormat": "75th {{machine}} {{deployment}}"
    }
   ]
  },
  {
   "title": "Second by second download rate ($deployment) ($site/$machine)",
   "type": "heatmap",
   "description": "Percent time spent at each bandwidth.\n\nIndicates congestion if there are significant counts in bins > 1Gb/sec",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100*avg(irate(tcpinfo_send_rate_histogram_bucket{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Second by second upload rates ($deployment) ($site/$machine)",
   "type": "heatmap",
   "description": "Percent of time spent at each bandwidth, across the fleet.",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "100*avg(irate(tcpinfo_receive_rate_histogram_bucket{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Send bandwidth ( $deployment - $site)",
   "type": "graph",
   "description": "Deployment throughput stats, by 5 minute average, and by hottest 1 second interval.\n\nEnable TOP view to see hottest machine (slow).",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(1.0, sum(irate(tcpinfo_send_rate_histogram_bucket{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by (le, deployment))) by (deployment)",
     "legendFormat": "{{deployment}} hottest second"
    },
    {
     "expr": "max(rate(tcpinfo_send_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} hottest machine (5 minute average)"
    },
    {
     "expr": "quantile(0.95, rate(tcpinfo_send_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} 95th % machine (5 minute average)"
    },
    {
     "expr": "quantile(0.5, rate(tcpinfo_send_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} 90th % machine (5 minute average)"
    }
   ]
  },
  {
   "title": "Receive bandwidth ($deployment - $site)",
   "type": "graph",
   "description": "Deployment throughput stats, by 5 minute average, and by hottest 1 second interval.\n\nEnable TOP view to see hottest machine (slow).",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(1.0, sum(irate(tcpinfo_receive_rate_histogram_bucket{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by (le, deployment))) by (deployment)",
     "legendFormat": "{{deployment}} hottest second"
    },
    {
     "expr": "max(rate(tcpinfo_receive_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} hottest machine (5 minute average)"
    },
    {
     "expr": "quantile(0.95, rate(tcpinfo_receive_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} 95th % machine (5 minute average)"
    },
    {
     "expr": "quantile(0.5, rate(tcpinfo_receive_rate_histogram_sum{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[5m])) by (deployment)",
     "legendFormat": "{{deployment}} 90th % machine (5 minute average)"
    }
   ]
  },
  {
   "title": "Worldwide outbound bandwidth  ($site)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcpinfo_send_rate_histogram_sum{machine=~\"$machine.$site.*\"}[2m])) by (le, deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Worldwide inbound bandwidth ($site)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcpinfo_receive_rate_histogram_sum{machine=~\"$machine.$site.*\"}[2m])) by (le, deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Send bandwidth ( $deployment - $site)",
   "type": "graph",
   "description": "Deployment throughput stats, by 5 minute average, and by hottest 1 second interval.\n\nEnable TOP view to see hottest machine (slow).",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "100000*sum(irate(tcpinfo_send_rate_histogram_count{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by (deployment)",
     "legendFormat": "{{deployment}} count"
    }
   ]
  },
  {
   "title": "Errors ( $deployment - $site)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tcpinfo_error_total{deployment=~\"$deployment\", machine=~\"$machine.$site.*\"}[2m])) by (deployment, type)",
     "legendFormat": "{{deployment}} error count {{type}}"
    }
   ]
  }
 ]
}