{
 "title": "K8s: Topk Machine & Pod Resources",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   { "name": "site", "query": "label_values(machine)" },
   { "name": "pod", "label": "Pod", "query": "label_values(label_workload)" },
   {
    "name": "container",
    "query": "label_values(go_memstats_heap_inuse_bytes{pod=~\".*$pod.*\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Bytes Written (5m) $node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, rate(node_disk_written_bytes_total{node=~\"($node).$site.*\", device=~\"sda\"}[5m]))",
     "legendFormat": "{{device}} - {{node}}"
    }
   ]
  },
  {
   "title": "Memory $node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, node_memory_MemTotal_bytes{node=~\"($node).$site.*\"} - node_memory_MemAvailable_bytes{node=~\"($node).$site.*\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connections (2m) $node -> $pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(tcpinfo_connection_count_histogram_sum{pod=~\"$pod-.*\", machine=~\"($node).$site.*\"}[2m])\n  / rate(tcpinfo_connection_count_histogram_count{pod=~\"$pod-.*\", machine=~\"($node).$site.*\"}[2m]))",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (5m) $node -> $pod",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_usage_seconds_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    container_label_io_kubernetes_pod_namespace=~\"default\",\n    machine=~\"($node).$site.*\"\n  }[5m]))",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} - {{machine}}"
    }
   ]
  },
  {
   "title": "Pod Memory $node -> $pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, container_memory_working_set_bytes{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    container_label_io_kubernetes_container_name!=\"POD\",\n    machine=~\"($node).$site.*\"\n})",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} - {{machine}}"
    }
   ]
  },
  {
   "title": "Pod Network (5m) $node -> $pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-topk(10, 8 * rate(\n  container_network_receive_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    interface=~\"(eth0|net1)\",\n    machine=~\"($node).$site.*\"\n  }\n[5m]))",
     "legendFormat": "{{interface}} - {{container_label_io_kubernetes_pod_name}} - {{machine}}"
    },
    {
     "expr": "topk(10, 8 * rate(\n  container_network_transmit_bytes_total{\n    container_label_io_kubernetes_pod_name=~\"$pod-.*\",\n    interface=~\"(eth0|net1)\",\n    machine=~\"($node).$site.*\"\n  }\n[5m]))",
     "legendFormat": "{{interface}} - {{container_label_io_kubernetes_pod_name}} - {{machine}}"
    }
   ]
  },
  {
   "title": "Go Heap Memory  $node -> $pod -> $container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, process_resident_memory_bytes{\n    container=~\".*$container\",\n    machine=~\"($node).$site.*\",\n    pod=~\".*$pod.*\",\n})",
     "legendFormat": "{{container}} - {{machine}}"
    }
   ]
  },
  {
   "title": "Go Routines $node -> $pod -> $container",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk (10, go_goroutines{machine=~\"($node).$site.*\", workload=~\"$pod\", container=~\".*$container\"})",
     "legendFormat": "{{container}} - {{machine}}"
    }
   ]
  }
 ]
}