{
 "title": "Keep the Platform Running",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Switch: Global Network Utilization (outbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Bits / Sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCOutOctets{ifAlias=\"uplink\"}[5m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "NDT: Global Test Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Tests / Min" }
   ],
   "targets": [
    {
     "expr": "(60 * sum(rate(ndt5_client_test_results_total{result!=\"error-without-rate\"}[5m])) or vector(0))\n+ (60 * sum(rate(ndt7_client_test_results_total{result!=\"error-without-rate\"}[5m])) or vector(0))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Pusher: Bytes Uploaded to GCS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes / Min" }
   ],
   "targets": [
    {
     "expr": "60*sum  (rate(pusher_bytes_per_tarfile_sum[5m]))",
     "legendFormat": "All datatypes"
    }
   ]
  },
  {
   "title": "ETL: Rows Written to BigQuery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Rows / Min" }
   ],
   "targets": [
    {
     "expr": "60*sum (rate(etl_test_count[10m]))",
     "legendFormat": "standard"
    },
    {
     "expr": "60 * sum  (rate(etl_test_count[10m]))",
     "legendFormat": "legacy"
    }
   ]
  }
 ]
}