{
 "title": "Keep M-Lab Running",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "dc_datasource", "query": "prometheus" },
   { "name": "fed_datasource", "query": "prometheus" },
   { "name": "bigquery", "query": "grafana-bigquery-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Current Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Switch: Global Network Utilization (outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(max by(site) (rate(ifHCOutOctets{ifAlias=\"uplink\"}[5m]))) < 160000000000 ",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "NDT: Global Test Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(60 * sum(rate(ndt5_client_test_results_total{result!=\"error-without-rate\"}[5m])) or vector(0))\n+ (60 * sum(rate(ndt7_client_test_results_total{result!=\"error-without-rate\"}[5m])) or vector(0))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Pusher: Bytes Uploaded to GCS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "60*sum  (rate(pusher_bytes_per_tarfile_sum[5m]))",
     "legendFormat": "All datatypes"
    }
   ]
  },
  {
   "title": "ETL: Rows Written to BigQuery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "60*sum (rate(etl_test_total[10m]))",
     "legendFormat": "standard"
    },
    {
     "expr": "60 * sum  (rate(etl_test_total[10m]))",
     "legendFormat": "legacy"
    }
   ]
  },
  {
   "title": "Switch: Uplink Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(max by (site) (irate(ifOutDiscards{ifAlias=\"uplink\"}[4m]) > 0))",
     "legendFormat": "{{site}} ({{interface}})"
    }
   ]
  },
  {
   "title": "NDT: Global Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(ndt5_client_test_results_total{result=\"error-without-rate\"}[5m]) or vector(0)) +\n sum(rate(ndt7_client_test_results_total{result=\"error-without-rate\"}[5m]) or vector(0))) /\n(sum(rate(ndt5_client_test_results_total[5m]) or vector(0)) +\n sum(rate(ndt7_client_test_results_total[5m]) or vector(0)))"
    }
   ]
  },
  {
   "title": "Pusher: Successful Archive Uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate (pusher_tarfiles_successful_uploads_total[5m]))"
    }
   ]
  },
  {
   "title": "ETL: Gardener Task Completions (Tasks / day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(deployment, datatype) (24*increase(gardener_completed_total{deployment=~\".*-universal\", datatype=~\".*\"}[1h]))",
     "legendFormat": "Completed {{datatype}}"
    }
   ]
  },
  {
   "title": "Historical Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Site Counts",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "project": "measurement-lab",
     "rawSql": "SELECT\n TIMESTAMP(DATE_TRUNC(date, MONTH)) as time, \n IF( (\"physical\" IN UNNEST(raw.Download.ServerMetadata.Value)),\n   \"physical\", \"virtual\") as metric,\n COUNT(DISTINCT server.Site) as sites\nFROM `measurement-lab.ndt.ndt7`\nWHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) AND CURRENT_DATE()\nAND raw.Download is not NULL\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "Server Country Counts",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 18 },
   "targets": [
    {
     "project": "measurement-lab",
     "rawSql": "SELECT TIMESTAMP(DATE_TRUNC(date, MONTH)) as time, COUNT(DISTINCT server.Geo.CountryCode) as countries\nFROM `measurement-lab.ndt.ndt7`\nWHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) AND CURRENT_DATE()\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "NDT Daily Tests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "project": "measurement-lab",
     "rawSql": "SELECT TIMESTAMP(date) as time,\n IF( (\"physical\" IN UNNEST(raw.Download.ServerMetadata.Value) OR \"physical\" IN UNNEST(raw.Upload.ServerMetadata.Value)),\n   \"physical\", \"virtual\") as metric,\n  COUNT(*) as tests\nFROM `measurement-lab.ndt.ndt7`\nWHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) AND CURRENT_DATE()\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  }
 ]
}