{
 "title": "Locate Service",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "platformdatasource", "label": "Platform Datasource", "query": "prometheus" },
   { "name": "bigquerydatasource", "label": "BigQuery Datasource", "query": "doitintl-bigquery-datasource" },
   {
    "name": "experiment",
    "label": "Experiment",
    "query": {
     "query": "label_values(locate_current_heartbeat_connections, experiment)"
    }
   },
   {
    "name": "metro",
    "label": "Metro",
    "query": "SELECT SUBSTR(server.Site, 0, 3) AS metro,\nFROM`ndt.ndt7`\nWHERE date >= \"2022-12-01\"\nGROUP BY metro"
   }
  ]
 },
 "panels": [
  { "title": "Rollout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Server Count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (\n    min by (experiment) (\n        locate_health_status{experiment=~\"$experiment.*\"}\n    )\n)",
     "legendFormat": "locate"
    },
    {
     "expr": "(vector(0) AND absent(probe_success{service=~\"$experiment.*\"}))\nOR\nsum (\n    min by (experiment, machine) (\n        label_replace(probe_success{service=~\"$experiment.*\"}, \"experiment\", \"$experiment\", \"experiment\", \"$experiment.*\") OR\n        label_replace(script_success{service=~\"$experiment.*\"}, \"experiment\", \"$experiment\", \"experiment\", \"$experiment.*\") OR\n        label_replace(((node_filesystem_size_bytes{cluster=\"platform\", mountpoint=\"/cache/data\"} -\n              node_filesystem_avail_bytes{cluster=\"platform\", mountpoint=\"/cache/data\"}) /\n                node_filesystem_size_bytes{cluster=\"platform\", mountpoint=\"/cache/data\"}),\n                \"experiment\", \"$experiment\", \"\", \"\") < bool 0.95 OR\n        label_replace(kube_node_spec_taint{cluster=\"platform\", key=\"lame-duck\"}, \"experiment\", \"$experiment\", \"\", \"\") != bool 1 OR\n        label_replace(lame_duck_experiment{cluster=\"platform\"}, \"experiment\", \"$experiment\", \"experiment\", \"$experiment.*\") != bool 1 OR\n        label_replace(gmx_machine_maintenance, \"experiment\", \"$experiment\", \"\", \"\") != bool 1\n    )\n)",
     "legendFormat": "mlab-ns"
    }
   ]
  },
  {
   "title": "Distance from Client to Server (NDT7)",
   "type": "barchart",
   "description": "Distribution of distances between client and server fot NDT7 tests. Y axis shows distance in kilometers and X axis shows percentiles.",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "orderByCol": "2",
     "orderBySort": "1",
     "partitionedField": "date",
     "rawSql": "WITH dist_locate AS (\n  SELECT st_distance(st_geogpoint(server.Geo.Longitude, server.Geo.Latitude), st_geogpoint(client.Geo.Longitude, client.Geo.Latitude)) / 1000 as dist_in_kms_locate\n  FROM `ndt.ndt7`, UNNEST(raw.Download.ClientMetadata) as metadata\n  WHERE $__timeFilter(date)\n    AND (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n      AND \"v2\" IN UNNEST(raw.Download.ClientMetadata.Value))\n    AND server.Geo.Longitude IS NOT NULL\n    AND server.Geo.Latitude IS NOT NULL\n    AND client.Geo.Longitude IS NOT NULL\n    AND client.Geo.Latitude IS NOT NULL\n),\n\ndist_others AS (\n  SELECT ST_DISTANCE(ST_GEOGPOINT(server.Geo.Longitude, server.Geo.Latitude), ST_GEOGPOINT(client.Geo.Longitude, client.Geo.Latitude)) / 1000 AS dist_in_kms_others\n  FROM `ndt.ndt7`\n  WHERE $__timeFilter(date)\n    AND ( (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n        AND \"v2_proxy\" IN UNNEST(raw.Download.ClientMetadata.Value))\n      OR (\"locate_version\" NOT IN UNNEST(raw.Download.ClientMetadata.Name)) )\n    AND server.Geo.Longitude IS NOT NULL\n    AND server.Geo.Latitude IS NOT NULL\n    AND client.Geo.Longitude IS NOT NULL\n    AND client.Geo.Latitude IS NOT NULL\n),\n\npercentiles_locate AS (\n  SELECT approx_quantiles(dist_in_kms_locate, 10) dist_in_kms_locate\n  FROM dist_locate\n),\n\npercentiles_others AS (\n  SELECT approx_quantiles(dist_in_kms_others, 10) dist_in_kms_others\n  FROM dist_others\n),\n\nunnest_percentiles_locate AS (\n  SELECT dist_in_kms_locate AS locate, (RANK() OVER (ORDER BY dist_in_kms_locate ASC) - 1) * 10 AS percentile \n  FROM percentiles_locate, UNNEST(dist_in_kms_locate) AS dist_in_kms_locate\n),\n\nunnest_percentiles_others AS (\n  SELECT dist_in_kms_others AS mlab_ns, (RANK() OVER (ORDER BY dist_in_kms_others ASC) - 1) * 10 AS percentile \n  FROM percentiles_others, UNNEST(dist_in_kms_others) AS dist_in_kms_others\n)\n\nSELECT locate, mlab_ns, unnest_percentiles_locate.percentile\nFROM unnest_percentiles_locate JOIN unnest_percentiles_others ON (unnest_percentiles_locate.percentile = unnest_percentiles_others.percentile)\nORDER BY percentile\n"
    }
   ]
  },
  {
   "title": "Distribution of Number of Tests per Site for Metro (NDT7)",
   "type": "barchart",
   "description": "Median, min, and max number of NDT7 tests per site for metro(s). Y axis shows the number of tests and X axis shows min, max, and median number of tests for sites within the selected metro(s).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "orderByCol": "2",
     "orderBySort": "1",
     "partitionedField": "date",
     "rawSql": "WITH agg_locate AS (\n  SELECT SUBSTR(server.Site, 0, 3) AS metro, server.Site AS site, COUNT(*) AS total_tests\n  FROM `ndt.ndt7`\n  WHERE $__timeFilter(date)\n    AND raw.Download is not NULL\n    AND (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n      AND \"v2\" IN UNNEST(raw.Download.ClientMetadata.Value))\n  GROUP BY metro,site\n),\n\nagg_other AS (\n  SELECT SUBSTR(server.Site, 0, 3) AS metro, server.Site AS site, COUNT(*) AS total_tests\n  FROM `ndt.ndt7`\n  WHERE $__timeFilter(date)\n    AND ( (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n        AND \"v2_proxy\" IN UNNEST(raw.Download.ClientMetadata.Value))\n      OR (\"locate_version\" NOT IN UNNEST(raw.Download.ClientMetadata.Name)) )\n  GROUP BY metro,site\n),\n\ndistribution_locate AS (\n  SELECT MIN(total_tests) AS min_locate, MAX(total_tests) AS max_locate, APPROX_QUANTILES(total_tests, 100)[OFFSET(50)] AS p50_locate, metro\n  FROM agg_locate\n  GROUP BY metro\n),\n\ndistribution_other AS (\n  SELECT MIN(total_tests) AS min_other, MAX(total_tests) AS max_other, APPROX_QUANTILES(total_tests, 100)[OFFSET(50)] AS p50_other, metro\n  FROM agg_other\n  GROUP BY metro\n)\n\nSELECT SUM(min_locate) AS min_locate, SUM(p50_locate) AS median_locate, SUM(max_locate) AS max_locate,\n  SUM(min_other) AS min_mlab_ns, SUM(p50_other) AS median_mlab_ns, SUM(max_other) AS max_mlab_ns,\n  \"Min, median, and max\" AS min_median_max\nFROM distribution_locate JOIN distribution_other ON (distribution_locate.metro = distribution_other.metro)\nWHERE REGEXP_CONTAINS(distribution_locate.metro, '${metro:regex}')\n\n"
    }
   ]
  },
  {
   "title": "Distribution of Number of Tests per Machine for Metro (NDT7)",
   "type": "barchart",
   "description": "Number of NDT7 tests per machine for the selected metro(s). Y axis shows the number of tests and X axis the machines.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "orderByCol": "2",
     "orderBySort": "1",
     "partitionedField": "date",
     "rawSql": "WITH agg_locate AS (\n  SELECT SUBSTR(server.Site, 0, 3) AS metro,\n    server.Site AS site,\n    COUNTIF(server.Machine LIKE '%mlab1%') AS mlab1_locate,\n    COUNTIF(server.Machine LIKE '%mlab2%') AS mlab2_locate,\n    COUNTIF(server.machine LIKE '%mlab3%') AS mlab3_locate,\n    COUNTIF(server.machine LIKE '%mlab4%') AS mlab4_locate,\n  FROM `ndt.ndt7`\n  WHERE $__timeFilter(date)\n    AND (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n      AND \"v2\" IN UNNEST(raw.Download.ClientMetadata.Value))\n  GROUP BY metro,site\n),\n\nagg_other AS (\n  SELECT SUBSTR(server.Site, 0, 3) AS metro,\n    server.Site AS site,\n    COUNTIF(server.Machine LIKE '%mlab1%') AS mlab1_mlab_ns,\n    COUNTIF(server.Machine LIKE '%mlab2%') AS mlab2_mlab_ns,\n    COUNTIF(server.machine LIKE '%mlab3%') AS mlab3_mlab_ns,\n    COUNTIF(server.machine LIKE '%mlab4%') AS mlab4_mlab_ns,\n    FROM `ndt.ndt7`\n  WHERE $__timeFilter(date)\n    AND raw.Download IS NOT NULL\n    AND ( (\"locate_version\" IN UNNEST(raw.Download.ClientMetadata.Name)\n        AND \"v2_proxy\" IN UNNEST(raw.Download.ClientMetadata.Value))\n      OR (\"locate_version\" NOT IN UNNEST(raw.Download.ClientMetadata.Name)) )\n  GROUP BY metro,site\n)\n\nSELECT SUM(mlab1_locate) AS mlab1_locate, SUM(mlab2_locate) as mlab2_locate, SUM(mlab3_locate) AS mlab3_locate, SUM(mlab4_locate) AS mlab4_locate, \n  SUM(mlab1_mlab_ns) AS mlab1_mlab_ns, SUM(mlab2_mlab_ns) AS mlab2_mlab_ns, SUM(mlab3_mlab_ns) AS mlab3_mlab_ns, SUM(mlab4_mlab_ns) AS mlab4_mlab_ns,\n  \"Machines\" AS machines\nFROM agg_locate JOIN agg_other ON (agg_locate.site = agg_other.site)\nWHERE REGEXP_CONTAINS(agg_locate.metro, '${metro:regex}')\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Health Signals from Locate Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Current Heartbeat Connections",
   "type": "gauge",
   "description": "Number of currently active Heartbeat connections.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(locate_current_heartbeat_connections{experiment=~\"$experiment\"})"
    }
   ]
  },
  {
   "title": "Heartbeat Connection Request Rate (per min)",
   "type": "timeseries",
   "description": "The 1 min rate of Heartbeat connection requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(locate_requests_total{type=\"heartbeat\"}[10m])/10)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Prometheus Health Collections (per min)",
   "type": "timeseries",
   "description": "One minute Increase in Prometheus health collections grouped by code.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (code) (increase(prometheus_health_collection_duration_count[10m])/10)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Prometheus Health Collection Request Time",
   "type": "heatmap",
   "description": "Prometheus health collection duration in seconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by(le) (increase(prometheus_health_collection_duration_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Health Signals from Heartbeat Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Port Checks (per min)",
   "type": "timeseries",
   "description": "One minute increase in number of port checks grouped by status.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(status)(increase(heartbeat_port_checks_total{workload=~\"$experiment.*\"}[10m])/10)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Health Checks (per min)",
   "type": "timeseries",
   "description": "One minute increase in number of health checks grouped by status.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(status)(increase(heartbeat_health_endpoint_checks_total{workload=~\"$experiment.*\"}[10m])/10)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes Requests (per min)",
   "type": "timeseries",
   "description": "One minute increase in requests to the Kubernetes API Server grouped by status.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (status) (increase(heartbeat_kubernetes_requests_total{workload=~\"$experiment.*\"}[10m])/10)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Request Time",
   "type": "heatmap",
   "description": "Kubernetes API server request duration in seconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by(le) (increase(heartbeat_kubernetes_request_time_histogram_bucket{workload=~\"$experiment.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Nearest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client Request Rate (per min)",
   "type": "timeseries",
   "description": "Number of client requests served by the Locate service.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(locate_requests_total{type=\"nearest\"}[10m])/10)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Client Request Failure Rate (per min)",
   "type": "timeseries",
   "description": "The rate at which client requests returned status != \"OK\".",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 * (sum by (status) (increase(locate_requests_total{type=\"nearest\", status!=\"OK\"}[10m])/10)\n/ ignoring (status) group_left \nsum(increase(locate_requests_total{type=\"nearest\"}[10m])/10))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "App Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "App Engine Country Success Rate (per min)",
   "type": "timeseries",
   "description": "The rate at which App Engine successfully returns the client's country (i.e., country != \"ZZ\"). ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "100 * (sum(rate(locate_app_engine_total{country!=\"ZZ\"}[10m])/10) / (sum(rate(locate_app_engine_total[10m])/10)))",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}