{
 "title": "MLAB-NS: Prometheus Queries",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "protocol", "label": "Protocol", "query": "IPv4 :  , IPv6 : _ipv6" }
  ]
 },
 "panels": [
  {
   "title": "ndt5 (wss) $protocol: % up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  min by (experiment, machine) (\n    probe_success{service=\"ndt_ssl$protocol\"} OR\n    script_success{service=\"ndt5_client\"} OR\n    label_replace(((node_filesystem_size_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"} -\n      node_filesystem_avail_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"}) /\n        node_filesystem_size_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"}),\n        \"experiment\", \"ndt.iupui\", \"\", \"\") < bool 0.95 OR\n    label_replace(kube_node_spec_taint{cluster=\"platform-cluster\", key=\"lame-duck\"},\n      \"experiment\", \"ndt.iupui\", \"\", \"\") != bool 1 OR\n    label_replace(gmx_machine_maintenance, \"experiment\", \"ndt.iupui\", \"\", \"\") != bool 1\n  )\n) /\ncount(\n  probe_success{service=\"ndt_ssl$protocol\"} unless on(machine)\n  (gmx_machine_maintenance == 1 unless on(machine) kube_node_status_condition)\n)"
    }
   ]
  },
  {
   "title": "ndt7 $protocol: % up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  min by (experiment, machine) (\n    probe_success{service=\"ndt7$protocol\"} OR\n    label_replace(((node_filesystem_size_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"} -\n      node_filesystem_avail_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"}) /\n        node_filesystem_size_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"}),\n        \"experiment\", \"ndt.iupui\", \"\", \"\") < bool 0.95 OR\n    label_replace(kube_node_spec_taint{cluster=\"platform-cluster\", key=\"lame-duck\"},\n      \"experiment\", \"ndt.iupui\", \"\", \"\") != bool 1 OR\n    label_replace(gmx_machine_maintenance, \"experiment\", \"ndt.iupui\", \"\", \"\") != bool 1\n  )\n) /\ncount(\n  probe_success{service=\"ndt7$protocol\"} unless on(machine)\n  (gmx_machine_maintenance == 1 unless on(machine) kube_node_status_condition)\n)"
    }
   ]
  },
  {
   "title": "Disk space used (sum)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (\n  node_filesystem_size_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"} -\n  node_filesystem_avail_bytes{cluster=\"platform-cluster\", mountpoint=\"/cache/data\"}\n)\n              "
    }
   ]
  },
  {
   "title": "ndt5 (wss) $protocol: probe_success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_success{service=\"ndt_ssl$protocol\"})"
    }
   ]
  },
  {
   "title": "ndt7 $protocol: probe_success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_success{service=\"ndt7$protocol\"})"
    }
   ]
  },
  {
   "title": "GMXed nodes (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gmx_machine_maintenance == 1)\n              "
    }
   ]
  },
  {
   "title": "ndt5 (wss) IPv4: e2e",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(script_success{service=\"ndt5_client\"})"
    }
   ]
  },
  {
   "title": "Lame-ducks (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_spec_taint{cluster=\"platform-cluster\", key=\"lame-duck\"})\n              ",
     "legendFormat": "nodes"
    },
    {
     "expr": "count(lame_duck_experiment{cluster=\"platform-cluster\"} == 1)",
     "legendFormat": "experiments"
    }
   ]
  }
 ]
}