{
 "title": "MLAB-NS: Reverse proxying",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests per experiment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gae_app_logging_googleapis_com_user_requests_counter",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Reverse proxied requests per experiment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gae_app_logging_googleapis_com_user_reverse_proxy_counter) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Reverse proxying rate per experiment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(stackdriver_gae_app_logging_googleapis_com_user_reverse_proxy_counter[10m])) by (resource) /\nsum(avg_over_time(stackdriver_gae_app_logging_googleapis_com_user_requests_counter[10m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}