{
 "title": "MSAK monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MSAK connections per hour",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 16, "x": 0, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "expr": "label_replace(sum by (machine) (rate(msak_throughput1_client_websocket_upgrades_total{machine=~\"mlab.*\"}[1h]) * 60 * 60), \"metro\", \"$1\", \"machine\", \".*mlab[1-4].([a-z]{3})[0-9tc]{2}.*\")",
     "legendFormat": "{{metro}}"
    }
   ]
  },
  {
   "title": "Running MSAK containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{exported_container=\"msak\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy MSAK servers (heartbeat)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(heartbeat_port_checks_total{workload=\"msak\", status=\"OK\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSAK streams per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(msak_throughput1_tests_total[1h])*60) by (direction)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket upgrades per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(msak_throughput1_client_websocket_upgrades_total[1h]) * 60) by (direction, status)",
     "legendFormat": "{{direction}} ({{status}})"
    }
   ]
  },
  {
   "title": "MSAK results VS created files",
   "type": "timeseries",
   "description": "Number of streams considered \"successful\" i.e. with status \"ok\" or \"ok-timeout\", together with number of files written. The two are expected to be the same at all times.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(msak_throughput1_tests_total[1h]))",
     "legendFormat": "streams"
    },
    {
     "expr": "sum(rate(msak_throughput1_file_writes_total{status=\"ok\"}[1h]))",
     "legendFormat": "files"
    },
    {
     "expr": "rate(msak_throughput1_file_writes_total{status!=\"ok\"}[1h])",
     "legendFormat": "write errors"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(msak_throughput1_client_websocket_upgrades_total{status!=\"ok\"}[1h]) * 60) by (status)",
     "legendFormat": "WS upgrade error {{status}}"
    },
    {
     "expr": "sum(rate(msak_throughput1_tests_total{status=~\"[^ok].*\"}[1h]) * 60)",
     "legendFormat": "Test errors"
    },
    {
     "expr": "sum(rate(msak_throughput1_congestion_control_errors_total[1h]) * 60)",
     "legendFormat": "setCC errors ({{cc}})"
    }
   ]
  },
  {
   "title": "MSAK server commit version count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "count by(commit) (git_short_commit{container=\"msak\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average and topk (5) goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(5, go_goroutines{container=\"msak\"})",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "avg(go_goroutines{container=\"msak\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "Jostler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Bundles upload rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(jostler_bytes_per_bundle_count{workload=\"msak\"}[$__rate_interval]))",
     "legendFormat": "Bundles"
    },
    {
     "expr": "rate(jostler_bytes_per_bundle_count{workload=\"msak\"}[$__rate_interval])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Bundle size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(jostler_bytes_per_bundle_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}