{
 "title": "NDT: Canary Validation",
 "description": "This dashboard allows to compare the production version of ndt-server with the current canary release(s).",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "mlab-sandbox,mlab-staging,mlab-oti"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT(table_catalog, \".\", table_schema, \".\", table_name) FROM `$project.statistics.INFORMATION_SCHEMA.TABLES` WHERE STARTS_WITH(table_name, 'ndt') OR STARTS_WITH(table_name, 'gfr')"
   },
   {
    "name": "metro",
    "query": "SELECT DISTINCT METRO FROM $table"
   },
   { "name": "interval", "query": "10m,30m,1h,6h,12h,1d,7d,14d" },
   {
    "name": "client",
    "query": "SELECT DISTINCT clientName FROM $table"
   },
   { "name": "nclients", "query": "5000" },
   {
    "name": "canary",
    "label": "Canary version",
    "query": "SELECT DISTINCT NDTVersion FROM $table"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Speed Variation",
   "type": "stat",
   "description": "Variation in the weighted average of download speeds worldwide, averaged over the selected time range to get a single value.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanSpeed,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanSpeed,\n  \n  FROM $table\n  WHERE complete AND NOT slow AND $__timeFilter(time_column) \n  GROUP BY test_date\n)\nSELECT time, (canaryLogMeanSpeed / prodLogMeanSpeed - 1) AS percentFaster FROM global\nORDER BY time DESC\n"
    }
   ]
  },
  {
   "title": "MinRTT variation",
   "type": "stat",
   "description": "Variation in the weighted average of logMeanMinRTT for all metros, averaged over the selected time range to get a single value.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = 'ndt',tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanMinRTT,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanMinRTT,\n  \n  FROM $table\n  WHERE complete AND NOT slow AND $__timeFilter(time_column) \n  GROUP BY test_date\n)\nSELECT time, (canaryLogMeanMinRTT / prodLogMeanMinRTT - 1) AS variation FROM global\nORDER BY time DESC\n"
    }
   ]
  },
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Global Geometric Mean Download Speed",
   "type": "timeseries",
   "description": "Weighted Geometric Mean of log_mean_speed for all metros",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanSpeed,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanSpeed,\n  \n  FROM $table\n  -- If we remove the complete requirement, the difference drops to about 1.5% to 2%\n  -- For the tests that are NOT COMPLETE, the canary is 13% SLOWER than prod.  This is MOSTLY due to tests that run longer than 13 seconds.\n  WHERE $__timeFilter(time_column) AND NOT slow --AND complete \n  AND (\"$canary\" = \"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY test_date\n)\nSELECT *, (canaryLogMeanSpeed / prodLogMeanSpeed - 1) AS percentFaster FROM global\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Global Geometric Mean MinRTT",
   "type": "timeseries",
   "description": "Weighted Geometric Mean of logMeanMinRTT for all metros",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanMinRTT,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanMinRTT,\n  \n  FROM $table\n  WHERE complete AND NOT slow AND $__timeFilter(time_column) \n  GROUP BY test_date\n)\nSELECT *, (canaryLogMeanMinRTT / prodLogMeanMinRTT - 1) AS percent FROM global\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Log Mean Machine Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(q90),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodQ90,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(q90),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryQ90,\n  \n  FROM $table\n  WHERE NOT slow \n  AND (\"$canary\"=\"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY test_date\n)\nSELECT *, (canaryQ90 / prodQ90 - 1) AS q90percentFaster FROM global\nORDER BY time DESC"
    },
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(q75),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodQ75,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(q75),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryQ75,\n  \n  FROM $table\n  WHERE NOT slow \n  AND (\"$canary\"=\"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY test_date\n)\nSELECT *, (canaryQ75 / prodQ75 - 1) AS q75percentFaster FROM global\nORDER BY time DESC"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'global' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(q25),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodQ25,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(q25),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryQ25,\n  \n  FROM $table\n  WHERE NOT slow \n  AND (\"$canary\"=\"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY test_date\n)\nSELECT *, (canaryQ25 / prodQ25 - 1) AS q25percentFaster FROM global\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Global Geometric Mean Download Speed by client ($client)",
   "type": "timeseries",
   "description": "Weighted Geometric Mean of log_mean_speed for all metros, by client",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH global as (\n  SELECT TIMESTAMP(test_date) as time,\n  'client' as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanSpeed,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanSpeed,\n  FROM $table\n  WHERE $__timeFilter(time_column) AND NOT slow and clientName = \"$client\" \n  AND (\"$canary\" = \"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY test_date, clientName HAVING SUM(clients) > 100 AND canaryLogMeanSpeed IS NOT NULL and prodLogMeanSpeed IS NOT NULL\n)\nSELECT *, (canaryLogMeanSpeed / prodLogMeanSpeed - 1) AS percentFaster FROM global\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Geometric Mean Download Speed Difference by site",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "WITH metro_summary AS (\n  SELECT TIMESTAMP(DATE_TRUNC(test_date, DAY)) as time,\n  site as metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanSpeed,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanSpeed,\n  SUM(clients) as nclients,\n  FROM $table\n  WHERE NOT slow \n  AND (\"$canary\"=\"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\n  GROUP BY time, metric HAVING canaryLogMeanSpeed IS NOT NULL\n)\n\nSELECT time, metric, (canaryLogMeanSpeed / prodLogMeanSpeed - 1) AS percentFaster FROM metro_summary WHERE nclients > $nclients\n\n"
    }
   ]
  },
  { "title": "Download Stats ($metro)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Geometric Mean Download Speed by metro ($metro)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "SELECT \n  TIMESTAMP(test_date) AS time,\n  metro AS metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanSpeed,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(log_Mean_Speed),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanSpeed,\nFROM $table\nWHERE NOT slow \nAND (\"$canary\"=\"ndt-canary\" OR site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\"))\nAND  $__timeFilter(time_column) AND metro IN ($metro)\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "Geometric Mean Download Q90 by metro ($metro)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "SELECT \n  TIMESTAMP(test_date) AS time,\n  metro AS metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(Q90),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodQ90,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(Q90),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryQ90,\nFROM $table\nWHERE complete AND NOT slow AND  $__timeFilter(time_column) AND metro IN ($metro) AND site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\")\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "Geometric Mean MinRTT by metro ($metro)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "SELECT \n  TIMESTAMP(test_date) AS time,\n  metro AS metric,\n  EXP(SUM(IF(NDTVersion = \"ndt\",tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"ndt\", tests, 0))) AS prodLogMeanMinRTT,\n  EXP(SUM(IF(NDTVersion = \"$canary\",tests*SAFE.LN(logMeanMinRTT),NULL))/SUM(IF(NDTVersion = \"$canary\", tests, 0))) AS canaryLogMeanMinRTT,\nFROM $table\nWHERE complete AND NOT slow AND  $__timeFilter(time_column) AND metro IN ($metro) AND site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\")\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "Geometric Mean Download Speed by metro ($metro)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "SELECT \n  TIMESTAMP(test_date) AS time,\n  CONCAT(metro, \"-canary\") AS metric,\n  EXP(SUM(tests*SAFE.LN(log_Mean_Speed))/SUM(tests)) AS value,\nFROM $table\nWHERE complete AND NOT slow AND  $__timeFilter(time_column) AND metro IN ($metro) AND site IN (\"sin01\",\"lga05\",\"fln01\",\"bom01\",\"hkg01\",\"mil04\")\nAND NDTVersion = \"$canary\"\nGROUP BY time, metric\nORDER BY time"
    },
    {
     "dataset": "statistics",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-sandbox",
     "rawSql": "SELECT \n  TIMESTAMP(test_date) AS time,\n  CONCAT(metro, \"-prod\") AS metric,\n  EXP(SUM(tests*SAFE.LN(log_Mean_Speed))/SUM(tests)) AS value,\nFROM $table\nWHERE complete AND NOT slow AND  $__timeFilter(time_column) AND metro IN ($metro)\nAND NDTVersion = \"ndt\"\nGROUP BY time, metric\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "ndt7 error rate (errors/min) by machine ($metro)",
   "type": "timeseries",
   "description": "NOTE: This should be normalized by number of tests, instead of the raw errors per minute.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "60 * avg(\n     label_replace(\n     rate(ndt7_client_sender_errors_total{deployment=\"ndt\", machine=~\".*$metro.*\"}[$interval]),\n      \"site\",\n      \"$1\",\n      \"machine\",\n      \"mlab[1-4]-([a-zA-Z]{3}\\\\d{2}).+\"\n    )\n) by (site, deployment)",
     "legendFormat": "{{deployment}} {{site}}"
    },
    {
     "expr": "60 * avg(\n     label_replace(\n     rate(ndt7_client_sender_errors_total{deployment=\"$canary\", machine=~\".*$metro.*\"}[$interval]),\n      \"site\",\n      \"$1\",\n      \"machine\",\n      \"mlab[1-4]-([a-zA-Z]{3}\\\\d{2}).+\"\n    )\n) by (site, deployment)",
     "legendFormat": "{{deployment}} {{site}}"
    }
   ]
  }
 ]
}