{
 "title": "NDT: Client Rates, Quantiles over time, & Heatmaps",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "site", "query": { "query": "label_values(machine)" } },
   {
    "name": "protocol",
    "query": "ndt5+ws,ndt5+wss,ndt5+plain,ndt7+ws,ndt7+wss"
   },
   { "name": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "$protocol per-metro (global)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Tests / Min" }
   ],
   "targets": [
    {
     "expr": "(60 * sum by(metro) (\n    label_replace(rate(ndt_test_rate_mbps_count{protocol=~\"$protocol\", monitoring=\"false\"}[$interval]),\n       \"metro\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}).*\"))\n)",
     "legendFormat": "{{metro}}"
    }
   ]
  },
  {
   "title": "NDT Testing Rate (tests/min)  ($site)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Tests/Min" }
   ],
   "targets": [
    {
     "expr": "60* sum(rate(ndt_test_rate_mbps_count{monitoring=\"false\", machine=~\".*($site).*\"}[$interval])) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "$protocol - Download Bandwidth Quartiles (Mbps) ($site)",
   "type": "graph",
   "description": "NB:  The diurnal drop is likely because we have bandwidth limited internal monitoring in WS, that dominates when there is less organic traffic.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (.95, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile (0.75, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile (0.25, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "25th"
    }
   ]
  },
  {
   "title": "Week-over-week Median $protocol - Download Bandwidth (Mbps) ($site)",
   "type": "graph",
   "description": "Overlay of the past 3 weeks of median download performance, Mb/sec.\nNB: The diurnal drop is likely because we have bandwidth limited internal monitoring in WS, that dominates when there is less organic traffic.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "now"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval] offset 7d)) by (le, protocol))",
     "legendFormat": "last week"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=~\"$protocol\"}[$interval] offset 14d)) by (le, protocol))",
     "legendFormat": "two weeks"
    }
   ]
  },
  {
   "title": "Aggregate Download Rate Heatmap ($site)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(ndt_test_rate_mbps_bucket{protocol=~\"$protocol\", direction=~\"download|s2c\", monitoring=\"false\", machine=~\".*$site.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Download Rate Histogram ($site)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(le) (increase(ndt_test_rate_mbps_bucket{protocol=~\"$protocol\", direction=~\"download|s2c\",  monitoring=\"false\", machine=~\".*$site.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upload Rate Histogram ($site)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(le) (increase(ndt_test_rate_mbps_bucket{protocol=~\"$protocol\", direction=~\"c2s|upload\", monitoring=\"false\", machine=~\".*$site.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Aggregate Upload Rate Heatmap ($site)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by(le) (increase(ndt_test_rate_mbps_bucket{protocol=~\"$protocol\", direction=~\"c2s|upload\",  monitoring=\"false\",machine=~\".*$site.*\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}