{
 "title": "NDT: Median Rates",
 "time": { "from": "now-8d", "to": "now" },
 "templating": {
  "list": [
   { "name": "machine", "label": "Machine", "query": "mlab1,mlab2,mlab3,mlab4" },
   {
    "name": "sites",
    "label": "Sites",
    "query": ".*,bru01|fra01|lax01|lga03|lhr05|mia02|nuq05|ord04|sea06|wlg02"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Tests" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_tests{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Upload median",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_upload_median_rate{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "median - {{machine}}"
    }
   ]
  },
  {
   "title": "Upload Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_upload_avg_rate{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "avg - {{machine}}"
    }
   ]
  },
  {
   "title": "Upload Median RTT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_upload_median_rtt{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "RTT - {{machine}}"
    }
   ]
  },
  {
   "title": "Download median",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_download_median_rate{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "median - {{machine}}"
    }
   ]
  },
  {
   "title": "Download Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_download_avg_rate{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "avg - {{machine}}"
    }
   ]
  },
  {
   "title": "Download Median RTT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bq_ndt_server_download_median_rtt{machine=~\"$machine.($sites).*\"}",
     "legendFormat": "RTT - {{machine}}"
    }
   ]
  }
 ]
}