{
 "title": "NDT: Access Control",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "machine", "query": ".*par04.*" },
   { "name": "range", "query": "2m,5m,10m,15m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "Columns are arranged in the same order they are handled by the ndt-server: tx, token, ndt server.\n\nIf a connection is rejected (or errors) at one stage, the remaining stages never see it."
  },
  {
   "title": "Global TX Rejection Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_access_txcontroller_requests_total{deployment=\"ndt\", request=\"rejected\"}[15m])) / \n  sum(increase(controller_access_txcontroller_requests_total{deployment=\"ndt\"}[15m]))",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Global Token Rejection Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (reason, path) ((rate(controller_access_token_requests_total{deployment=\"ndt\",request=\"rejected\"}[10m]))) / ignoring(reason, path) group_left() sum ((rate(controller_access_token_requests_total{deployment=\"ndt\",}[10m])))",
     "legendFormat": "{{reason}} {{path}}"
    }
   ]
  },
  {
   "title": "Global NDT Test Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(ndt5_client_test_results_total{result=\"error-without-rate\"}[10m]) or vector(0)) +\n sum(rate(ndt7_client_test_results_total{result=\"error-without-rate\"}[10m]) or vector(0))) /\n(sum(rate(ndt5_client_test_results_total[10m]) or vector(0)) +\n sum(rate(ndt7_client_test_results_total[10m]) or vector(0)))"
    }
   ]
  },
  { "title": "TX Controller", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 11 }, "content": "\n\n\n\n" },
  { "title": "Token Controller", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 11 }, "content": "\n\n\n\n" },
  { "title": "NDT Server", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 11 }, "content": "\n\n\n\n" },
  {
   "title": "Percent of Rejected Requests / Site ($range avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(site) (label_replace(rate(controller_access_txcontroller_requests_total{request=\"rejected\", machine=~\"$machine\"}[$range]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z0-9]{5}).*\")) / \n  sum by(site) (label_replace(rate(controller_access_txcontroller_requests_total{machine=~\"$machine\"}[$range]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z0-9]{5}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Percent of Rejected Requests / Site ($range avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(site) (label_replace(rate(controller_access_token_requests_total{deployment=\"ndt\", request=\"rejected\", path=~\".*ndt.*\", machine=~\"$machine\"}[$range]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z0-9]{5}).*\")) / \n  sum by(site) (label_replace(rate(controller_access_token_requests_total{deployment=\"ndt\", path=~\".*ndt.*\",  machine=~\"$machine\"}[$range]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z0-9]{5}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Percent NDT Test Errors / Site ($range avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(site) (label_replace(                                                    \n  (                                                                             \n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[$range])) +\n     sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[$range]))) /\n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\"}[$range])) +\n     sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\"}[$range])))\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[5m]))) /\n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\"}[$range])))\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[$range]))) /\n    (sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\"}[$range])))\n  )                                                                             \n , \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9t]{2}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "TX Requests / Minute / Site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*sum by(site) (label_replace(rate(controller_access_txcontroller_requests_total{machine=~\"$machine\"}[2m]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9t]{2}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Token Requests / Minute / Site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*sum by(site) (label_replace(rate(controller_access_token_requests_total{machine=~\"$machine\", path=~\".*ndt.*\"}[2m]), \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9t]{2}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "NDT Test Count / Site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "NDT Tests / Min" }
   ],
   "targets": [
    {
     "expr": "sum by(site) (label_replace(                                                    \n  (                                                                             \n    (machine:ndt5_client_test_results:rpm2m{machine=~\"$machine\"} + machine:ndt7_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (machine:ndt5_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (machine:ndt7_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \n , \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9t]{2}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "TX Requests / Minute / Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*sum by(machine) (rate(controller_access_txcontroller_requests_total{machine=~\"$machine\"}[2m]))",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Token Requests / Minute / machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*sum by(machine) (rate(controller_access_token_requests_total{deployment=\"ndt\", machine=~\"$machine\", path=~\".*ndt.*\"}[2m]))",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "NDT Test Count / Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "NDT Tests / Min" }
   ],
   "targets": [
    {
     "expr": "                                                  \n  (                                                                             \n    (machine:ndt5_client_test_results:rpm2m{machine=~\"$machine\"} + machine:ndt7_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (machine:ndt5_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (machine:ndt7_client_test_results:rpm2m{machine=~\"$machine\"})\n  )                                                                             \n",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Rejected Requests / Minute / Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60 *sum by(machine) (rate(controller_access_txcontroller_requests_total{request=\"rejected\", machine=~\"$machine\"}[2m]))",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Rejected Requests / Minute / Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*sum by(machine, reason) (rate(controller_access_token_requests_total{deployment=\"ndt\", machine=~\"$machine\", request=\"rejected\", path=~\".*ndt.*\"}[2m]))",
     "legendFormat": "{{machine}} {{reason}}"
    }
   ]
  },
  {
   "title": "NDT Test Errors / Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60 * ((                                                                             \n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[2m])) +\n     sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[2m])))\n  )                                                                             \nOR                                                                              \n  (                                                                             \n    (sum by(machine) (rate(ndt5_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[2m])))\n  )\nOR                                                                              \n  (                                                                             \n    (sum by(machine) (rate(ndt7_client_test_results_total{machine=~\"$machine\", result=\"error-without-rate\"}[2m])))\n  ))",
     "legendFormat": "{{machine}}"
    }
   ]
  }
 ]
}