{
 "title": "NDT: Download Speeds",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "site", "query": "label_values(machine)" },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   },
   {
    "name": "protocol",
    "query": "ndt5+ws,ndt5+wss,ndt5+plain,ndt7+ws,ndt7+wss"
   }
  ]
 },
 "panels": [
  {
   "title": "Median Download Bandwidth (Mbps) by protocol [$site]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\"}[$interval])) by (le, protocol))",
     "legendFormat": " {{protocol}}"
    }
   ]
  },
  {
   "title": "$protocol - Download Bandwidth Quartiles (Mbps) [$site]",
   "type": "graph",
   "description": "NB:  The diurnal drop is likely because we have bandwidth limited internal monitoring in WS, that dominates when there is less organic traffic.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (.95, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile (0.75, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile (0.25, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "25th"
    }
   ]
  },
  {
   "title": "Rate of Downloads (Tests/Min) [$site]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Tests/Min" }
   ],
   "targets": [
    {
     "expr": "60* sum(rate(ndt_test_rate_mbps_count{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\"}[$interval])) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Week-over-week Median $protocol - Download Bandwidth (Mbps) [$site]",
   "type": "graph",
   "description": "Overlay of the past 3 weeks of median download performance, Mb/sec.\nNB: The diurnal drop is likely because we have bandwidth limited internal monitoring in WS, that dominates when there is less organic traffic.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, protocol))",
     "legendFormat": "now"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval] offset 7d)) by (le, protocol))",
     "legendFormat": "last week"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval] offset 14d)) by (le, protocol))",
     "legendFormat": "two weeks"
    }
   ]
  }
 ]
}