{
 "title": "NDT: Metro Performance Distributions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "doitintl-bigquery-datasource" },
   {
    "name": "metro",
    "query": {
     "query": "label_values(ndt_test_rate_mbps_count{site_type=~\"$type\"}, machine)"
    }
   },
   { "name": "type", "query": "physical,virtual" },
   { "name": "mode", "query": "pdf,cdf" }
  ]
 },
 "panels": [
  { "title": "${metro}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "metro" },
  {
   "title": "Download Mbps ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "-- $__timeFilter(date) --date BETWEEN \"2023-03-04\" AND \"2023-03-04\"\nSELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\n\nFROM `ops.ndt7_download_pdf`(0.1, 3500, \"MeanThroughputMbps\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}\")"
    }
   ]
  },
  {
   "title": "Download MinRTT ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "-- $__timeFilter(date) --date BETWEEN \"2023-03-04\" AND \"2023-03-04\"\nSELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\n\nFROM `ops.ndt7_download_pdf`(0.1, 300, \"MinRTT\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}\")"
    }
   ]
  },
  {
   "title": "Download LossRate ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "-- $__timeFilter(date) --date BETWEEN \"2023-03-04\" AND \"2023-03-04\"\nSELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\n\nFROM `ops.ndt7_download_pdf`(1e-6, 1, \"LossRate\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${metro:regex}\")"
    }
   ]
  },
  {
   "title": "Test Counts (hourly, downloads only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT TIMESTAMP_TRUNC(a.TestTime, HOUR) as date, server.Site as metric, COUNT(*) as total\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n   $__timeFilter(date)\n AND REGEXP_CONTAINS(server.Site, \"${metro:regex}\")\nGROUP by date, metric\nORDER BY date, metric"
    }
   ]
  }
 ]
}