{
 "title": "NDT: Site Performance Distributions",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-bigquery-datasource" },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(ndt_test_rate_mbps_count{site_type=~\"$type\"}, machine)"
    }
   },
   { "name": "type", "query": "physical,virtual" },
   { "name": "mode", "query": "pdf,cdf" },
   { "name": "maskUpload", "label": "Hide Upload Spike", "query": "off,on" }
  ]
 },
 "panels": [
  {
   "title": "Download Mbps ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_download_pdf`(0.1, 3500, \"MeanThroughputMbps\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${site:regex}\")"
    }
   ]
  },
  {
   "title": "Download MinRTT ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\n\nFROM `ops.ndt7_download_pdf`(0.1, 300, \"MinRTT\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${site:regex}\")"
    }
   ]
  },
  {
   "title": "Download LossRate ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\n\nFROM `ops.ndt7_download_pdf`(1e-6, 1, \"LossRate\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${site:regex}\")"
    }
   ]
  },
  {
   "title": "Upload Mbps ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_upload_pdf`(0.1, 3500, \"MeanThroughputMbps\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${site:regex}\", \"${maskUpload}\" = \"on\")"
    }
   ]
  },
  {
   "title": "Upload MinRTT ($mode)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT\n  xright,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN site_pdf\n    ELSE site_cdf\n  END AS data,\n  site,\nFROM `ops.ndt7_upload_pdf`(0.1, 500, \"MinRTT\", \"${__from:date:YYYY-MM-DD}\", \"${__to:date:YYYY-MM-DD}\", \"${site:regex}\", \"${maskUpload}\" = \"on\")"
    }
   ]
  },
  {
   "title": "Test Counts (hourly, download only)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "SELECT TIMESTAMP_TRUNC(a.TestTime, HOUR) as date, server.Site as metric, COUNT(*) as total\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n   $__timeFilter(TIMESTAMP(date))\n AND REGEXP_CONTAINS(server.Site, \"${site:regex}\")\nGROUP by date, server.Site\nORDER BY date, server.Site  "
    }
   ]
  }
 ]
}