{
 "title": "NDT: Canary Release Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "query": "label_values(ndt_test_rate_mbps_bucket{deployment=\"ndt-canary\"}, machine)"
   },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   },
   {
    "name": "protocol",
    "query": "ndt5+ws,ndt5+wss,ndt5+plain,ndt7+ws,ndt7+wss"
   }
  ]
 },
 "panels": [
  {
   "title": "Median Download Throughput (Mbps) by machine [$site, $protocol]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, machine))",
     "legendFormat": "{{machine}} {{protocol}}"
    }
   ]
  },
  {
   "title": "$protocol - Download Bandwidth Quartiles (Mbps) [$site, $protocol]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (.95, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, workload, protocol))",
     "legendFormat": "{{machine}} 95th -- {{workload}}"
    },
    {
     "expr": "histogram_quantile (0.75, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, workload,protocol))",
     "legendFormat": "{{machine}} 75th -- {{workload}}"
    },
    {
     "expr": "histogram_quantile (0.5, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, workload,protocol))",
     "legendFormat": "{{machine}} 50th -- {{workload}}"
    },
    {
     "expr": "histogram_quantile (0.25, sum(increase(ndt_test_rate_mbps_bucket{direction=~\"s2c|download\", monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (le, workload,protocol))",
     "legendFormat": "{{machine}} 25th -- {{workload}}"
    }
   ]
  },
  {
   "title": "ndt7 error rate (errors/min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "errors/min" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(ndt7_client_sender_errors_total{deployment=~\"ndt.*\", machine=~\".*($site).*\"}[$interval])) by (machine)",
     "legendFormat": "Sender errors - {{machine}}"
    },
    {
     "expr": "60 * sum(rate(ndt7_client_receiver_errors_total{deployment=~\"ndt.*\", machine=~\".*($site).*\"}[$interval])) by (machine)",
     "legendFormat": "Receiver errors - {{machine}}"
    }
   ]
  },
  {
   "title": "Rate of Downloads (Tests/Min) [$site, $protocol]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Tests/Min" }
   ],
   "targets": [
    {
     "expr": "60* sum(rate(ndt_test_rate_mbps_count{direction=~\"s2c|download\",  monitoring=\"false\", machine=~\".*($site).*\", protocol=\"$protocol\"}[$interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "NDT DaemonSet CPU usage by node",
   "type": "graph",
   "description": "Left Y: Aggregate DaemonSet CPU usage expressed as a percentage of a node's total CPU cores.\n\nRight Y: Aggregate DaemonSet CPU usage as an absolute number of cores on a node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit", "label": "% Total Cores" }
   ],
   "targets": [
    {
     "expr": "machine_daemonset:container_cpu_usage_seconds:ratio{daemonset=~\"ndt.*\", machine=~\".*($site).*\"}",
     "legendFormat": "% Total: {{daemonset}} ({{machine}})"
    },
    {
     "expr": "machine_daemonset:container_cpu_usage_seconds:sum_rate1h{daemonset=~\"ndt.*\", machine=~\".*($site).*\"}",
     "legendFormat": "Cores: {{daemonset}} ({{machine}})"
    }
   ]
  }
 ]
}