{
 "title": "Ops: Rebot Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Rebooted in the last 24h",
   "type": "table",
   "description": "Nodes which have been rebooted by Rebot during the last 24 hours.\n\nTODO: use $__range after we upgrade to Grafana >v5.3",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(rebot_last_reboot_timestamp{} > time() - 86400) * 1000",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Currently offline nodes",
   "type": "table",
   "description": "Currently offline nodes. This panel runs Rebot's nodes query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum_over_time(probe_success{service=\"ssh806\", module=\"ssh_v4_online\"}[15m]) == 0 ,\n      \"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9tc]{2}).*\")\n  UNLESS ON(site) gmx_site_maintenance == 1\n  UNLESS ON(machine) gmx_machine_maintenance == 1\n  UNLESS ON(machine) lame_duck_node == 1\n  UNLESS ON(machine) sum_over_time(probe_success{service=\"ssh\", module=\"ssh_v4_online\"}[15m]) > 0\n\tUNLESS ON(machine) count_over_time(probe_success{service=\"ssh806\", module=\"ssh_v4_online\"}[15m]) < 14\n\tUNLESS ON(machine) rate(inotify_extension_create_total{ext=\".s2c_snaplog\"}[15m]) > 0",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Currently offline sites",
   "type": "table",
   "description": "Currently offline sites. This panel runs Rebot's offline sites query.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(probe_success{instance=~\"s1.*\", module=\"icmp\"}[15m]) == 0\n  UNLESS ON(site) gmx_site_maintenance == 1",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Offline node count",
   "type": "graph",
   "description": "Number of offline nodes as seen by Rebot, after applying the offline sites filtering.\n\nThis is NOT the same as the candidates list as it also includes nodes for which a reboot has been attempted in the last 24h.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rebot_machines_offline", "legendFormat": "Offline nodes" }
   ]
  },
  {
   "title": "Lame-ducked nodes",
   "type": "table",
   "description": "Nodes that have been placed in lame-duck status.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "lame_duck_node == 1", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Nodes GMX maintenance",
   "type": "table",
   "description": "Nodes that are in GMX maintenance. These nodes will not be considered as reboot candidates.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "gmx_machine_maintenance == 1", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Sites GMX maintenance",
   "type": "table",
   "description": "Sites that are in GMX maintenance. Nodes in these sites will not be considered as reboot candidates.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "gmx_site_maintenance == 1", "legendFormat": "{{site}}" }
   ]
  }
 ]
}