{
 "title": "Ops: Tactical & SRE Overview",
 "description": "This dashboard displays metrics that are useful to be reviewed as part of the Ops Tactical meetings and SRE rotation.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Alerts (active + suppressed)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# of alerts" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(alertmanager_alerts_received_total{status=\"firing\"}[5m])) by (job)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(alertmanager_alerts{kubernetes_name=\"alertmanager-tls-service\",state=\"suppressed\"}) by (kubernetes_name)",
     "legendFormat": "Suppressed"
    }
   ]
  },
  {
   "title": "Pod container restarts (increase 1d)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container:kube_pod_container_status_restarts:increase1d",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Kernel logs priority <=3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (log, priority) (stackdriver_generic_node_logging_googleapis_com_user_platform_cluster_kernel_logs{priority=~\"[0-3]\"})",
     "legendFormat": "{{log}}"
    }
   ]
  },
  {
   "title": "Excessive 6h/90th Percentile of Switch Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% Utilized" }
   ],
   "targets": [
    {
     "expr": "candidate_site:uplink:90th_quantile_6h{ifAlias=\"uplink\", speed=\"1g\"} / 1e9 > (40 / 100)",
     "legendFormat": "1g switch > 40% - {{site}}"
    },
    {
     "expr": "candidate_site:uplink:90th_quantile_6h{ifAlias=\"uplink\", speed=\"10g\"} / (9.4 * 1e9) > (50 / 100)",
     "legendFormat": "10g switch > 50% - {{site}}"
    }
   ]
  },
  {
   "title": "Rebooted nodes",
   "type": "table-old",
   "description": "Nodes which have been rebooted by Rebot.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(rebot_last_reboot_timestamp{} > time() - 86400) * 1000",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Sites GMX maintenance",
   "type": "table-old",
   "description": "Sites that are in GMX maintenance.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "gmx_site_maintenance == 1", "legendFormat": "{{site}}" }
   ]
  },
  {
   "title": "Nodes GMX maintenance (outside sites in GMX)",
   "type": "table-old",
   "description": "Nodes that are in GMX maintenance and not part of a site under maintenance.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(gmx_machine_maintenance == 1, \"site\", \"$1\", \"machine\", \"mlab[1-4]-([a-z]{3}[0-9ct]{2}).+\") unless on(site) gmx_site_maintenance == 1",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Lame-ducked nodes",
   "type": "table-old",
   "description": "Nodes that are currently in lame-duck mode.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "lame_duck_node == 1 OR kube_node_spec_taint{key=\"lame-duck\"} == 1",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (alertname, status) (increase(githubreceiver_alerts_total[$__range])) > 0"
    }
   ]
  },
  {
   "title": "Cluster versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (kubelet_version) (kube_node_info and on(node) kube_node_labels{label_mlab_type=\"physical\"})",
     "legendFormat": "k8s - physical: {{kubelet_version}}"
    },
    {
     "expr": "count by (kubelet_version) (kube_node_info and on(node) kube_node_labels{label_mlab_type=\"virtual\"})",
     "legendFormat": "k8s - virtual: {{kubelet_version}}"
    },
    {
     "expr": "count by (kernel_version) (kube_node_info and on(node) kube_node_labels{label_mlab_type=\"physical\"})",
     "legendFormat": "kernel - physical: {{kernel_version}}"
    },
    {
     "expr": "count by (kernel_version) (kube_node_info and on(node) kube_node_labels{label_mlab_type=\"virtual\"})",
     "legendFormat": "kernel - virtual: {{kernel_version}}"
    }
   ]
  },
  {
   "title": "Rolling updates triggered by Reloader (increase 1d)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(reloader_reload_executed_total{success=\"true\"}[1d])",
     "legendFormat": "Successes"
    },
    {
     "expr": "increase(reloader_reload_executed_total{success=\"false\"}[1d])",
     "legendFormat": "Failures"
    }
   ]
  }
 ]
}