{
 "title": "Ops: Reboot API monitoring",
 "time": { "from": "2019-08-08T06:12:51.525Z", "to": "2019-08-08T19:18:13.940Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "/v1/e2e - BMC E2E tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed E2E tests count",
   "type": "graph",
   "description": "Count of failed E2E tests over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(reboot_e2e_result == 0)", "legendFormat": "Failed E2E tests" }
   ]
  },
  {
   "title": "Currently failing E2E tests",
   "type": "table",
   "description": "This panel lists the E2E tests that are currently failing and their status.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "reboot_e2e_result == 0" }
   ]
  },
  { "title": "/v1/reboot - Reboots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Reboots",
   "type": "graph",
   "description": "BMC reboots over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reboot_bmc_total[2m]) * 120) by (deployment)",
     "legendFormat": "Reboot rate (2m)"
    }
   ]
  },
  {
   "title": "Reboot times",
   "type": "heatmap",
   "description": "BMC response times for reboot operations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(reboot_bmc_duration_seconds_bucket[1h])) by (le) * 3600",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{deployment=\"reboot-api\"}) by (deployment)",
     "legendFormat": "alloc_bytes"
    }
   ]
  }
 ]
}