{
 "title": "Ops: Pod Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "pod", "label": "Pod", "query": "label_values(hostname)" },
   { "name": "node", "label": "Node", "query": "mlab1,mlab2,mlab3,mlab4" }
  ]
 },
 "panels": [
  {
   "title": "Switch ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{module=\"icmp\", instance=\"s1.$pod.measurement-lab.org\"}"
    }
   ]
  },
  {
   "title": "Switch SNMP scraping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"snmp-targets\", site=\"$pod\"}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "node" },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"} -\n    node_filesystem_free{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"})\n/ node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "NDT disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vdlimit_used{experiment=\"ndt.iupui\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Total procs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_process_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Packet sockets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_packet_socket_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=\"ssh806\", machine=~\"$node.$pod.*\", module=\"ssh_v4_online\"}, \"service_name\", \"ssh806\", \"service\", \".*\")\n  OR label_replace(collectd_mlab_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"collectd_mlab\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_node_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_node\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_readonly_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_readonly\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_swap_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_swap\", \"service\", \".*\")",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "NDT status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"} OR script_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Neubot status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{service=~\"neubot.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mobiperf status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=~\"mobiperf.*\", machine=~\"$node.*$pod.*\"}, \"tcp_port\", \"$1\", \"instance\", \".*:(.*)\")",
     "legendFormat": "{{service}} ({{tcp_port}})"
    }
   ]
  },
  {
   "title": "Rsync status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{service=\"rsyncd\", machine=~\"$node.$pod.*\"}",
     "legendFormat": "{{experiment}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"} -\n    node_filesystem_free{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"})\n/ node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "NDT disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 14 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vdlimit_used{experiment=\"ndt.iupui\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Total procs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_process_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Packet sockets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_packet_socket_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=\"ssh806\", machine=~\"$node.$pod.*\", module=\"ssh_v4_online\"}, \"service_name\", \"ssh806\", \"service\", \".*\")\n  OR label_replace(collectd_mlab_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"collectd_mlab\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_node_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_node\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_readonly_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_readonly\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_swap_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_swap\", \"service\", \".*\")",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "NDT status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"} OR script_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Neubot status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{service=~\"neubot.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mobiperf status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=~\"mobiperf.*\", machine=~\"$node.*$pod.*\"}, \"tcp_port\", \"$1\", \"instance\", \".*:(.*)\")",
     "legendFormat": "{{service}} ({{tcp_port}})"
    }
   ]
  },
  {
   "title": "Rsync status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{service=\"rsyncd\", machine=~\"$node.$pod.*\"}",
     "legendFormat": "{{experiment}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"} -\n    node_filesystem_free{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"})\n/ node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "NDT disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 24 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vdlimit_used{experiment=\"ndt.iupui\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Total procs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_process_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Packet sockets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_packet_socket_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=\"ssh806\", machine=~\"$node.$pod.*\", module=\"ssh_v4_online\"}, \"service_name\", \"ssh806\", \"service\", \".*\")\n  OR label_replace(collectd_mlab_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"collectd_mlab\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_node_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_node\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_readonly_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_readonly\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_swap_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_swap\", \"service\", \".*\")",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "NDT status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": "probe_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"} OR script_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Neubot status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "probe_success{service=~\"neubot.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mobiperf status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=~\"mobiperf.*\", machine=~\"$node.*$pod.*\"}, \"tcp_port\", \"$1\", \"instance\", \".*:(.*)\")",
     "legendFormat": "{{service}} ({{tcp_port}})"
    }
   ]
  },
  {
   "title": "Rsync status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "probe_success{service=\"rsyncd\", machine=~\"$node.$pod.*\"}",
     "legendFormat": "{{experiment}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 34 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"} -\n    node_filesystem_free{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"})\n/ node_filesystem_size{device=\"/dev/mapper/planetlab-root\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "NDT disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 34 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vdlimit_used{experiment=\"ndt.iupui\", machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Total procs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_process_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Packet sockets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mlab_host_packet_socket_count{machine=~\"$node.$pod.*\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=\"ssh806\", machine=~\"$node.$pod.*\", module=\"ssh_v4_online\"}, \"service_name\", \"ssh806\", \"service\", \".*\")\n  OR label_replace(collectd_mlab_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"collectd_mlab\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_node_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_node\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_readonly_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_readonly\", \"service\", \".*\")\n  OR label_replace(mlab_host_check_swap_success{machine=~\"$node.$pod.*\"}, \"service_name\", \"check_swap\", \"service\", \".*\")",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "NDT status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "probe_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"} OR script_success{service=~\"ndt.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Neubot status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "probe_success{service=~\"neubot.*\", machine=~\"$node.*$pod.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mobiperf status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(probe_success{service=~\"mobiperf.*\", machine=~\"$node.*$pod.*\"}, \"tcp_port\", \"$1\", \"instance\", \".*:(.*)\")",
     "legendFormat": "{{service}} ({{tcp_port}})"
    }
   ]
  },
  {
   "title": "Rsync status",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "probe_success{service=\"rsyncd\", machine=~\"$node.$pod.*\"}",
     "legendFormat": "{{experiment}}"
    }
   ]
  }
 ]
}