{
 "title": "Ops: OA&M Overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "vm",
    "label": "VM",
    "query": "dns,eb,mirror,blackbox-exporter-ipv6"
   }
  ]
 },
 "panels": [
  { "title": "$vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vm" },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_memory_MemFree_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}) / \nnode_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Network bits/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} In"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} Out"
    }
   ]
  },
  { "title": "$vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_memory_MemFree_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}) / \nnode_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Network bits/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} In"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} Out"
    }
   ]
  },
  { "title": "$vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_memory_MemFree_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}) / \nnode_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Network bits/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} In"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} Out"
    }
   ]
  },
  { "title": "$vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Root fs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_filesystem_free_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"})\n/ node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\", instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"} -\n    node_memory_MemFree_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}) / \nnode_memory_MemTotal_bytes{instance=~\"^$vm.+measurementlab.net:9100\"}"
    }
   ]
  },
  {
   "title": "Network bits/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} In"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{device=\"eth0\", instance=~\"^$vm.+measurementlab.net:9100\"}[4m])",
     "legendFormat": "{{device}} Out"
    }
   ]
  }
 ]
}