{
 "title": "Ops: Platform Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "site", "label": "Site", "query": "label_values(site)" }
  ]
 },
 "panels": [
  {
   "title": "Switches down",
   "type": "table",
   "description": "Returns a switch when 100% of the probes have failed during the last 15 minutes. It excludes site which have been put into GMX maintenance mode.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(probe_success{instance=~\"s1.*\", module=\"icmp\"}[15m]) == 0 unless on(site) gmx_site_maintenance == 1",
     "legendFormat": "<font color=\"red\">s1.{{site}}</font>"
    }
   ]
  },
  {
   "title": "% NDT up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\n  probe_success{service=\"ndt_ssl\"} AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1 AND ON(machine)\n    probe_success{service=\"ndt_ssl\"} == 1 AND ON(machine)\n    probe_success{service=\"ndt_raw\"} == 1 AND ON(machine)\n    script_success{service=\"ndt5_client\"} == 1 AND ON(machine)\n    vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} < 0.95\n)\n/\ncount(\n  probe_success{service=\"ndt_ssl\"} AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1\n)"
    }
   ]
  },
  {
   "title": "NDT up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\n  probe_success{service=\"ndt_ssl\"} AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1 AND ON(machine)\n    probe_success{service=\"ndt_ssl\"} == 1 AND ON(machine)\n    probe_success{service=\"ndt_raw\"} == 1 AND ON(machine)\n    script_success{service=\"ndt5_client\"} == 1 AND ON(machine)\n    vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} < 0.95\n)"
    }
   ]
  },
  {
   "title": "NDT down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(\n  probe_success{service=\"ndt_ssl\"} AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1\n  UNLESS ON(machine) (\n    probe_success{service=\"ndt_ssl\"} == 1 AND ON(machine)\n    probe_success{service=\"ndt_raw\"} == 1 AND ON(machine)\n    script_success{service=\"ndt5_client\"} == 1 AND ON(machine)\n    vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} < 0.95\n  )\n))"
    }
   ]
  },
  {
   "title": "NDT queueing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(\n  script_success{service=\"ndt_queue\"} == 0 AND ON(machine)\n    script_exit_code{} == 5\n))"
    }
   ]
  },
  {
   "title": "Nodes down",
   "type": "table",
   "description": "Returns a node where 100% of probes have failed during the last 15 minutes. It excludes nodes which have been put into GMX maintenance mode.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(label_replace(sum_over_time(probe_success{service=\"ssh806\", module=\"ssh_v4_online\"}[15m]) == 0,\n\t\"site\", \"$1\", \"machine\", \"mlab[1-4].([a-z]{3}[0-9tc]{2}).*\")) unless on(machine) gmx_machine_maintenance == 1 unless on(site) gmx_site_maintenance == 1",
     "legendFormat": "<font color=\"red\">{{machine}}</font>"
    }
   ]
  },
  {
   "title": "Lame ducks",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "targets": [
    { "expr": "lame_duck_node{} == 1", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Nodes in GMX maintenance mode",
   "type": "table",
   "description": "Returns a machine which has been put into GMX maintenance mode.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "targets": [
    { "expr": "gmx_machine_maintenance{} == 1", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Sites in GMX maintenance mode",
   "type": "table",
   "description": "Returns a site which has been put into GMX maintenance mode.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "targets": [
    { "expr": "gmx_site_maintenance{} == 1", "legendFormat": "{{site}}" }
   ]
  },
  {
   "title": "Rebot - Rebooted in the last 24h",
   "type": "table",
   "description": "Returns a node which has been rebooted by Rebot during the last 24 hours.\n\nTODO: use $__range after we upgrade to Grafana >v5.3",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "(rebot_last_reboot_timestamp{} > time() - 86400) * 1000",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "NDT global test rate (up + down)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(inotify_extension_create_total{ext=\".s2c_snaplog\"}[5m])) + 60 * sum(rate(inotify_extension_create_total{ext=\".c2s_snaplog\"}[5m]))"
    }
   ]
  },
  {
   "title": "NDT down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(count(\n  probe_success{service=\"ndt_ssl\"} AND ON(machine)\n      up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n      lame_duck_node{} == 1\n    UNLESS ON(machine) (\n      probe_success{service=\"ndt_ssl\"} == 1 AND ON(machine)\n      probe_success{service=\"ndt_raw\"} == 1 AND ON(machine)\n      script_success{service=\"ndt5_client\"} == 1 AND ON(machine)\n      vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} < 0.8\n    )\n))",
     "legendFormat": "Down count"
    },
    {
     "expr": "probe_success{service=\"ndt_ssl\"} AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1\n  UNLESS ON(machine) (\n    probe_success{service=\"ndt_ssl\"} == 1 AND ON(machine)\n    probe_success{service=\"ndt_raw\"} == 1 AND ON(machine)\n    script_success{service=\"ndt5_client\"} == 1 AND ON(machine)\n    vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} < 0.8\n  )",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "scalar(count(\n  probe_success{service=\"ndt_ssl\"} == 0 AND ON(machine)\n      up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n      lame_duck_node{} == 1\n))",
     "legendFormat": "Down ndt_ssl"
    },
    {
     "expr": "scalar(count(\n  probe_success{service=\"ndt_raw\"} == 0 AND ON(machine)\n      up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n      lame_duck_node{} == 1\n))",
     "legendFormat": "Down ndt_raw"
    },
    {
     "expr": "scalar(count(\n  script_success{service=\"ndt5_client\"} == 0 AND ON(machine)\n      up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n      lame_duck_node{} == 1\n))",
     "legendFormat": "Down ndt5_client"
    },
    {
     "expr": "scalar(count(\n  vdlimit_used{experiment=\"ndt.iupui\"} / vdlimit_total{experiment=\"ndt.iupui\"} > 0.8 AND ON(machine)\n    up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n    lame_duck_node{} == 1\n))",
     "legendFormat": "Down disk full"
    }
   ]
  },
  {
   "title": "NDT queueing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(count(\n  script_success{service=\"ndt_queue\"} == 0 AND ON(machine)\n    script_exit_code{} == 5 AND ON(machine)\n    up{service=\"nodeexporter\"} == 1\n))",
     "legendFormat": "Queueing count"
    },
    {
     "expr": "script_success{service=\"ndt_queue\"} == 0 AND ON(machine)\n  script_exit_code{} == 5 AND ON(machine)\n  up{service=\"nodeexporter\"} == 1",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "$site: NDT status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "probe_success{service=\"ndt_ssl\", machine=~\".*$site.*\"} AND ON(machine)\n  up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n  lame_duck_node{} == 1",
     "legendFormat": "{{machine}} ({{service}})"
    },
    {
     "expr": "probe_success{service=\"ndt_raw\", machine=~\".*$site.*\"} AND ON(machine)\n  up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n  lame_duck_node{} == 1",
     "legendFormat": "{{machine}} ({{service}})"
    },
    {
     "expr": "script_success{service=\"ndt5_client\", machine=~\".*$site.*\"} AND ON(machine)\n  up{service=\"nodeexporter\"} == 1 UNLESS ON(machine)\n  lame_duck_node{} == 1",
     "legendFormat": "{{machine}} ({{service}})"
    }
   ]
  },
  {
   "title": "Disk Usage rootfs: Top 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, (node_filesystem_size{device=\"/dev/mapper/planetlab-root\"} - node_filesystem_free{device=\"/dev/mapper/planetlab-root\"}) / node_filesystem_size{device=\"/dev/mapper/planetlab-root\"})",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Disk Usage NDT: Top 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, vdlimit_used{experiment=\"ndt.iupui\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$site: NDT Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "vdlimit_used{machine=~\".*$site.*\"}",
     "legendFormat": "{{experiment}} {{machine}}"
    }
   ]
  },
  {
   "title": "% of time spent doing Disk IO (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_ms{device=\"dm-2\", machine!~\".*mlab4.*\"}[10m]) / 1000)",
     "legendFormat": "Max"
    },
    {
     "expr": "quantile(0.99, rate(node_disk_io_time_ms{device=\"dm-2\", machine!~\".*mlab4.*\"}[10m]) / 1000)",
     "legendFormat": "99th %"
    },
    {
     "expr": "quantile(0.90, rate(node_disk_io_time_ms{device=\"dm-2\", machine!~\".*mlab4.*\"}[10m]) / 1000)",
     "legendFormat": "90th %"
    },
    {
     "expr": "quantile(0.50, rate(node_disk_io_time_ms{device=\"dm-2\", machine!~\".*mlab4.*\"}[10m]) / 1000)",
     "legendFormat": "50th %"
    }
   ]
  },
  {
   "title": "Top 2 (% of time spent doing Disk IO (sec/sec))",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(node_disk_io_time_ms{device=\"dm-2\", machine!~\".*mlab4.*\"}[2m]) / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$site:  % of time spent doing Disk IO (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms{instance=~\".*$site.*\", device=\"dm-2\"}[2m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load15 Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load15{machine!=\".*mlab4.*\", service=\"nodeexporter\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "quantile(0.99, node_load15{machine!=\".*mlab4.*\", service=\"nodeexporter\"})",
     "legendFormat": "99th %"
    },
    {
     "expr": "quantile(0.90, node_load15{machine!=\".*mlab4.*\", service=\"nodeexporter\"})",
     "legendFormat": "90th %"
    },
    {
     "expr": "quantile(0.50, node_load15{machine!=\".*mlab4.*\", service=\"nodeexporter\"})",
     "legendFormat": "50th %"
    }
   ]
  },
  {
   "title": "Top 2: Load15 Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, node_load15{machine!=\".*mlab4.*\", service=\"nodeexporter\"})",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "$site: Load15 Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load15{instance=~\".*$site.*\", service=\"nodeexporter\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Switch Uplink Percentiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max(8 * rate(ifHCOutOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "Max Out"
    },
    {
     "expr": "quantile(0.99, 8 * rate(ifHCOutOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "99% Out"
    },
    {
     "expr": "quantile(0.90, 8 * rate(ifHCOutOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "90% Out"
    },
    {
     "expr": "- max(8 * rate(ifHCInOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "Max In"
    },
    {
     "expr": "- quantile(0.99, 8 * rate(ifHCInOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "99% In"
    },
    {
     "expr": "- quantile(0.90, 8 * rate(ifHCInOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "90% In"
    }
   ]
  },
  {
   "title": "Switch Uplink: Top 5",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, 8 * rate(ifHCOutOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "{{site}}"
    },
    {
     "expr": "bottomk(5, -8 * rate(ifHCInOctets{ifAlias=\"uplink\"}[2m]))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "$site: Switch Uplink",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(ifHCOutOctets{site=~\"$site.*\", ifAlias=\"uplink\"}[2m])",
     "legendFormat": "{{site}} Out"
    },
    {
     "expr": "- 8 * rate(ifHCInOctets{site=~\"$site.*\", ifAlias=\"uplink\"}[2m])",
     "legendFormat": "{{site}} In"
    }
   ]
  }
 ]
}