{
 "title": "Pipeline Overview Reorg",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "mlab-oti,mlab-staging,mlab-sandbox"
   },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   },
   { "name": "PrometheusDS", "query": "prometheus" },
   { "name": "LegacyDS", "query": "prometheus" },
   { "name": "Gardener2_DS", "label": "Gardener 2.0 Datasource", "query": "prometheus" },
   {
    "name": "states",
    "label": "Gardener States",
    "query": "label_values(gardener_state_date, state)"
   },
   {
    "name": "states2",
    "label": "Gardener 2.0 States",
    "query": "label_values(gardener_state_date, state)"
   }
  ]
 },
 "panels": [
  { "title": "Good/Bad Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Oldest Bigquery Parse Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "Days" }
   ],
   "targets": [
    {
     "expr": "bq_gardener_parse_time_age_days",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "Gardener 2.0 Bigquery Costs",
   "type": "graph",
   "description": "We may want to monitor this from the Gardener instance, and suspend operation if the cost exceeds some threshold.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s", "label": "Slot Time per Query" }
   ],
   "targets": [
    {
     "expr": "sum  by(version, datatype, query)(rate(query_cost_seconds_sum{}[1h])/rate(query_cost_seconds_count{}[1h]))",
     "legendFormat": "Slot Time per Query {{datatype}} {{query}}"
    },
    {
     "expr": "sum by(version, datatype, query)(increase(query_cost_seconds_sum{}[24h]))",
     "legendFormat": "Cumulative per Day {{datatype}} {{query}}"
    }
   ]
  },
  {
   "title": "Weekly query slot-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(version, query)(increase(query_cost_seconds_sum{}[24h]))",
     "legendFormat": "Recent {{version}} {{query}}"
    },
    {
     "expr": "sum by(version, query)(increase(query_cost_seconds_sum{}[24h]  offset 28d))",
     "legendFormat": "4 weeks ago {{version}} {{query}}"
    },
    {
     "expr": "sum by(query)(increase(query_cost_seconds_sum{}[24h]  offset 56d))",
     "legendFormat": "8 weeks ago {{query}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gardeners (one per datatype) ",
   "type": "graph",
   "description": "Uptimes for V2 Gardener and Parsers.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg by(run, pod_template_hash)(time()-process_start_time_seconds{container=~\"etl-gardener\"})",
     "legendFormat": "{{run}} {{pod_template_hash}}"
    },
    {
     "expr": "sum by(container, value)(etl_commit_hash{})",
     "legendFormat": "Git Hash {{container}} = {{value}}"
    }
   ]
  },
  {
   "title": "Parsers / Annotators",
   "type": "graph",
   "description": "Average Parser Version Uptime",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg by(version, service)(time()-process_start_time_seconds{version!=\"\"})",
     "legendFormat": "Avg {{service}} {{version}}"
    },
    {
     "expr": "max by(version, service)(time()-process_start_time_seconds{version!=\"\"})",
     "legendFormat": "Max {{service}} {{version}}"
    }
   ]
  },
  {
   "title": "Gardener V2 and K8S Parser Uptime",
   "type": "graph",
   "description": "Uptimes for V2 Gardener and Parsers.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg by(run, pod_template_hash)(time()-process_start_time_seconds{container=~\"etl-.*\"})",
     "legendFormat": "{{run}} {{pod_template_hash}}"
    },
    {
     "expr": "count by(container, pod_template_hash, value)(etl_commit_hash{container=~\"etl-parser.*\"})",
     "legendFormat": "Parser Instances {{pod_template_hash}} - Git: {{value}} "
    },
    {
     "expr": "count by(run, pod_template_hash)(process_start_time_seconds{container=~\"etl-gardener.*\"})",
     "legendFormat": "Gardener Instances {{pod_template_hash}}"
    }
   ]
  },
  {
   "title": "2.0 Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "V2 Task Date of Recent State Updates",
     "type": "graph",
     "description": "Task dates of the most recent updates to each task state.\n\nNOTE: In sandbox, we now process only a small subset of the requests, to get high throughput and test across the full date range quickly.  Cycle time is less than a day for sandbox, compared with one or two weeks for production.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dateTimeAsIso", "label": "State update for task date" }
     ],
     "targets": [
      {
       "expr": "1000*quantile_over_time(0.8, gardener_state_date{datatype=~\"$datatypes\", state=~\"$states2\"}[5m])",
       "legendFormat": "{{datatype}} {{state}}"
      },
      {
       "expr": "1000*quantile_over_time(0.8, gardener_state_date{state=~\"$states2\"}[5m])",
       "legendFormat": "{{datatype}} {{state}}"
      }
     ]
    },
    {
     "title": "Parsers - Process Resident Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(container, instance) (process_resident_memory_bytes{container=~\"etl-.*\"})",
       "legendFormat": "Instance Ram {{container}} - {{instance}}"
      },
      {
       "expr": "avg by(container, pod_template_hash) (process_resident_memory_bytes{container=~\"etl-.*|stats.*\"})",
       "legendFormat": "Average Ram {{container}} - {{pod_template_hash}}"
      }
     ]
    },
    {
     "title": "Parser Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(process_cpu_seconds_total{container=\"etl-parser\"}[2m])/etl_num_cpu{container=\"etl-parser\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg by (pod_template_hash)(rate(process_cpu_seconds_total{container=\"etl-parser\"}[10m])/etl_num_cpu)",
       "legendFormat": "Average {{pod_template_hash}}"
      },
      {
       "expr": "avg by (pod_template_hash)(etl_num_cpu{container=\"etl-parser\"})",
       "legendFormat": "Num CPU"
      }
     ]
    },
    {
     "title": "GCS JSON Write Failures",
     "type": "graph",
     "description": "Not clear why there is a small background failure rate.  Probably should investigate.\n\nTODO - separate GCS read and write error metrics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Failures/Minute" }
     ],
     "targets": [
      {
       "expr": "60 * sum by (kind, table)(rate(etl_backend_failure_count[10m]))",
       "legendFormat": "{{table}} Failures/Min {{kind}}"
      },
      {
       "expr": "1000*(sum by (table)(rate(etl_backend_failure_count{kind=\"googleapi.Error\"}[30m])) OR vector(0))/(sum by( table)(rate(etl_test_file_size_bytes_count{}[30m])) OR vector(1))",
       "legendFormat": "{{table}} Failures Per Thousand Files"
      }
     ]
    },
    {
     "title": "Processing Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(table)(rate(etl_test_file_size_bytes_sum{}[30m]))",
       "legendFormat": "Bytes/Sec {{table}}"
      }
     ]
    },
    {
     "title": "Median Filesize",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5,sum by(le, table)(rate(etl_test_file_size_bytes_bucket{}[1h])))",
       "legendFormat": "Bytes/File {{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Date of Recent State Updates",
     "type": "graph",
     "description": "Task dates of the most recent updates to each task state.\n\nNOTE: In sandbox, we now process only a small subset of the requests, to get high throughput and test across the full date range quickly.  Cycle time is less than a day for sandbox, compared with one or two weeks for production.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "dateTimeAsIso", "label": "State update for task date" }
     ],
     "targets": [
      {
       "expr": "1000*quantile_over_time(0.2, gardener_state_date{state=~\"$states\"}[20m])",
       "legendFormat": "{{deployment}} {{state}}"
      }
     ]
    },
    {
     "title": "Parsers - Process Resident Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (process_resident_memory_bytes{service=~\"etl-batch-parser\"})",
       "legendFormat": "inst {{instance}}"
      },
      {
       "expr": "avg by(service,version) (process_resident_memory_bytes{service=~\"etl-batch-parser\"})",
       "legendFormat": "Average: {{service}}:{{version}}"
      },
      {
       "expr": "count by(service,version) (process_start_time_seconds{service=~\"etl-batch-parser\"})",
       "legendFormat": "Instances: {{service}}:{{version}}"
      }
     ]
    },
    {
     "title": "Parser CPU - Per-instance & Avg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "percentunit", "label": "CPU %" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{service=~\"etl-.*\"}[2m])/etl_num_cpu ",
       "legendFormat": "Instance CPU {{instance}}"
      },
      {
       "expr": "avg(rate(process_cpu_seconds_total{service=~\"etl-.*\"}[5m])/etl_num_cpu)",
       "legendFormat": "Average Parser CPU"
      },
      {
       "expr": "count by(service) (process_start_time_seconds{service=~\"etl-.*\"})",
       "legendFormat": "Instance Count"
      },
      { "expr": "avg by (version)(etl_num_cpu)", "legendFormat": "Num CPU" }
     ]
    },
    {
     "title": "Backend Failure Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Failures/Minute" }
     ],
     "targets": [
      {
       "expr": "sum by (kind, table)(60*rate(etl_backend_failure_count[10m]))"
      }
     ]
    },
    {
     "title": "Processing Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(table)(rate(etl_test_file_size_bytes_sum{}[30m]))",
       "legendFormat": "Bytes/Sec {{table}}"
      }
     ]
    },
    {
     "title": "Median Filesize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5,sum by(le, table)(rate(etl_test_file_size_bytes_bucket{}[10m])))",
       "legendFormat": "Bytes/File {{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Annotator Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime and Incoming Request Rates",
     "type": "graph",
     "description": "These are the per second request rates to the Annotation Service.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "avg by(service, version)(time()-process_start_time_seconds{service=~\"annotator\"})",
       "legendFormat": "Uptime: {{service}} {{version}}"
      },
      {
       "expr": "sum by (type, detail)(rate(annotator_latency_hist_usec_count{service=\"annotator\"}[1h]))",
       "legendFormat": "Requests: {{type}} {{detail}}"
      }
     ]
    },
    {
     "title": "Annotation Service Request Rate Per Datatype / Result",
     "type": "graph",
     "description": "Ripples in the various metrics likely reflect oscillations in the different queues feeding the ETL pipelines.  The queues slow down as they empty, and push faster when refilled.  This changes the mix of requests for different data types.  Since the different parsers handle annotation differently, this changes the load on the annotator.\n\nWe expect to see bursts of \"reject (loading)\" when a new dataset is requested.  However, we DON'T want to see reject (cache full).  These might mean that gardener is misbehaving, or that the dataset cache is broken in some way.\n\nEarly (<2013) NDTTests trigger a burst of \"missing annotations for client IP\". Not clear why.\n \nWe are sometimes seeing long bursts of \"Invalid IP\".  This requires more investigation - likely a problem with the raw data.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Requests / Second" }
     ],
     "targets": [
      {
       "expr": "sum by(test_type) (rate(etl_annotator_Annotation_Time_Summary_count{}[1h]))",
       "legendFormat": "Requests {{test_type}}"
      },
      {
       "expr": "sum by(source)(rate(etl_annotator_Error_Count{service=~\"etl-.*\"}[1h]))",
       "legendFormat": "Errors: {{source}}"
      }
     ]
    },
    {
     "title": "K8S Parser V2 Requests and Error Rate",
     "type": "graph",
     "description": "v2 API requests and error rate from K8S parsers.\n\nNOTE:  These should be zero, since the 2.0 pipeline should get annotations from uuid-annotator.  However, we haven't removed the annotator calls yet.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "V2 Requests/Sec" }
     ],
     "targets": [
      {
       "expr": "sum by(test_type) (rate(etl_annotator_Annotation_Time_Summary_count{container=\"etl-parser\"}[1h]))",
       "legendFormat": "V2 Requests/sec {{test_type}}"
      },
      {
       "expr": "(sum(rate(annotator_external_latency_hist_msec_count{container=\"etl-parser\", detail!=\"success\"}[10m])) or vector(0)) / (sum(rate(annotator_external_latency_hist_msec_count{container=\"etl-parser\"}[10m])) or vector(1)) > .01",
       "legendFormat": "High Error Rate"
      },
      {
       "expr": "(sum(rate(annotator_external_latency_hist_msec_count{container=\"etl-parser\", detail!=\"success\"}[10m])) or vector(0)) / (sum(rate(annotator_external_latency_hist_msec_count{container=\"etl-parser\"}[10m])) or vector(1))",
       "legendFormat": "Error Rate"
      }
     ]
    },
    {
     "title": "Annotation Service Internal Latency",
     "type": "graph",
     "description": "The annotation service runs in AppEngine Flex.  The term \"legacy\" refers to the legacy geolite1 maxmind datasets, NOT the legacy pipeline.\n\nRequest service time varies primarily on the number of IP addresses requested.  Requests of up to 5 are typically completed in about 100 usec.  Large requests of 400+ IPs typically take 2.5 msec.\n\nWhen there are large numbers of small requests, the worst case large request times spike, likely due to lock contention.  We might want to optimize this a bit better.\n\nRoughly 50% of the time is spent marshallling and unmarshallling.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "µs", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(annotator_latency_hist_usec_bucket[30m])) by (version, le, type, detail))",
       "legendFormat": "Median {{type}} {{detail}}"
      },
      {
       "expr": "topk(1, histogram_quantile(0.99, sum(rate(annotator_latency_hist_usec_bucket[30m])) by (version, le, type, detail)))",
       "legendFormat": "Worst 0.99 {{type}} {{detail}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(annotator_latency_hist_usec_bucket[30m])) by (version, le))",
       "legendFormat": "Median request {{version}}"
      }
     ]
    },
    {
     "title": "Annotation Service - Process Resident Memory",
     "type": "graph",
     "description": "These currently run on machines with 257GB available memory.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by(service,version) (process_resident_memory_bytes{service=~\"annotator.*\"})",
       "legendFormat": "Average: {{service}}:{{version}}"
      },
      {
       "expr": "avg by(service,version, instance) (process_resident_memory_bytes{service=~\"annotator.*\"})",
       "legendFormat": "Instances: {{service}}:{{version}}"
      }
     ]
    }
   ]
  }
 ]
}