{
 "title": "Pipeline: SLIs",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "mlab-sandbox,mlab-staging,mlab-oti"
   },
   { "name": "PrometheusDS", "query": "prometheus" },
   { "name": "Gardener2_DS", "label": "Gardener 2.0 Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Freshness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Daily Jobs (Last 4 Days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datatype) (bq_gardener_daily_done_last_4_days)",
     "legendFormat": "{{datatype}} "
    }
   ]
  },
  {
   "title": "Gardener Latest Daily Job Completed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(gardener_jobs_total{status=\"success\", daily=\"true\"}[1d])) by (datatype)",
     "legendFormat": "{{datatype}} "
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Parser Failure Rate (Tasks / Hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(sum(rate(etl_task_total{status!=\"OK\", cluster=\"data-pipeline\"}[1h])) by (table) /\nsum(rate(etl_task_total{cluster=\"data-pipeline\"}[1h])) by (table))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Parser Failure Rate (Tests / Hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(sum(rate(etl_test_total{status!=\"ok\", cluster=\"data-pipeline\"}[1h])) by (table) /\nsum(rate(etl_test_total{cluster=\"data-pipeline\"}[1h])) by (table))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Gardener Failure Rate (Jobs / Day)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(gardener_jobs_total{status!=\"success\"}[1d])) by (datatype) /\nsum(rate(gardener_jobs_total[1d])) by (datatype))",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gardener Self-Reported Historical Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datatype) (increase(gardener_jobs_total{status=\"success\", daily=\"false\"}[1d]))",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "BigQuery Exporter Verified Historical Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datatype) (bq_gardener_historical_throughput)",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "Parser Task Rate (Hourly)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etl_task_total{cluster=\"data-pipeline\"}[1h])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}