{
 "title": "Pipeline: Gardener",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Gardener Deployment",
    "query": "label_values(up{deployment=~\"etl-gardener-.*\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks In Flight",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gardener_tasks_in_flight{deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "GoRoutine Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    },
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"etl-gardener\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Warnings and Failures Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gardener_warning_total{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "Warning: {{status}}"
    },
    {
     "expr": "gardener_fail_total{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "Failure: {{status}}"
    }
   ]
  },
  {
   "title": "Time in State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment, quantile, state)(-gardener_state_time_summary{quantile=\"0.5\", deployment=~\"$deployment\"})",
     "legendFormat": "q:{{quantile}} {{state}} {{deployment}}"
    }
   ]
  },
  {
   "title": "Start and Completion Rate",
   "type": "graph",
   "description": "Number of tasks started and completed, per hour.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Tasks / Hour" }
   ],
   "targets": [
    {
     "expr": "rate(gardener_started_total{deployment=~\"$deployment\"}[3h])*3600",
     "legendFormat": "Started {{deployment}}"
    },
    {
     "expr": "rate(gardener_completed_total{deployment=~\"$deployment\"}[3h])*3600",
     "legendFormat": "Completed {{deployment}}"
    }
   ]
  }
 ]
}