{
 "title": "Pipeline: NDT Batch Throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks/Min by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(60*rate(etl_task_count{service=\"etl-batch-parser\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Worker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(state)(etl_worker_state{service=\"etl-batch-parser\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (process_resident_memory_bytes{service=\"etl-batch-parser\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per Instance Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "count(process_start_time_seconds{service=\"etl-batch-parser\"})",
     "legendFormat": "instance count"
    },
    {
     "expr": "sum by(instance)(time()-process_start_time_seconds{service=\"etl-batch-parser\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Count By Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_worker_count{service=\"etl-batch-parser\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per instance cpu utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"etl-batch-parser\"}[2m])/2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Approximate Insertion Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "0.99 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "0.95 {{status}}"
    },
    {
     "expr": "(sum by(le, status) (rate(etl_insertion_time_seconds_sum{service=\"etl-batch-parser\"}[5m]))) / (sum by(le, status)(rate(etl_insertion_time_seconds_count{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "0.5 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "0.25 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-batch-parser\"}[5m])))",
     "legendFormat": "0.05 {{status}}"
    }
   ]
  },
  {
   "title": "Backend Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kind)(increase(etl_backend_failure_count{service='etl-batch-parser'}[$interval]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Annotator request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(etl_annotator_Annotation_Time_Summary{quantile=\"0.99\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.99 {{test_type}}"
    },
    {
     "expr": "sum(etl_annotator_Annotation_Time_Summary{quantile=\"0.9\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.9 {{test_type}}"
    },
    {
     "expr": "sum(etl_annotator_Annotation_Time_Summary{quantile=\"0.5\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.5 {{test_type}}"
    }
   ]
  },
  {
   "title": "Annotation time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.99\"})",
     "legendFormat": ".99 {{test_type}}"
    },
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.9\"})",
     "legendFormat": ".9 {{test_type}}"
    },
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.5\"})",
     "legendFormat": ".5 {{test_type}}"
    }
   ]
  }
 ]
}