{
 "title": "Pipeline: Parser",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(etl_worker_count, table)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(etl_worker_count, service)"
   },
   { "name": "show_count", "label": "Show count", "query": "absent,sum by(service)" }
  ]
 },
 "panels": [
  { "title": "Errors - $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase, status, retries, service)(increase(etl_gcs_retry_count{service=~\"$service\", table=~\"$table\"}[$interval]))",
     "legendFormat": "{{phase}} : {{status}} : {{retries}} : {{service}}"
    },
    {
     "expr": "sum by(kind, service) (rate(etl_backend_failure_count{service=~\"$service\", table=~\"$table\"}[5m]))",
     "legendFormat": "{{kind}} : {{service}}"
    }
   ]
  },
  {
   "title": "Test Error Count by Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind, service, table)(increase(etl_error_count{service=~\"$service\", table=~\"$table\"}[$interval]))",
     "legendFormat": "Error {{filetype}} : {{kind}} : {{service}} : {{table}}"
    }
   ]
  },
  {
   "title": "Annotator Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (increase(etl_annotator_Annotation_Time_Summary_count{service=~\"$service\"}[$interval]))",
     "legendFormat": "Requests : {{service}}"
    },
    {
     "expr": "sum by(source, service)(increase(etl_annotator_Error_Count{service=~\"$service\"}[$interval]))",
     "legendFormat": "Errors: {{source}}"
    }
   ]
  },
  { "title": "Uptime, RAM, CPU - $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime - Per-instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(time()-process_start_time_seconds{service=~\"$service\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "$show_count(count by(service) (process_start_time_seconds{service=~\"$service\"}))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "RAM - Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (process_resident_memory_bytes{service=~\"$service\"})",
     "legendFormat": "inst {{instance}}"
    },
    {
     "expr": "$show_count (count by(service) (process_start_time_seconds{service=~\"$service\"}))",
     "legendFormat": "Instances: {{service}}"
    },
    {
     "expr": "avg by(service) (process_resident_memory_bytes{service=~\"$service\"})",
     "legendFormat": "Average: {{service}}"
    }
   ]
  },
  {
   "title": "CPU - Per-instance & Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"$service\"}[2m])/2",
     "legendFormat": "inst {{instance}}"
    },
    {
     "expr": "avg(rate(process_cpu_seconds_total{service=~\"$service\"}[5m])/2)",
     "legendFormat": "avg {{instance}}"
    },
    {
     "expr": "$show_count(count by(service) (process_start_time_seconds{service=~\"$service\"}))",
     "legendFormat": "Instances"
    }
   ]
  },
  { "title": "Worker Aggregates - $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Worker Count By Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_worker_count{service=~\"$service\", table=~\"$table\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(service) (etl_worker_count{service=~\"$service\", table=~\"$table\"})",
     "legendFormat": "sum : {{service}}"
    }
   ]
  },
  {
   "title": "Worker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(state, service)(etl_worker_state{service=~\"$service\", table=~\"$table\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Worker QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "sum by(version, status, service) (irate(etl_worker_duration_seconds_count{service=~\"$service\"}[4m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Task archive & Test files - $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Task Totals by Version / Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status, version, service)(rate(etl_task_count{service=~\"$service\", table=~\"$table|unknown\"}[$interval]))",
     "legendFormat": "{{version}} : {{status}}"
    },
    {
     "expr": "$show_count(count by(service) (process_start_time_seconds{service=~\"$service\"}))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Tasks/Min by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status, service)(60*irate(etl_task_count{service=~\"$service\", table=~\"$table\"}[4m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Successful Tasks/Min by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*irate(etl_task_count{service=\"$service\", table=~\"$table\", status=\"OK\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tests/Sec by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, status, service)(irate(etl_test_count{service=~\"$service\", table=~\"$table\", filetype!=\"meta\"}[4m]))",
     "legendFormat": "{{filetype}} : {{status}} : {{service}}"
    }
   ]
  },
  {
   "title": "Test Count by Type [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(version, filetype, status, service)(increase(etl_test_count{service=~\"$service\", table=~\"$table\"}[$interval]))",
     "legendFormat": "{{version}} : {{filetype}} : {{status}} : {{service}}"
    }
   ]
  },
  {
   "title": "Test Warning Count by Table/Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind, service)(increase(etl_warning_count{service=~\"$service\", table=~\"$table\"}[$interval]))",
     "legendFormat": "Warning {{filetype}} : {{kind}} : {{service}}"
    }
   ]
  },
  { "title": "Performance - $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "BQ Insertion Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, status, service) (rate(etl_insertion_time_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} 0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, status, service) (rate(etl_insertion_time_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} 0.95"
    },
    {
     "expr": "(sum by(le, status) (rate(etl_insertion_time_seconds_sum{service=~\"$service\"}[5m]))) / (sum by(le, status, service)(rate(etl_insertion_time_seconds_count{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, status, service) (rate(etl_insertion_time_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} 0.5"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, status, service) (rate(etl_insertion_time_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} 0.25"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le, status, service) (rate(etl_insertion_time_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{status}} 0.05"
    },
    {
     "expr": "$show_count(count by(service) (process_start_time_seconds{service=~\"$service\"}))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Worker Duration Quantiles (Successful)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, service) (rate(etl_worker_duration_seconds_bucket{service=~\"$service\", status=\"OK\"}[$interval])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, service) (rate(etl_worker_duration_seconds_bucket{service=~\"$service\", status=\"OK\"}[$interval])))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, service) (rate(etl_worker_duration_seconds_bucket{service=~\"$service\", status=\"OK\"}[$interval])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, service) (rate(etl_worker_duration_seconds_bucket{service=~\"$service\", status=\"OK\"}[$interval])))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le, service) (rate(etl_worker_duration_seconds_bucket{service=~\"$service\", status=\"OK\"}[$interval])))",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Total Insertion Calls [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum by(version, service)(increase(etl_insertion_time_seconds_count{service=~\"$service\"}[$interval]))",
     "legendFormat": "increase - {{version}} {{service}}"
    },
    {
     "expr": "sum by(version, service)(etl_insertion_time_seconds_count{service=~\"$service\"})",
     "legendFormat": "total - {{version}} {{service}}"
    }
   ]
  },
  {
   "title": "Insertions per Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_insertion_time_seconds_count{service=~\"$service\", status=\"succeed\"}",
     "legendFormat": "ok: {{instance}}"
    },
    {
     "expr": "etl_insertion_time_seconds_count{service=~\"$service\", status=\"fail\"}",
     "legendFormat": "fail: {{instance}}"
    }
   ]
  },
  { "title": "Size Stats : $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "File sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": "0.99999"
    },
    {
     "expr": " histogram_quantile(0.999, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".999"
    },
    {
     "expr": " histogram_quantile(0.99, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".99"
    },
    {
     "expr": " histogram_quantile(0.95, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": " histogram_quantile(0.90, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": " histogram_quantile(0.50, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".50"
    },
    {
     "expr": " histogram_quantile(0.10, sum by(le, service)(rate(etl_test_file_size_bytes_bucket{service=~\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".10"
    }
   ]
  },
  {
   "title": "Row sizes (json) : $service -> $table",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": "0.99999"
    },
    {
     "expr": " histogram_quantile(0.999, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".999"
    },
    {
     "expr": " histogram_quantile(0.99, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".99"
    },
    {
     "expr": " histogram_quantile(0.95, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": " histogram_quantile(0.90, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": " histogram_quantile(0.50, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".50"
    },
    {
     "expr": " histogram_quantile(0.10, sum by(le)(rate(etl_row_json_size_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".10"
    }
   ]
  },
  {
   "title": "Rows per File -- Total Field Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, sum by(le)(rate(etl_entry_field_count_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": "1.00"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(etl_entry_field_count_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.95, sum by(le)(rate(etl_entry_field_count_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(.90, sum by(le)(rate(etl_entry_field_count_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le)(rate(etl_entry_field_count_bucket{service=\"$service\", table=\"$table\"}[10m])))",
     "legendFormat": ".50"
    }
   ]
  },
  {
   "title": "Fields per Row -- Snapshot Field Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.999, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": "0.999"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.80, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".80"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.20, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".20"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".10"
    },
    {
     "expr": "histogram_quantile(0.010, sum by(le)(rate(etl_delta_num_field_bucket{service=\"$service\"}[10m])))",
     "legendFormat": ".01"
    }
   ]
  }
 ]
}