{
 "title": "Pipeline: Autoloader",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "period",
    "label": "Period",
    "query": {
     "query": "label_values(autoloader_loaded_dates, period)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Loaded Dates",
   "type": "graph",
   "description": "Most recently loaded dates.\n\n\"Invalid date\" appears when Gardener has been restarted recently.  Haven't figured out how to suppress that.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dateTimeAsIso", "label": "Date" }
   ],
   "targets": [
    {
     "expr": "1000*quantile_over_time(0.8, autoloader_loaded_dates{period=~\"$period\"}[5m])",
     "legendFormat": "{{experiment}}/{{datatype}} {{period}} {{status}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(autoloader_duration_bucket[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (experiment, datatype) (increase(autoloader_duration_count[10m]))",
     "legendFormat": "{{experiment}}/{{datatype}}"
    }
   ]
  },
  {
   "title": "Job Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (experiment, datatype) (increase(autoloader_duration_count{status!=\"OK\"}[10m]))",
     "legendFormat": "{{experiment}}/{{datatype}}"
    }
   ]
  },
  {
   "title": "Total BigQuery Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (operation) (increase(autoloader_bigquery_operations_total[10m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "BigQuery Operation Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (experiment, datatype, operation) (increase(autoloader_bigquery_operations_total{status!=\"OK\"}[10m]))",
     "legendFormat": "{{experiment}}/{{datatype}} {{operation}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"autoloader\"}[3m])",
     "legendFormat": "autoloader {{instance}}"
    }
   ]
  },
  {
   "title": "RSS RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"autoloader\"}",
     "legendFormat": "autoloader {{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(pod_template_hash)(time()-process_start_time_seconds{container=\"autoloader\"})",
     "legendFormat": "Pod hash {{pod_template_hash}}"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "count by(pod_template_hash)(process_start_time_seconds{container=\"autoloader\"})",
     "legendFormat": "Pod hash {{pod_template_hash}}"
    }
   ]
  }
 ]
}