{
 "title": "Pipeline: Annotation Service",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "10m,30m,1h,3h,6h,12h,1d,2d,7d" },
   {
    "name": "service",
    "query": "label_values(etl_annotator_Annotation_Time_Summary, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Internal Time to Serve Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "annotator_Request_Response_Time_Summary",
     "legendFormat": "Quantile: {{quantile}}, Instance {{instance}}"
    }
   ]
  },
  {
   "title": "Mean and 99th Percentile Response Times",
   "type": "graph",
   "description": "Means should be under 1 msec, and 99th percentiles should be under 1 second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "avg(rate(annotator_Request_Response_Time_Summary_sum[5m])/rate(annotator_Request_Response_Time_Summary_count[5m])) by (service)",
     "legendFormat": "Mean {{service}}"
    },
    {
     "expr": "max(annotator_Request_Response_Time_Summary{quantile=\"0.99\"}) by (service)",
     "legendFormat": "Worst 99th {{service}}"
    }
   ]
  },
  {
   "title": "Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum by(version, service)(rate(etl_annotator_Annotation_Time_Summary_sum[5m]))/sum by(version, service)(rate(etl_annotator_Annotation_Time_Summary_count[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ETL-Annotator Connection Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by(source)(increase(etl_annotator_Error_Count[$interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Percentiles of Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "avg by (service, quantile)(etl_annotator_Annotation_Time_Summary{service=~\"$service\"})",
     "legendFormat": "Quantile: {{quantile}}, Service: {{service}}"
    }
   ]
  },
  {
   "title": "Downloader Error Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(downloader_Error_Count[5m])"
    }
   ]
  },
  {
   "title": "Time Since Last Successful Download",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-downloader_last_success_time_seconds"
    }
   ]
  },
  {
   "title": "Failed Downloads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(downloader_Download_Failed[5m])"
    }
   ]
  },
  {
   "title": "Annotator CPU Utilization",
   "type": "graph",
   "description": "Target CPU is 60%.  App Engine should add more instances if utilization is frequently above 60%, and drop instances if usually below.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "90th Percentile CPU Utilization"
    }
   ],
   "targets": [
    {
     "expr": "quantile(0.9, irate(process_cpu_seconds_total{service=~\"annotator.*\"}[2m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Annotator Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "GiBytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,process_virtual_memory_bytes{service=\"annotator\"}/1024/1024/1024)",
     "legendFormat": "Topk {{instance}}"
    },
    {
     "expr": "quantile(0.5,process_virtual_memory_bytes{service=\"annotator\"}/1024/1024/1024)",
     "legendFormat": "Median (by instance)"
    },
    {
     "expr": "quantile(0.0,process_virtual_memory_bytes{service=\"annotator\"}/1024/1024/1024)",
     "legendFormat": "Min (by instance)"
    }
   ]
  },
  {
   "title": "# Of Requests Being Handled Right Now",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "annotator_Running_Annotation_Requests_Count"
    }
   ]
  },
  {
   "title": "IP Lookups Per Second",
   "type": "graph",
   "description": "Aggregate annotation rate (per service), and median annotations/CPU-sec.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops", "label": "Service Throughput - IP/sec" }
   ],
   "targets": [
    {
     "expr": "-avg(rate(annotator_Annotation_Lookups_Total{service=\"annotator\"}[5m]))",
     "legendFormat": "Throughput (annotator)"
    },
    {
     "expr": "avg by (service)(rate(annotator_Annotation_Lookups_Total{service!=\"annotator\"}[5m]))",
     "legendFormat": "Throughput ({{service}})"
    },
    {
     "expr": "-quantile(0.5, rate(annotator_Annotation_Lookups_Total{service=\"annotator\"}[5m])/rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "Median Annotations/CPU-sec (annotator)"
    },
    {
     "expr": "quantile by (service)(0.5, rate(annotator_Annotation_Lookups_Total{service!=\"annotator\"}[5m])/rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "Median Annotations/CPU-sec ({{service}})"
    }
   ]
  },
  {
   "title": "Annotator Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(rate(annotator_Annotation_Requests_Total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total IP Lookups Per Second",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(annotator_Annotation_Lookups_Total[5m]))"
    }
   ]
  },
  {
   "title": "Total # Of IPs Looked Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(annotator_Annotation_Lookups_Total)"
    }
   ]
  },
  {
   "title": "Total # Of Requests Served",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(annotator_Annotation_Requests_Total)"
    }
   ]
  },
  {
   "title": "Total Annotator Requests Per Second",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(annotator_Annotation_Requests_Total[5m]))"
    }
   ]
  }
 ]
}