{
 "title": "Pipeline: Batch (in progress)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase, status, retries)(increase(etl_gcs_retry_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "{{phase}} : {{status}} : {{retries}}"
    }
   ]
  },
  {
   "title": "Test Error Count by Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind)(increase(etl_error_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "Error {{filetype}} : {{kind}}"
    }
   ]
  },
  {
   "title": "Annotator Error Count [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etl_annotator_Annotation_Time_Summary_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(source)(increase(etl_annotator_Error_Count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "Errors: {{source}}"
    }
   ]
  },
  {
   "title": "Per Instance Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(time()-process_start_time_seconds{service=\"etl-ndt-batch-parser\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(process_start_time_seconds{service=\"etl-ndt-batch-parser\"})",
     "legendFormat": "instance count"
    }
   ]
  },
  {
   "title": "Worker Count By Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_worker_count{service=\"etl-ndt-batch-parser\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(state)(etl_worker_state{service=\"etl-ndt-batch-parser\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task Totals by Version / Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status, version)(increase(etl_task_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "{{version}} : {{status}}"
    }
   ]
  },
  {
   "title": "Tasks/Min by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(60*rate(etl_task_count{service=\"etl-ndt-batch-parser\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Successful Tasks/Min by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(60*rate(etl_task_count{service=\"etl-ndt-batch-parser\", status=\"OK\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tests/Sec by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, status)(rate(etl_test_count{service=\"etl-ndt-batch-parser\", filetype!=\"meta\"}[2m]))",
     "legendFormat": "{{filetype}} : {{status}}"
    }
   ]
  },
  {
   "title": "Test Count by Type [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(version, filetype, status)(increase(etl_test_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "{{version}} : {{filetype}} : {{status}}"
    }
   ]
  },
  {
   "title": "Test Warning Count by Table/Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind)(increase(etl_warning_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "Warning {{filetype}} : {{kind}}"
    }
   ]
  },
  {
   "title": "Approximate Insertion Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "0.99 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "0.95 {{status}}"
    },
    {
     "expr": "(sum by(le, status) (rate(etl_insertion_time_seconds_sum{service=\"etl-ndt-batch-parser\"}[5m]))) / (sum by(le, status)(rate(etl_insertion_time_seconds_count{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "0.5 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "0.25 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-ndt-batch-parser\"}[5m])))",
     "legendFormat": "0.05 {{status}}"
    }
   ]
  },
  {
   "title": "Approximate Snaplog Size Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9999, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": ".9999"
    },
    {
     "expr": "histogram_quantile(.99, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": "0.05"
    },
    {
     "expr": "histogram_quantile(0.01, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": "0.01"
    }
   ]
  },
  {
   "title": "Annotation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.99\"})",
     "legendFormat": ".99 {{test_type}}"
    },
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.9\"})",
     "legendFormat": ".9 {{test_type}}"
    },
    {
     "expr": "avg by(test_type)(etl_annotator_Annotation_Time_Summary{quantile=\"0.5\"})",
     "legendFormat": ".5 {{test_type}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (process_resident_memory_bytes{service=\"etl-ndt-batch-parser\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per instance cpu utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"etl-ndt-batch-parser\"}[2m])/2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Insertion Calls [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(version)(increase(etl_insertion_time_seconds_count{service=\"etl-ndt-batch-parser\"}[$interval]))",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum by(version)(etl_insertion_time_seconds_count{service=\"etl-ndt-batch-parser\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Insertions per Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_insertion_time_seconds_count{service=\"etl-ndt-batch-parser\", status=\"succeed\"}",
     "legendFormat": "ok: {{instance}}"
    },
    {
     "expr": "etl_insertion_time_seconds_count{service=\"etl-ndt-batch-parser\", status=\"fail\"}",
     "legendFormat": "fail: {{instance}}"
    }
   ]
  },
  {
   "title": "Json sizes of largest (5%) of snaplog records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": "0.99999"
    },
    {
     "expr": " histogram_quantile(0.999, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".999"
    },
    {
     "expr": " histogram_quantile(0.99, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".99"
    },
    {
     "expr": " histogram_quantile(0.95, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": " histogram_quantile(0.90, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": " histogram_quantile(0.50, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".50"
    },
    {
     "expr": " histogram_quantile(0.10, sum by(le)(rate(etl_row_json_size_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".10"
    }
   ]
  },
  {
   "title": "Total Field Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, sum by(le)(rate(etl_entry_field_count_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": "1.00"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(etl_entry_field_count_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.95, sum by(le)(rate(etl_entry_field_count_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(.90, sum by(le)(rate(etl_entry_field_count_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le)(rate(etl_entry_field_count_bucket{service=\"etl-ndt-batch-parser\"}[10m])))",
     "legendFormat": ".50"
    }
   ]
  },
  {
   "title": "Snapshot Field Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.999, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": "0.999"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.80, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".80"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".50"
    },
    {
     "expr": "(sum by(le) (rate(etl_delta_num_field_sum{service=\"etl-ndt-parser\"}[5m]))) / (sum by(le)(rate(etl_delta_num_field_count{service=\"etl-ndt-parser\"}[5m])))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.20, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".20"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".10"
    },
    {
     "expr": "histogram_quantile(0.010, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": ".01"
    },
    {},
    {
     "expr": "histogram_quantile(.99, sum by(le)(rate(etl_delta_num_field_bucket{service=\"etl-ndt-parser\"}[10m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Annotator request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(etl_annotator_Annotation_Time_Summary{quantile=\"0.99\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.99 {{test_type}}"
    },
    {
     "expr": "avg(etl_annotator_Annotation_Time_Summary{quantile=\"0.9\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.9 {{test_type}}"
    },
    {
     "expr": "avg(etl_annotator_Annotation_Time_Summary{quantile=\"0.5\", test_type=\"NDT\"})",
     "legendFormat": "Q:0.5 {{test_type}}"
    }
   ]
  },
  {
   "title": "Backend Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kind)(increase(etl_backend_failure_count{service='etl-ndt-batch-parser'}[$interval]))",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}