{
 "title": "Pipeline: PT",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10m,1h,3h,6h,12h,18h,1d,2d,1w,4w,13w,1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Per Instance Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(time()-process_start_time_seconds{service=\"etl-traceroute-parser\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(process_start_time_seconds{service=\"etl-traceroute-parser\"})",
     "legendFormat": "instance count"
    }
   ]
  },
  {
   "title": "Storage Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase, status, retries)(increase(etl_gcs_retry_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{phase}} : {{status}} : {{retries}}"
    }
   ]
  },
  {
   "title": "Test Error Count by Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind)(increase(etl_error_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "Error {{filetype}} : {{kind}}"
    }
   ]
  },
  {
   "title": "Worker Count By Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_worker_count{service=\"etl-traceroute-parser\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(state)(etl_worker_state{service=\"etl-traceroute-parser\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task Totals by Version / Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status, version)(increase(etl_task_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{version}} : {{status}}"
    }
   ]
  },
  {
   "title": "Tasks/Min by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(60*rate(etl_task_count{service=\"etl-traceroute-parser\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Successful Tasks/Min by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(60*rate(etl_task_count{service=\"etl-traceroute-parser\", status=\"OK\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tests/Sec by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, status)(rate(etl_test_count{service=\"etl-traceroute-parser\", filetype!=\"meta\"}[2m]))",
     "legendFormat": "{{filetype}} : {{status}}"
    }
   ]
  },
  {
   "title": "Test Count by Type [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(version, filetype, status)(increase(etl_test_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{version}} : {{filetype}} : {{status}}"
    }
   ]
  },
  {
   "title": "Test Warning Count by Table/Type/Status [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind)(increase(etl_warning_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "Warning {{filetype}} : {{kind}}"
    }
   ]
  },
  {
   "title": "Approximate Insertion Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.99 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.95 {{status}}"
    },
    {
     "expr": "(sum by(le, status) (rate(etl_insertion_time_seconds_sum{service=\"etl-traceroute-parser\"}[5m]))) / (sum by(le, status)(rate(etl_insertion_time_seconds_count{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.5 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.25 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le, status) (rate(etl_insertion_time_seconds_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.05 {{status}}"
    }
   ]
  },
  {
   "title": "Approximate Snaplog Size Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9999, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": ".9999"
    },
    {
     "expr": "histogram_quantile(.99, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.05"
    },
    {
     "expr": "histogram_quantile(0.01, sum by(le) (rate(etl_web100_snaplog_file_size_bytes_bucket{service=\"etl-traceroute-parser\"}[5m])))",
     "legendFormat": "0.01"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (process_resident_memory_bytes{service=\"etl-traceroute-parser\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per instance cpu utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"etl-traceroute-parser\"}[2m])/2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Insertion Calls [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(version)(increase(etl_insertion_time_seconds_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum by(version)(etl_insertion_time_seconds_count{service=\"etl-ndt-parser\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Insertions per Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etl_insertion_time_seconds_count{service=\"etl-traceroute-parser\", status=\"succeed\"}",
     "legendFormat": "ok: {{instance}}"
    },
    {
     "expr": "etl_insertion_time_seconds_count{service=\"etl-traceroute-parser\", status=\"fail\"}",
     "legendFormat": "fail: {{instance}}"
    }
   ]
  },
  {
   "title": "Polluted Tests Count Per Site",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(metro)(increase(etl_pt_polluted_total{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{metro}} "
    }
   ]
  },
  {
   "title": "Polluted Tests Percentage Per Site",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(metro)(increase(etl_pt_polluted_total{service=\"etl-traceroute-parser\"}[$interval]))/ sum by(metro)(increase(etl_pt_test_count_per_metro{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{metro}} "
    }
   ]
  },
  {
   "title": "PT Hop Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filetype, kind)(increase(etl_error_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "PTHop {{filetype}} : {{kind}}"
    }
   ]
  },
  {
   "title": "PT not reach dest count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(metro)(increase(etl_pt_not_reach_dest_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{metro}} "
    }
   ]
  },
  {
   "title": "PT not reach dest ratio per metro",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(metro)(increase(etl_pt_not_reach_dest_count{service=\"etl-traceroute-parser\"}[$interval])) / sum by(metro)(increase(etl_pt_test_count_per_metro{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{metro}} "
    }
   ]
  },
  {
   "title": "PT Reach Dest in the Middle Count per metro",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(metro)(increase(etl_pt_more_hops_after_dest_count{service=\"etl-traceroute-parser\"}[$interval]))",
     "legendFormat": "{{metro}} "
    }
   ]
  },
  {
   "title": "PT not reach Distance Between last hop and dest V4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"32\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"31\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "Bucket 32"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"0\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "Bucket 0"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"31\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"30\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 31"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"30\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"29\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 30"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"1\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"0\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 1"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"16\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"15\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 16"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"24\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v4_bucket{le=\"23\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 24"
    }
   ]
  },
  {
   "title": "PT not reach Distance Between last hop and dest V6",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"32\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"31\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "Bucket 32"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"0\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "Bucket 0"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"31\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"30\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 31"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"30\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"29\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 30"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"1\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"0\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 1"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"16\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"15\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 16"
    },
    {
     "expr": "sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"24\", service=\"etl-traceroute-parser\"}[10m])) - ignoring (le) sum by(le)(rate(etl_pt_bits_away_from_dest_v6_bucket{le=\"23\", service=\"etl-traceroute-parser\"}[10m]))",
     "legendFormat": "bucket 24"
    }
   ]
  }
 ]
}