{
 "title": "Prometheus: Self-monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus 2.x",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{container=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "TSDB Blocks in Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_blocks_loaded)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Alert Notifications",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_notifications_dropped_total[10m])",
     "legendFormat": "Dropped"
    },
    {
     "expr": "prometheus_notifications_alertmanagers_discovered",
     "legendFormat": "AM Discovered"
    }
   ]
  },
  {
   "title": "Prometheus CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"prometheus\"}[5m])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Prometheus RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"prometheus\"}",
     "legendFormat": "Process RSS"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"prometheus\"}",
     "legendFormat": "Bytes in Go Heap"
    }
   ]
  },
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile!=\"0.01\", quantile!=\"0.05\", container=\"prometheus\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Prometheus Collection Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(scrape_duration_seconds)", "legendFormat": "MAX" },
    {
     "expr": "quantile(0.99, scrape_duration_seconds)",
     "legendFormat": "99th"
    },
    {
     "expr": "quantile(0.95, scrape_duration_seconds)",
     "legendFormat": "95th"
    },
    {
     "expr": "quantile(0.5, scrape_duration_seconds)",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up)", "legendFormat": "All Targets" },
    { "expr": "count(up == 1)", "legendFormat": "All Up Targets" },
    {
     "expr": "count(up == 1) - count(up{job=\"blackbox-targets\"} == 1) ",
     "legendFormat": "All - Up"
    },
    {
     "expr": "count(up{job=\"blackbox-targets\"} == 1) ",
     "legendFormat": "Blackbox Up"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{quantile=\"0.9\", container=\"prometheus\"}",
     "legendFormat": "{{slice}} - {{quantile}}"
    },
    {}
   ]
  },
  {
   "title": "Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])*60",
     "legendFormat": "Rate of Ingested Samples"
    },
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "Series in Memory" }
   ]
  },
  {
   "title": "Filesystem Available Estimate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "predict_linear(sum(kubelet_volume_stats_available_bytes{cluster=\"prometheus-federation\", persistentvolumeclaim=\"auto-prometheus-disk0\"})[10d:10m], 10*86400)",
     "legendFormat": "prometheus-federation - 10 days"
    },
    {
     "expr": "kubelet_volume_stats_available_bytes{cluster=\"prometheus-federation\", persistentvolumeclaim=\"auto-prometheus-disk0\"}",
     "legendFormat": "prometheus-federation - raw"
    },
    {
     "expr": "predict_linear(sum(node_filesystem_avail_bytes{node=\"prometheus-platform-cluster\", mountpoint=\"/mnt/local\"})[10d:10m], 10*86400)",
     "legendFormat": "platform - 10 days"
    },
    {
     "expr": "node_filesystem_avail_bytes{node=\"prometheus-platform-cluster\", mountpoint=\"/mnt/local\"}",
     "legendFormat": "platform - raw"
    },
    {
     "expr": "predict_linear(sum(kubelet_volume_stats_available_bytes{instance=~\"gke-data-processing.*\", persistentvolumeclaim=\"auto-prometheus-ssd0\"})[10d:10m], 10*86400)",
     "legendFormat": "data-processing - 10 days"
    },
    {
     "expr": "kubelet_volume_stats_available_bytes{instance=~\"gke-data-processing.*\", persistentvolumeclaim=\"auto-prometheus-ssd0\"}",
     "legendFormat": "data-processing - raw"
    }
   ]
  }
 ]
}