{
 "title": "Revtr sidecar monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(tcpinfo_flow_events_total, site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "tcp-info <-> revtr monitoring",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(revtr_eventsocket_events_processed_total{event=\"open\", site=~\"$site\", deployment=\"ndt\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "revtr events received"
    },
    {
     "expr": "sum(rate(revtr_eventsocket_events_skipped_total{event=\"open\", site=~\"$site\", deployment=\"ndt\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "revtr events skipped"
    },
    {
     "expr": "sum(rate(tcpinfo_flow_events_total{event=\"open\", site=~\"$site\", deployment=\"ndt\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "tcp-info events sent"
    },
    {
     "expr": "sum(rate(revtr_samples_total{site=~\"$site\", deployment=\"ndt\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "revtr samples sent"
    }
   ]
  },
  {
   "title": "Event processing time",
   "type": "heatmap",
   "description": "Time between an event is received from tcp-info and the same event is sent to the revtr API",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(revtr_event_processing_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "revtr API requests/s by deployment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(revtr_api_calls_total{site=~\"$site\", status=\"success\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "{{deployment}} (success)"
    },
    {
     "expr": "sum(rate(revtr_api_calls_total{site=~\"$site\", status=\"error\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "{{deployment}} (error)"
    }
   ]
  },
  {
   "title": "revtr API request duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(revtr_api_request_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}