{
 "title": "Scraper: Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasourcePrometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "rsync_module",
    "label": "Rsync Module",
    "query": "ndt,sidestream,paris-traceroute,switch,utilization,neubot,glasnost,ooni"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "content": "# Global stats" },
  {
   "title": "Total scraper counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{container=\"scraper\"})",
     "legendFormat": "Scraper count"
    },
    {
     "expr": "count(up{container=\"scraper\"} == 1)",
     "legendFormat": "Scraper up"
    }
   ]
  },
  {
   "title": "Prometheus CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\"prom.*\"}[2m]))",
     "legendFormat": "scraper-cluster"
    }
   ]
  },
  {
   "title": "Prometheus RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"prometheus\"}",
     "legendFormat": "scraper-cluster - RSS"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"prometheus\"}",
     "legendFormat": "scraper-cluster - Bytes in Go Heap"
    }
   ]
  },
  {
   "title": "Filesystem Avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/prometheus\"}",
     "legendFormat": "scraper-cluster"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "content": "# Scraper\n\nReal-time-ish resource utilization by scraper processes."
  },
  {
   "title": "Rsync List Runtime $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Rsync Chunk Download Time  $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by(le) (scraper_rsync_chunk_download_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (scraper_rsync_chunk_download_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (scraper_rsync_chunk_download_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Tarfile Creation Runtime $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by(le) (scraper_per_tarfile_creation_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (scraper_per_tarfile_creation_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (scraper_per_tarfile_creation_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Tarfile Chunk Upload Runtime  $rsync_module (FIX METRIC NAME)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (scraper_tarfile_chunk_upload_time_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (scraper_tarfile_chunk_upload_time_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (scraper_tarfile_chunk_upload_time_seconds_bucket{rsync_module=~\"$rsync_module\"}))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Top 5 Scraper Filesystem Usage $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_filesystem_size{container=\"fs-exporter\", mountpoint=\"/scraper_data\", deployment=~\".*$rsync_module.*\"} - node_filesystem_avail{container=\"fs-exporter\", mountpoint=\"/scraper_data\", deployment=~\".*$rsync_module.*\"})",
     "legendFormat": "{{deployment}} "
    }
   ]
  },
  {
   "title": "Top 2 Rsync List Runtime  $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(2, round(histogram_quantile(0.99, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))))",
     "legendFormat": "99th"
    },
    {
     "expr": "topk(2, round(histogram_quantile(0.95, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))))",
     "legendFormat": "95th"
    },
    {
     "expr": "topk(2, round(histogram_quantile(0.5, sum by(le) (scraper_rsync_list_runtime_seconds_bucket{rsync_module=~\"$rsync_module\"}))))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Scraper Target Count $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{container=\"scraper\", rsync_module=~\".*$rsync_module.*\"})",
     "legendFormat": "Scraper count"
    },
    {
     "expr": "count(up{container=\"scraper\", rsync_module=~\".*$rsync_module.*\"} == 1)",
     "legendFormat": "Scraper up"
    }
   ]
  },
  {
   "title": "5-min CPU usage Percentiles $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, rate(container_cpu_usage_seconds_total{pod_name=~\".*$rsync_module.*\"}[5m]))",
     "legendFormat": "99th"
    },
    {
     "expr": "quantile(0.90, rate(container_cpu_usage_seconds_total{pod_name=~\".*$rsync_module.*\"}[5m]))",
     "legendFormat": "90th"
    },
    {
     "expr": "quantile(0.5, rate(container_cpu_usage_seconds_total{pod_name=~\".*$rsync_module.*\"}[5m]))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "5-min Network +TX / -RX Percentiles $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-quantile(0.99, rate(container_network_receive_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "RX 99th"
    },
    {
     "expr": "-quantile(0.90, rate(container_network_receive_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "RX 90th"
    },
    {
     "expr": "-quantile(0.5, rate(container_network_receive_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "RX 50th"
    },
    {
     "expr": "quantile(0.99, rate(container_network_transmit_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "TX 99th"
    },
    {
     "expr": "quantile(0.90, rate(container_network_transmit_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "TX 90th"
    },
    {
     "expr": "quantile(0.5, rate(container_network_transmit_bytes_total{pod_name=~\".*$rsync_module.*\"}[5m])) * 8",
     "legendFormat": "TX 50th"
    }
   ]
  },
  {
   "title": "RAM Used Percentiles $rsync_module",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, container_memory_usage_bytes{pod_name=~\".*$rsync_module.*\"})",
     "legendFormat": "99th"
    },
    {
     "expr": "quantile(0.90, container_memory_usage_bytes{pod_name=~\".*$rsync_module.*\"})",
     "legendFormat": "90th"
    },
    {
     "expr": "quantile(0.5, container_memory_usage_bytes{pod_name=~\".*$rsync_module.*\"})",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "content": "# Scraper-Sync\n\nEnd-to-end scraper status."
  },
  {
   "title": "Min / Max / Avg last-collection-attempt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Top 10 last-collection-attempt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{machine}} {{rsync_module}}"
    }
   ]
  },
  {
   "title": "Min / Max / Avg max-raw-file-time-archived",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Top 10 max-raw-file-time-archived",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, (time() - (scraper_maxrawfiletimearchived{container=\"scraper-sync\"} != 0)) and ON(machine) (time() - process_start_time_seconds{service=\"sidestream\"}) > (24 * 60 * 60))",
     "legendFormat": "{{machine}} {{rsync_module}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
   "content": "# Scraper Details\n\nMore Scraper drill-down of resource utilization"
  },
  {
   "title": "scraper_bytes_uploaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, scraper_bytes_uploaded{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "bottomk(5, scraper_bytes_uploaded{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "scraper_files_uploaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, scraper_files_uploaded{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "bottomk(5, scraper_files_uploaded{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Top 5 Scraper Filesystem Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_filesystem_files{container=\"fs-exporter\", mountpoint=\"/scraper_data\", rsync_module=~\".*$rsync_module.*\"} - node_filesystem_files_free{container=\"fs-exporter\", mountpoint=\"/scraper_data\", rsync_module=~\".*$rsync_module.*\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Most recent 5 scraper start times (TODO: FIX QUERY)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk(5, time() - process_start_time_seconds{namespace=\"scraper\", rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Top 2 Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum by(pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\".*$rsync_module.*\"}[2m])))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top 2 Container Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum by(pod_name) (container_memory_usage_bytes{pod_name=~\".*$rsync_module.*\"}))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, kube_pod_container_status_restarts > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scrapper Success / Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(message) (scraper_success)",
     "legendFormat": "{{message}} "
    }
   ]
  }
 ]
}