{
 "title": "Scraper: Sync",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "rsync_module",
    "label": "Rsync Module",
    "query": "ndt,sidestream,paris-traceroute,switch,utilization,neubot,glasnost,ooni"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Scraper-Sync\n\nEnd-to-end scraper status."
  },
  {
   "title": "Min / Max / Avg last-collection-attempt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Top 10 last-collection-attempt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, time() - scraper_lastcollectionattempt{rsync_module=~\"$rsync_module\"})",
     "legendFormat": "{{machine}} {{rsync_module}}"
    }
   ]
  },
  {
   "title": "Min / Max / Avg max-raw-file-time-archived",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(time() - scraper_maxrawfiletimearchived{rsync_module=~\"$rsync_module\"} < time() / 2)",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Top 10 max-raw-file-time-archived",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, (time() - (scraper_maxrawfiletimearchived{container=\"scraper-sync\"} != 0)) and ON(machine) (time() - process_start_time_seconds{service=\"sidestream\"}) > (24 * 60 * 60))",
     "legendFormat": "{{machine}} {{rsync_module}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "content": "# Scraper-sync Details\n\nMore Scraper-sync information for drill-down."
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, kube_pod_container_status_restarts > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time Prometheus took to collect /metrics from scraper-sync",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{container=\"scraper-sync\", instance=~\".*:9090\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "RAM Usage (node exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"scraper-sync\"}",
     "legendFormat": "Virtual RAM"
    }
   ]
  },
  {
   "title": "RAM Usage (self-reported)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{application=\"scraper-sync\"}",
     "legendFormat": "Virtual RAM"
    },
    {
     "expr": "process_resident_memory_bytes{application=\"scraper-sync\"}",
     "legendFormat": "Resident RAM"
    }
   ]
  }
 ]
}