{
 "title": "Stats Pipeline Monitoring",
 "time": { "from": "2021-02-22T21:32:03.609Z", "to": "2021-02-23T00:26:27.766Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy system"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{nodepool=\"data-pipeline-stats-pipeline-po\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "Go stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Go memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{deployment=\"stats-pipeline\"}) ",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{deployment=\"stats-pipeline\"}[2m])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{deployment=\"stats-pipeline\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{deployment=\"stats-pipeline\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{deployment=\"stats-pipeline\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Process memory (RES + VIRT)",
   "type": "graph",
   "description": "RES memory size for the stats-pipeline process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{deployment=\"stats-pipeline\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{deployment=\"stats-pipeline\"})",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of Goroutines for the stats-pipeline service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{deployment=\"stats-pipeline\"})"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{deployment=\"stats-pipeline\"}) by (deployment)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Histogram generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Bytes processed by BQ",
   "type": "graph",
   "description": "Bytes processed by BQ while running the histogram generation queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stats_pipeline_histograms_bytes_processed",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Export status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stats_pipeline_exporter_queries_processed / stats_pipeline_exporter_queries * 100",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Bytes uploaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_uploaded_bytes) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "description": "Bytes processed by the export queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_bytes_processed) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "graph",
   "description": "Number of queries that resulted in a cache hit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_cache_hits) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "In-flight uploads",
   "type": "heatmap",
   "description": "Current uploads. More observations in the higher buckets mean the uploader workers are being used more efficiently. If too low, it might indicate more query workers are needed. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_inflight_uploads_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upload queue",
   "type": "heatmap",
   "description": "Number of query workers waiting for an upload worker to become available. If more observations fall into higher buckets it might indicate that more uploaders or fewer query workers are needed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_uploads_queue_size_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}