{
 "title": "Annotation Export Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "File system - DISK & INODES",
   "type": "graph",
   "description": "Basic disk & inodes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/var-spool-ndt\"}  - node_filesystem_avail_bytes{mountpoint=\"/var-spool-ndt\"}",
     "legendFormat": "Disk"
    },
    {
     "expr": "node_filesystem_files_free{mountpoint=\"/var-spool-ndt\"}",
     "legendFormat": "INODES"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{nodepool=\"data-processing-annotation-export\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{nodepool=\"data-processing-annotation-export\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    },
    {
     "expr": "irate(node_network_receive_bytes_total{nodepool=\"data-processing-stats-pipeline-po\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{nodepool=\"data-processing-stats-pipeline-po\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy system"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',nodepool=\"data-processing-stats-pipeline-po\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "description": "Basic node RAM",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{nodepool=~\"data-processing-stats-pipeline-po\",} - node_memory_MemFree_bytes{nodepool=~\"data-processing-stats-pipeline-po\",}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{nodepool=~\"data-processing-stats-pipeline-po\",} - node_memory_MemAvailable_bytes{nodepool=~\"data-processing-stats-pipeline-po\",}"
    }
   ]
  },
  { "title": "Go stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Go memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{deployment=\"annotation-export\", instance=~\".*:9990\"}) ",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{deployment=\"annotation-export\", instance=~\".*:9990\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{deployment=\"annotation-export\", instance=~\".*:9990\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Go memstats (Pusher)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{deployment=\"annotation-export\", instance=~\".*:9991\"}) ",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{deployment=\"annotation-export\", instance=~\".*:9991\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{deployment=\"annotation-export\", instance=~\".*:9991\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Process memory (RES + VIRT)",
   "type": "graph",
   "description": "RES memory size for the stats-pipeline process.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{deployment=\"annotation-export\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{deployment=\"annotation-export\"})",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of Goroutines for the stats-pipeline service.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{deployment=\"annotation-export\"})"
    }
   ]
  },
  {
   "title": "Go memstats (Pusher)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{deployment=\"annotation-export\", container=\"pusher\"}[2m])  ",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{deployment=\"annotation-export\", container=\"stats-pipeline\"}[2m])  ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{deployment=\"annotation-export\"}) by (deployment)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Successful Tarfile Uploads (per Datatype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(datatype) (increase (pusher_tarfiles_successful_uploads_total[2m]))",
     "legendFormat": "{{datatype}}"
    }
   ]
  },
  {
   "title": "Bytes uploaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_uploaded_bytes{deployment=\"annotation-export\"}) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "description": "Bytes processed by the export queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stats_pipeline_exporter_bytes_processed{deployment=\"annotation-export\"}) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Successful files written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(table, success) (rate (stats_pipeline_exporter_written_files_total{deployment=\"annotation-export\"}[2m]))",
     "legendFormat": "{{table}} {{success}}"
    },
    {
     "expr": "sum by(table, success) (rate (stats_pipeline_exporter_written_files{deployment=\"annotation-export\"}[2m]))",
     "legendFormat": "{{table}} {{success}}"
    }
   ]
  },
  {
   "title": "In-flight uploads",
   "type": "heatmap",
   "description": "Current uploads. More observations in the higher buckets mean the uploader workers are being used more efficiently. If too low, it might indicate more query workers are needed. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(le) (rate(stats_pipeline_exporter_inflight_uploads_bucket{deployment=\"annotation-export\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upload queue",
   "type": "heatmap",
   "description": "Number of query workers waiting for an upload worker to become available. If more observations fall into higher buckets it might indicate that more uploaders or fewer query workers are needed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (rate (stats_pipeline_exporter_uploads_queue_size_bucket{deployment=\"annotation-export\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}