{
 "title": "Wehe: access envelope",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "site", "label": "TODO(Site)", "query": "label_values(machine)" },
   { "name": "prometheusfederation", "label": "Prometheus Federation", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Wehe\n\nWehe is deployed with the Access Envelope.\nClients connect to the access envelope before the Wehe server.\nOn success, new files are written to disk and collected by pusher."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global Envelope Opens and Replay Counts by Wehe Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(envelope_requests_total{container=\"access\", status=\"success\"}[2m]))",
     "legendFormat": "envelope requests open"
    },
    {
     "expr": " sum(increase(replay_count_total[2m]))\n",
     "legendFormat": "replay server counts"
    },
    {
     "expr": "sum(increase(replay_erros_total[2m]))",
     "legendFormat": "replay server errors"
    }
   ]
  },
  {
   "title": "Global Envelope Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(envelope_requests_total{container=\"access\", status=\"success\"}[2m])) / sum(rate(envelope_requests_total{container=\"access\"}[2m]))",
     "legendFormat": "envelope requests open"
    }
   ]
  },
  {
   "title": "Total Test Files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(pusher_files_added_total{datatype=~\"replay\", deployment=~\"wehe\"}[2m]))",
     "legendFormat": "{{metro}}"
    }
   ]
  },
  {
   "title": "Total Successful Envelope Opens By Location",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(site) (label_replace(increase(envelope_requests_total{container=\"access\", status=\"success\"}[2m]), \"site\", \"$1\", \"machine\", \"mlab[1-4]-([a-z]{3}).*\"))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Envelope Errors By Location",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(status, site) (label_replace(increase(envelope_requests_total{container=\"access\", status!=\"success\"}[2m]), \"site\", \"$1\", \"machine\", \"mlab[1-4]-([a-z]{3}).*\")))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Total Test Files by Location",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(metro) (label_replace(increase(pusher_files_added_total{datatype=~\"replay\", deployment=~\"wehe\"}[2m]), \"metro\", \"$1\", \"machine\", \"mlab[1-4]-([a-z]{3}).*\"))",
     "legendFormat": "{{metro}}"
    }
   ]
  },
  {
   "title": "Global Wehe Server Replays by Name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by(name) (increase(replay_count_total[2m]))\n",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(increase(replay_erros_total[2m]))",
     "legendFormat": "replay server errors"
    }
   ]
  },
  {
   "title": "Envelope Errors By Kind",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(envelope_requests_total{container=\"access\", status!=\"success\"}[2m]))",
     "legendFormat": "{{status}} -- {{request}} -- {{site}}"
    }
   ]
  },
  {
   "title": "E2E Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(script_success{service=\"wehe_client\"}) / count(script_success{service=\"wehe_client\"})",
     "legendFormat": "success rate"
    }
   ]
  }
 ]
}