apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-state-metrics
  template:
    metadata:
      labels:
        application: kube-state-metrics
        version: "v1.2.0"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        prometheus-node: 'true'
      containers:
      - name: kube-state-metrics
        image: quay.io/coreos/kube-state-metrics:v1.2.0
        ports:
        - containerPort: 8080
