apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-state-metrics
  template:
    metadata:
      labels:
        application: kube-state-metrics
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        prometheus-node: 'true'
      containers:
      - name: kube-state-metrics
        image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.4
        ports:
        - containerPort: 8080
