apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: kube-state-metrics
        version: "v0.5.0"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        prometheus-node: 'true'
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v0.5.0
        ports:
        - containerPort: 8080
