apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigquery-exporter-24h
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bigquery-exporter-24h
  template:
    metadata:
      labels:
        run: bigquery-exporter-24h
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: bigquery-exporter
        image: measurementlab/prometheus-bigquery-exporter:v1.1.1
        args: [ "-project={{GCLOUD_PROJECT}}",
                "-refresh=24h",
                "-gauge-query=/queries/bq_gardener_parse_time.sql",
                "-gauge-query=/queries/bq_gardener.sql",
                "-gauge-query=/queries/bq_gardener_historical.sql",
              ]
        ports:
        - containerPort: 9348
        volumeMounts:
        - mountPath: /queries
          name: bigquery-config

      volumes:
      - name: bigquery-config
        configMap:
          name: bigquery-exporter-config
