apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigquery-exporter-5m
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bigquery-exporter-5m
  template:
    metadata:
      labels:
        run: bigquery-exporter-5m
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: bigquery-exporter
        image: measurementlab/prometheus-bigquery-exporter:v1.1.1
        args: [ "-project={{GCLOUD_PROJECT}}",
                "-refresh=5m",
                "-gauge-query=/queries/bq_mlabns_ratelimit.sql",
                "-gauge-query=/queries/bq_ndt_s2c.sql",
              ]
        ports:
        - containerPort: 9348
        volumeMounts:
        - mountPath: /queries
          name: bigquery-config

      volumes:
      - name: bigquery-config
        configMap:
          name: bigquery-exporter-config
