apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oauth2-proxy
  template:
    metadata:
      labels:
        run: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --client-id=3d84e669439b5e000a2c # Temporary. Do not use.
        - --client-secret=8e9f1105f338fb7414b1acf6aa33a644b5a2ad69 # Temporary. Do not use.
        - --cookie-domain={{GCLOUD_PROJECT}}.measurementlab.net
        - --cookie-refresh=1h
        - --cookie-secret={{OAUTH_PROXY_COOKIE_SECRET}}
        - --github-org=m-lab
        - --email-domain=*
        - --redirect-url=https://prometheus.{{GCLOUD_PROJECT}}.measurementlab.net/oauth2/callback
        - --set-xauthrequest=true
        - --whitelist-domain=.measurementlab.net
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
