# A ClusterRole allowing external-dns to watch for new services and ingresses
# with domains to add to the zone.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
# A ServiceAccount for the external-dns service.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default
---
# Binding the external-dns ClusterRole to the ServiceAccount above.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
