apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      run: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        run: node-exporter
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: prom/node-exporter:v1.2.2
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
      hostNetwork: true
      hostPID: true
