groups:
- name: alerts.yml
  rules:

  # Fires when the rate of registation errors (non-200 responses) is greater
  # than 1% for more than 1h.
  - alert: AutojoinCluster_TooManyRegistrationErrors
    expr: |
      (sum(rate(autojoin_request_handler_duration_sum{service="autojoin", path="/autojoin/v0/node/register", code!="200"}[1h]))) /
        sum(rate(autojoin_request_handler_duration_sum{service="autojoin", path="/autojoin/v0/node/register"}[1h])) > 0.01
    for: 1h
    labels:
      repo: ops-tracker
      severity: ticket
      cluster: autojoin
    annotations:
      summary: The rate of Autojoin register request errors is great than 1%
      description: https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#autojoincluster__toomanyregistrationerrors
      dashboard: https://grafana.mlab-oti.measurementlab.net/d/abcdef37wdji8d/autojoin?orgId=1

  # Fires when the there have been no successful registrations in the last
  # hour.
  - alert: AutojoinCluster_TooFewRegistrations
    expr: sum (increase(autojoin_request_handler_duration_sum{service="autojoin", path="/autojoin/v0/node/register", code="200"}[1h])) == 0
    for: 1h
    labels:
      repo: ops-tracker
      severity: ticket
      cluster: autojoin
    annotations:
      summary: There have been no successful registrations in the last hour
      description: https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#autojoincluster__toofewregistrations
      dashboard: https://grafana.mlab-oti.measurementlab.net/d/abcdef37wdji8d/autojoin?orgId=1

  # Fires when the metric autojoin_request_hander_duration_sum does not exist
  # for more than 1h.
  # hour.
  - alert: AutojoinCluster_APIMetricsMissing
    expr: absent(autojoin_request_handler_duration_sum{service="autojoin", path="/autojoin/v0/node/register"})
    for: 1h
    labels:
      repo: ops-tracker
      severity: ticket
      cluster: autojoin
    annotations:
      summary: The metric autojoin_request_hander_duration_sum is missing
      description: https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#autojoincluster__apimetricsmissing
      dashboard: https://grafana.mlab-oti.measurementlab.net/d/abcdef37wdji8d/autojoin?orgId=1

  # Fires when the skew between ndt7 tests to autonodes and autojoin ndt7
  # BigQuery rows exceeds more than 25% for a day. In an ideal world, every
  # ndt7 test would result in one BigQuery row. This alert allow for a margin
  # of realworld errors. It is not meant to uncover every error, but to
  # generally alert when there is something very wrong with the data pipeline
  # for the autojoin cluster.
  #
  # The 4h offset is to account for the fact that it could take up to that
  # amount of time for test data from an autonode to make it into BigQuery,
  # roughly. Daily autoloader jobs run every 3 hours, and Jostler may wait up
  # to an hour before uploading a bundle. That is, the data in BigQuery could
  # be up to 4 hours old, while the ndt7_client_test_results_total metric has
  # data not more than around 1m old.
  #
  # The expression calculates the absolute percentage difference between the
  # two totals. It doesn't care which one is more or less, only that they are
  # within 25% of each other, roughly.
  - alert: AutojoinCluster_TooMuchBigQueryRowCountSkew
    expr: |
      ((
        abs(
          sum(increase(ndt7_client_test_results_total[1d] offset 4h)) - scalar(bq_ndt7_test_total)
        )
      ) /
      (
        (sum(increase(ndt7_client_test_results_total[1d] offset 4h)) + scalar(bq_ndt7_test_total)) / 2
      )) > 0.25
    for: 1d
    labels:
      repo: ops-tracker
      severity: ticket
      cluster: autojoin
    annotations:
      summary: The number of ndt7 tests is too skewed from the number of BigQuery rows
      description: https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#autojoincluster_toomuchbigqueryrowcountskew
      dashboard: https://grafana.mlab-oti.measurementlab.net/d/abcdef37wdji8d/autojoin?orgId=1

