apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: github-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: github-receiver
  template:
    metadata:
      labels:
        run: github-receiver
      annotations:
        # TODO(soltesz): add prometheus metrics to this daemon.
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: github-receiver
        image: measurementlab/alertmanager-github-receiver:v0.0
        env:
        - name: GITHUB_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: auth-token
        args: [ "-authtoken=$(GITHUB_AUTH_TOKEN)",
                "-owner=m-lab",
                "-repo=scraper" ]
        ports:
        - containerPort: 9393
