apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
  name: alertmanager-tls-service
  namespace: default
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: alertmanager-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-tls
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
  - hosts:
    - alertmanager.{{GCLOUD_PROJECT}}.measurementlab.net
    secretName: alertmanager-tls
  rules:
  - host: alertmanager.{{GCLOUD_PROJECT}}.measurementlab.net
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-tls-service
          servicePort: 9093
