apiVersion: v1
kind: Service
metadata:
  annotations:
    # The grafana web server does not export any prometheus metrics.
    prometheus.io/scrape: 'false'
  name: grafana-tls-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: grafana-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-tls
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    # Set authentication URL and sign-in URL for OAuth.
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # This makes sure the user and email are available to the proxied 
    # application in the X-User and X-Email headers.
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      proxy_set_header X-User  $user;
      proxy_set_header X-Email $email;
spec:
  tls:
  - hosts:
    - grafana.{{GCLOUD_PROJECT}}.measurementlab.net
    secretName: grafana-tls
  rules:
  - host: grafana.{{GCLOUD_PROJECT}}.measurementlab.net
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-tls-service
          servicePort: 3000
