
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-tls-oauth
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - grafana.{{GCLOUD_PROJECT}}.measurementlab.net
    secretName: grafana-tls
  rules:
  - host: grafana.{{GCLOUD_PROJECT}}.measurementlab.net
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
